<script lang="ts">
 import {onMount} from 'svelte';import {read,Mutation} from '$lib/consumer';import {record} from '$lib/api/reliable';import {organization,type Organization} from '$lib/records';
 let code=$state(''),org=$state(''),name=$state(''),businesses=$state<Organization[]>([]),consent=$state(false),busy=$state(false),error=$state(''),message=$state('');const mutation=new Mutation();
 async function load(){busy=true;error='';name='';consent=false;try{const v=record(await read('/api/v1/organizations'));if(!Array.isArray(v.organizations))throw new Error('Could not load businesses.');businesses=v.organizations.map(organization);org=businesses[0]?.id??'';if(code)name=String(record(await read('/api/v1/dsa/code/'+encodeURIComponent(code))).name)}catch(e){error=e instanceof Error?e.message:'Could not load referral.'}finally{busy=false}}
 async function claim(){busy=true;error='';try{await mutation.send(`/api/v1/organizations/${encodeURIComponent(org)}/dsa`,{code,consent});message='Referral confirmed. Finish your business setup; Kredit checks reward qualification automatically.';sessionStorage.removeItem('kredit_dsa_referral')}catch(e){error=e instanceof Error?e.message:'Referral was not confirmed.'}finally{busy=false}}
 async function retry(){busy=true;try{await mutation.retry();message='Referral confirmed.';sessionStorage.removeItem('kredit_dsa_referral');error=''}catch(e){error=e instanceof Error?e.message:'Could not confirm referral.'}finally{busy=false}}
 onMount(()=>{code=new URLSearchParams(location.search).get('code')??sessionStorage.getItem('kredit_dsa_referral')??'';if(code)sessionStorage.setItem('kredit_dsa_referral',code);void load()});
</script>
<svelte:head><title>Confirm your referral — Kredit</title></svelte:head>
<main class="shell"><h1>Who introduced your business?</h1><p>Only the business owner can confirm this. The agent can see your business name and referral progress and may earn rewards; they cannot access your customer records.</p>{#if error}<p role="alert">{error}</p>{#if mutation.pending}<button onclick={retry} disabled={busy}>Retry the same confirmation</button>{/if}{/if}{#if message}<p role="status">{message}</p><a href={`/app/onboarding?organization=${encodeURIComponent(org)}`}>Finish business setup</a>{:else}<form onsubmit={e=>{e.preventDefault();void claim()}}><fieldset disabled={busy}><label>Referral code<input bind:value={code} oninput={()=>{name='';consent=false}} required maxlength="40"/></label><button type="button" onclick={load}>Check code and refresh businesses</button>{#if name}<p>Agent: {name}</p>{/if}<label>Business<select bind:value={org} required>{#each businesses as b}<option value={b.id}>{b.legal_name}</option>{/each}</select></label><label><input type="checkbox" bind:checked={consent} required/>This agent introduced my business to Kredit. I agree to referral attribution and progress sharing.</label><button disabled={!org||!name}>Confirm introduction</button></fieldset></form>{/if}<p><a href="/app/overview">Create your business if it is not listed</a>. Return here before accepting your first sale.</p><a href="/app/settings/security">Set up or confirm extra sign-in safety</a></main>
<style>main{max-width:45rem;padding-block:2rem}label{display:grid;gap:.4rem;margin:1rem 0}input,select,button{font:inherit;padding:.7rem}fieldset{border:0;padding:0}p{line-height:1.6}</style>
