<script lang="ts">
 import {onMount} from 'svelte';
 import VerifyIdentity from '$lib/components/VerifyIdentity.svelte';
 import {checkedJSON,record,text,publicError} from '$lib/api/reliable';
 import {MutationIntent} from '$lib/api/mutation';
 type Destination={organization_id:string;version:number;settlement_provider:string;settlement_provider_reference:string;settlement_bank_name:string;settlement_account_name:string;settlement_account_last4:string};
 type Registration={id:string;organization_id:string;provider:string;bank_code:string;account_last4:string};
 let destinations=$state<Destination[]>([]),registrations=$state<Registration[]>([]),loading=$state(true),busy=$state(false),error=$state(''),message=$state('');
 let selected=$state<Destination|null>(null),retry=$state<Registration|null>(null),action=$state('approve'),reason=$state(''),reviewed=$state(false);let intent:MutationIntent|null=null;
 async function load(){loading=true;error='';try{const data=await checkedJSON('/api/v1/ops/settlement-review',record);if(!Array.isArray(data.destinations)||!Array.isArray(data.registrations))throw new Error('Invalid bank review');destinations=data.destinations.map(value=>{const row=record(value);if(!Number.isSafeInteger(row.version)||Number(row.version)<1)throw new Error('Invalid version');return{organization_id:text(row.organization_id),version:Number(row.version),settlement_provider:text(row.settlement_provider),settlement_provider_reference:text(row.settlement_provider_reference),settlement_bank_name:text(row.settlement_bank_name),settlement_account_name:text(row.settlement_account_name),settlement_account_last4:text(row.settlement_account_last4)}});registrations=data.registrations.map(value=>{const row=record(value);return{id:text(row.id),organization_id:text(row.organization_id),provider:text(row.provider),bank_code:text(row.bank_code),account_last4:text(row.account_last4)}});if(selected&&!destinations.some(item=>item.organization_id===selected?.organization_id&&item.version===selected?.version))selected=null;if(retry&&!registrations.some(item=>item.id===retry?.id))retry=null;}catch(cause){error=publicError(cause,'Bank reviews could not be loaded.')}finally{loading=false}}
 function choose(item:Destination){selected=item;retry=null;action='approve';reason='';reviewed=false;intent=new MutationIntent('bank-review',`/api/v1/ops/settlement-review/${encodeURIComponent(item.organization_id)}`)}
 function chooseRetry(item:Registration){retry=item;selected=null;reason='';reviewed=false;intent=new MutationIntent('bank-retry',`/api/v1/ops/settlement-registrations/${encodeURIComponent(item.organization_id)}/${encodeURIComponent(item.id)}/retry`)}
 async function save(){if(!intent||busy||!reviewed)return;busy=true;error='';try{if(selected){const item=selected;await intent.run({version:item.version,provider_reference:item.settlement_provider_reference,action,reason:reason.trim()},value=>{const profile=record(record(value).profile);if(profile.settlement_state!==(action==='approve'?'verified':'rejected'))throw new Error('Review was not confirmed');return true})}else if(retry){await intent.run({reason:reason.trim()},value=>{if(record(value).retry_permitted!==true)throw new Error('Decision was not confirmed');return true})}else return;selected=null;retry=null;message='Decision saved.';await load()}catch(cause){error=publicError(cause,'The result is unconfirmed. Refresh before trying again.')}finally{busy=false}}
 onMount(load);
</script>
<svelte:head><title>Business bank review — Kredit</title></svelte:head>
<main class="shell workspace"><p class="eyebrow">Super admin</p><h1>Business bank review</h1><p>Check the account holder against the verified business and supporting ownership records. Activating a destination does not confirm that a payment has settled.</p><a href="/admin/setup">Back to launch setup</a><VerifyIdentity />
{#if error}<p role="alert">{error}</p>{/if}{#if message}<p role="status">{message}</p>{/if}<button disabled={busy||loading} onclick={load}>Refresh records</button>
{#if loading}<p role="status">Loading bank reviews…</p>{:else if !error}
<h2>Accounts awaiting ownership review</h2>{#if !destinations.length}<p>No accounts need review.</p>{/if}
{#each destinations as item(item.organization_id)}<article><p>Business: {item.organization_id}</p><p>{item.settlement_bank_name} · {item.settlement_account_name} · •••• {item.settlement_account_last4}</p><p>{item.settlement_provider} · {item.settlement_provider_reference}</p><button disabled={busy} onclick={()=>choose(item)}>Review account</button></article>{/each}
<h2>Uncertain registrations</h2>{#if !registrations.length}<p>No interrupted registrations.</p>{/if}
{#each registrations as item(item.id)}<article><p>Business: {item.organization_id}</p><p>{item.provider} · Bank {item.bank_code} · •••• {item.account_last4}</p><p>Check the original provider account. If registration succeeded, keep this request on hold while its evidence is recovered.</p><button disabled={busy} onclick={()=>chooseRetry(item)}>Provider confirmed it was not created</button></article>{/each}
{/if}
{#if selected||retry}<form onsubmit={(event)=>{event.preventDefault();void save()}}><fieldset disabled={busy}><legend>Review the effect</legend>
{#if selected}<label>Decision<select bind:value={action} onchange={()=>reviewed=false}><option value="approve">Approve this business destination</option><option value="reject">Reject this destination</option></select></label><p>{action==='approve'?'The business can use this registered destination after all other onboarding requirements are met.':'This destination will stay unavailable. The business must correct its account details.'}</p>{:else}<p>This permits the seller to retry registration. It does not send a request now. Only proceed after the provider confirms that the original request created no sub-account.</p>{/if}
<label>Evidence checked and reason<textarea bind:value={reason} oninput={()=>reviewed=false} required minlength="20" maxlength="2000"></textarea></label><p>Use evidence references. Do not enter full account numbers, identity numbers, passwords or API keys.</p><label class="confirm"><input type="checkbox" bind:checked={reviewed} required />I reviewed the evidence and this decision.</label><button disabled={!reviewed}>{busy?'Saving…':'Save decision'}</button><button type="button" onclick={()=>{selected=null;retry=null}}>Cancel</button></fieldset></form>{/if}</main>
<style>main{max-width:900px;padding-block:2rem}article,form{border:1px solid var(--color-border);border-radius:1rem;padding:1.25rem;margin-block:1rem}article p{overflow-wrap:anywhere}fieldset{display:grid;gap:1rem;border:0;padding:0}label{display:grid;gap:.5rem}input,select,textarea,button{padding:.75rem;font:inherit}textarea{min-height:7rem}.confirm{display:flex;align-items:start}</style>
