<script lang="ts">
	import{onMount}from'svelte';import{csrfHeaders,idempotencyKey}from'$lib/api/client';import ProtectedActionDialog from'$lib/components/ProtectedActionDialog.svelte';
	let items=$state<any[]>([]),selected=$state<any>(null),decision=$state(''),message=$state(''),dialogOpen=$state(false),loading=$state(true);
	async function load(){loading=true;const response=await fetch('/api/v1/ops/account-recovery?state=PENDING_REVIEW',{credentials:'include'});items=response.ok?(await response.json()).requests??[]:[];loading=false}
	function begin(item:any,nextDecision:string){selected=item;decision=nextDecision;dialogOpen=true}
	async function confirm(reason:string){const response=await fetch(`/api/v1/ops/account-recovery/${selected.id}/review`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({decision,reason,expected_version:selected.version})});const body=await response.json().catch(()=>({}));message=response.ok?'Recovery review recorded.':body.detail??'Review failed.';if(response.ok)await load();return response.ok}
	onMount(load);
</script>
<svelte:head><title>Account recovery review — Kredit</title></svelte:head>
<main class="shell workspace"><p class="eyebrow">Operations / Recovery</p><h1>Recovery review queue.</h1><p class="lede">Approval requires independent evidence, recent MFA, reviewer separation, a reason, and a 24-hour cooling-off period.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}{#if loading}<p role="status">Loading recovery requests…</p>{:else}{#each items as item}<article><header><strong>Recovery {item.id}</strong><span class="status">pending review</span></header><p>{item.independent_factor_count} independent factors · version {item.version}</p><div class="actions"><button onclick={()=>begin(item,'approve')}>Approve with cooling-off</button><button class="danger" onclick={()=>begin(item,'reject')}>Reject</button></div></article>{:else}<section class="empty-state"><h2>No recoveries awaiting review</h2><p>Protected recovery requests will appear after independent evidence is collected.</p></section>{/each}{/if}</main>
{#if selected}<ProtectedActionDialog bind:open={dialogOpen} title={`${decision==='approve'?'Approve':'Reject'} account recovery`} description={decision==='approve'?'A 24-hour cooling-off period will begin and sensitive financial changes remain blocked.':'Access will not be restored. Record the evidence-based reason for rejection.'} confirmLabel={decision==='approve'?'Approve with cooling-off':'Reject recovery'} onconfirm={confirm}/>{/if}
<style>article{margin:1rem 0;padding:1rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}header{display:flex;justify-content:space-between;gap:1rem}.actions{display:flex;flex-wrap:wrap;gap:.5rem}.actions button{padding:.65rem .85rem;border:1px solid var(--color-border);border-radius:.6rem;background:var(--color-surface);color:var(--color-foreground);font:inherit;font-weight:700;cursor:pointer}.actions .danger{color:var(--color-destructive)}</style>
