<script lang="ts">
 import {onMount} from 'svelte';
 import VerifyIdentity from '$lib/components/VerifyIdentity.svelte';
 import FeeAuthorization from '$lib/components/FeeAuthorization.svelte';
 import FeeOperations from '$lib/components/FeeOperations.svelte';
 import FeeInvoices from '$lib/components/FeeInvoices.svelte';
 import {checkedJSON,record,text,publicError} from '$lib/api/reliable';
 import {MutationIntent} from '$lib/api/mutation';
 type Business={organization_id:string;legal_name:string;version:number;billing_method:string;billing_cycle:string;billing_provider_reference:string};
 let businesses=$state<Business[]>([]),invoiceBusinesses=$state<{organization_id:string;business_name:string}[]>([]),selected=$state<Business|null>(null),org=$state(''),error=$state(''),message=$state(''),loading=$state(true),busy=$state(false),instructions=$state(''),reviewed=$state(false),revision=$state(0);
 let receipt=$state<{id:string;outstanding_kobo:number;direction:'received'|'refunded'}|null>(null),bankReference=$state(''),paid=$state(''),receivedAt=$state(''),evidence=$state('');let intent:MutationIntent|null=null;
 async function load(){loading=true;error='';try{const data=await checkedJSON('/api/v1/ops/billing-review',record);if(!Array.isArray(data.businesses)||!Array.isArray(data.invoices))throw new Error('Invalid billing review');businesses=data.businesses.map(value=>{const r=record(value);if(!Number.isSafeInteger(r.version)||Number(r.version)<=0)throw new Error('Invalid review version');return{organization_id:text(r.organization_id),legal_name:text(r.legal_name),version:Number(r.version),billing_method:text(r.billing_method),billing_cycle:text(r.billing_cycle),billing_provider_reference:text(r.billing_provider_reference)}});const seen=new Map<string,string>();for(const business of businesses){seen.set(business.organization_id,business.legal_name)}for(const value of data.invoices){const r=record(value);seen.set(text(r.organization_id),text(r.business_name))}invoiceBusinesses=Array.from(seen,([organization_id,business_name])=>({organization_id,business_name}));revision++}catch(cause){error=publicError(cause,'Billing reviews could not be loaded.')}finally{loading=false}}
 function choose(item:Business){selected=item;receipt=null;reviewed=false;instructions='';intent=new MutationIntent('invoice-approval',`/api/v1/ops/billing-review/${encodeURIComponent(item.organization_id)}`)}
 function chooseReceipt(item:{id:string;outstanding_kobo:number;credit_balance_kobo:number},direction:'received'|'refunded'){receipt={id:item.id,outstanding_kobo:direction==='refunded'?item.credit_balance_kobo:item.outstanding_kobo,direction};selected=null;reviewed=false;bankReference='';paid='';receivedAt='';evidence='';intent=new MutationIntent('fee-receipt',`/api/v1/ops/fee-invoices/${encodeURIComponent(org)}/${encodeURIComponent(item.id)}/receipts`)}
 async function save(){if(!intent||busy||!reviewed)return;busy=true;error='';try{if(selected){await intent.run({version:selected.version,billing_reference:selected.billing_provider_reference,payment_instructions:instructions.trim()},value=>{if(record(record(value).profile).billing_state!=='configured')throw new Error('Approval not confirmed');return true})}else if(receipt){if(!/^\d+(\.\d{1,2})?$/.test(paid))throw new Error('Enter a valid naira amount.');const [whole,fraction='']=paid.split('.');const amount=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(amount)||amount<=0||amount>receipt.outstanding_kobo)throw new Error('Enter an amount within the bill balance.');const timestamp=new Date(receivedAt+'+01:00');if(!Number.isFinite(timestamp.getTime()))throw new Error('Enter the receipt date and time.');await intent.run({direction:receipt.direction,bank_reference:bankReference.trim(),amount_kobo:amount,received_at:timestamp.toISOString(),evidence:evidence.trim()},value=>{if(record(record(value).invoice).id!==receipt?.id)throw new Error('Receipt not confirmed');return true})}else return;selected=null;receipt=null;message='Saved.';await load()}catch(cause){error=publicError(cause,'The change is unconfirmed. Refresh before trying again.')}finally{busy=false}}
 onMount(load);
</script>
<svelte:head><title>Fee billing — Kredit</title></svelte:head><main class="shell workspace"><p class="eyebrow">Super admin</p><h1>Fee billing</h1><p>Approve invoice arrangements and record money received by Kredit. These payments do not reduce a buyer’s debt.</p><VerifyIdentity />{#if error}<p role="alert">{error}</p>{/if}{#if message}<p role="status">{message}</p>{/if}<button disabled={busy||loading} onclick={load}>Refresh</button>
{#if loading}<p role="status">Loading billing…</p>{:else}<h2>Arrangements awaiting review</h2>{#if !businesses.length}<p>No arrangements need review.</p>{/if}{#each businesses as item(item.organization_id)}<article><h3>{item.legal_name}</h3><p>{item.billing_method.replaceAll('_',' ')} · {item.billing_cycle}</p>{#if item.billing_method==='consolidated_invoice'||item.billing_method==='split_settlement'}<button disabled={busy} onclick={()=>choose(item)}>Review arrangement</button>{:else}<p>Review the separate fee bank permission below before approving this arrangement.</p>{/if}<button disabled={busy} onclick={()=>org=item.organization_id}>Open business fee setup</button></article>{/each}<label>Business bills<select disabled={busy} bind:value={org} onchange={()=>{receipt=null;selected=null}}><option value="">Choose a business</option>{#each invoiceBusinesses as item}<option value={item.organization_id}>{item.business_name}</option>{/each}</select></label>{#if org}<FeeAuthorization {org} admin /><FeeOperations {org} admin /><FeeInvoices url={`/api/v1/ops/fee-invoices/${encodeURIComponent(org)}`} {revision} onselect={chooseReceipt} />{/if}{/if}
{#if selected||receipt}<form onsubmit={(event)=>{event.preventDefault();void save()}}><fieldset disabled={busy}><legend>Review before saving</legend>{#if selected}<p>{#if selected.billing_method==='split_settlement'}Approve deduction of accepted fees from verified customer collections for {selected.legal_name}. The seller receives the remaining amount; bank settlement is recorded separately. Unpaid fees are billed monthly, with earlier deductions credited.{:else}Approve {selected.billing_cycle} bills for {selected.legal_name}. Bills contain recorded fees and are due seven days after issue.{/if}</p><label>Payment instructions or settlement review evidence<textarea bind:value={instructions} oninput={()=>reviewed=false} required minlength="20" maxlength="2000" placeholder="Kredit’s verified bank name, account name, account number and payment guidance"></textarea></label><p>These instructions will be shown to the seller and saved on each bill. Verify the receiving account before approval.</p>{:else if receipt}<p>{receipt.direction==='received'?'Confirm an actual credit in Kredit’s bank statement. Do not use a seller’s screenshot as proof.':'Confirm that the refund reached the seller using the bank’s completed transfer record.'} Bill: {receipt.id}.</p><label>{receipt.direction==='received'?'Amount received':'Amount refunded'} (₦)<input bind:value={paid} oninput={()=>reviewed=false} inputmode="decimal" required /></label><label>Bank transaction reference<input bind:value={bankReference} oninput={()=>reviewed=false} required minlength="3" maxlength="200" /></label><label>{receipt.direction==='received'?'Received at':'Refund completed at'} (Lagos time)<input type="datetime-local" bind:value={receivedAt} oninput={()=>reviewed=false} required /></label><label>Bank evidence reviewed<textarea bind:value={evidence} oninput={()=>reviewed=false} required minlength="20" maxlength="2000"></textarea></label><p>This updates the fee bill and ledger from a completed bank movement. It does not send money.</p>{/if}<label class="confirm"><input type="checkbox" bind:checked={reviewed} required />I checked the evidence and the effect of this change.</label><button disabled={!reviewed}>{busy?'Saving…':'Save'}</button><button type="button" onclick={()=>{selected=null;receipt=null}}>Cancel</button></fieldset></form>{/if}</main>
<style>main{max-width:950px;padding-block:2rem}article,form{padding:1rem;margin-block:1rem;border:1px solid var(--color-border);border-radius:1rem}fieldset{display:grid;gap:1rem;border:0}label{display:grid;gap:.5rem}button,input,select,textarea{font:inherit;padding:.7rem}textarea{min-height:7rem}.confirm{display:flex;align-items:start}</style>
