<script lang="ts">
	import { onMount } from 'svelte'; import { page } from '$app/state';
	import Money from '$lib/components/Money.svelte';
	let intent:any=$state(null);let error=$state('');
	onMount(async()=>{const response=await fetch(`/api/v1/public/payment-intents/${page.params.token}`);const result=await response.json().catch(()=>({}));if(response.ok)intent=result.payment_intent;else error=result.detail??'This payment link is no longer working.'});
</script>
<svelte:head><title>Pay safely — Kredit</title></svelte:head>
<main class="shell prose-page"><p class="eyebrow">Safe payment</p>{#if intent}<h1>Check the amount before you pay.</h1><dl><div><dt>You are paying</dt><dd>{intent.supplier_name||'Seller'}</dd></div><div><dt>For</dt><dd>{intent.description}</dd></div><div><dt>Money left to pay</dt><dd><Money amountKobo={intent.amount_kobo} /></dd></div></dl><p>{intent.provider_action}</p><a class="primary" href="/buyer">Continue to pay</a><div class="support-card"><p><strong>Not sure about this payment?</strong> Talk to a real person before you pay.</p><a class="whatsapp-support" href="https://wa.me/2348000000000?text=Hello%20Kredit%20Support%2C%20I%20have%20a%20question%20about%20my%20payment" target="_blank" rel="noopener noreferrer">Chat on WhatsApp</a></div><p class="privacy">This page never shows your bank details or your private account information.</p>{:else if error}<h1>This payment link is not working.</h1><p role="alert">{error}</p>{:else}<p>Opening your payment…</p>{/if}</main>
<style>dl{display:grid;gap:.8rem;padding:1.25rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}dl div{display:flex;justify-content:space-between;gap:2rem}dt{color:var(--color-muted)}dd{font-weight:750;text-align:right}.privacy{font-size:.9rem;color:var(--color-muted)}.support-card{margin:1.5rem 0;padding:1rem;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:.75rem;display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap}.support-card p{margin:0;font-size:.9rem;color:#166534}.whatsapp-support{display:inline-flex;padding:.5rem 1rem;background:#15803d;color:#fff;font-weight:700;border-radius:.5rem;text-decoration:none;font-size:.85rem}</style>
