<script lang="ts">
	import { page } from '$app/state'; import { onMount } from 'svelte';import{csrfHeaders,idempotencyKey}from'$lib/api/client';
	let dispute=$state<any>(null), evidence:any[]=$state([]), decisions:any[]=$state([]), error=$state(''),notice=$state(''), loading=$state(true),busy=$state(false),outcome=$state('VALID_AMOUNT_CONFIRMED'),validNaira=$state(0),adjustmentNaira=$state(0),remainingNaira=$state(0),reason=$state('');
	const money=(value:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format((value??0)/100);
	async function load(){const response=await fetch(`/api/v1/ops/disputes/${page.params.id}`,{credentials:'include'});const data=await response.json().catch(()=>({}));loading=false;if(!response.ok){error=data.detail??'The dispute could not be loaded.';return}dispute=data.dispute;evidence=data.evidence??[];decisions=data.decisions??[];remainingNaira=dispute.remaining_disputed_kobo/100;validNaira=Math.max(0,(dispute.total_disputed_kobo-dispute.remaining_disputed_kobo)/100)}
	async function decide(e:SubmitEvent){e.preventDefault();busy=true;error='';const r=await fetch(`/api/v1/ops/disputes/${page.params.id}/decide`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({outcome,valid_principal_kobo:Math.round(validNaira*100),adjustment_kobo:Math.round(adjustmentNaira*100),remaining_disputed_kobo:Math.round(remainingNaira*100),reason})});const d=await r.json().catch(()=>({}));busy=false;if(!r.ok){error=d.detail??'The decision could not be recorded.';return}notice='Decision recorded. The sale balance and dispute history were updated.';reason='';await load()}
	onMount(load);
</script>
<svelte:head><title>Dispute review — Kredit</title></svelte:head>
<main class="shell workspace"><a href="/admin/disputes">← All disputes</a><p class="eyebrow">Admin / Dispute</p><h1>Dispute review</h1><p class="lede">Evidence and decisions are shown together before any money is changed.</p>{#if notice}<p class="notice">{notice}</p>{/if}{#if loading}<p>Loading dispute…</p>{:else if error}<p class="error" role="alert">{error}</p>{:else}<section class="summary"><div><span>Status</span><strong>{dispute.state.replaceAll('_',' ')}</strong></div><div><span>Disputed</span><strong>{money(dispute.total_disputed_kobo)}</strong></div><div><span>Still disputed</span><strong>{money(dispute.remaining_disputed_kobo)}</strong></div><div><span>Bank-debit effect</span><strong>{dispute.collection_effect.replaceAll('_',' ')}</strong></div></section><article><h2>{dispute.reason}</h2><p>{dispute.explanation}</p></article><div class="columns"><section><h2>Evidence</h2>{#if evidence.length}<ol>{#each evidence as item}<li><p>{item.statement||'Document evidence'}</p><span>{new Date(item.submitted_at).toLocaleString('en-NG')}</span></li>{/each}</ol>{:else}<p>No evidence has been recorded.</p>{/if}<h2>Earlier decisions</h2>{#each decisions as item}<div class="decision"><strong>{item.outcome.replaceAll('_',' ')}</strong><p>{item.reason}</p><small>{new Date(item.decided_at).toLocaleString('en-NG')}</small></div>{:else}<p>No decision has been recorded.</p>{/each}</section>{#if !['RESOLVED','WITHDRAWN'].includes(dispute.state)}<section class="action"><h2>Record a decision</h2><form onsubmit={decide}><label>Decision<select bind:value={outcome}><option value="VALID_AMOUNT_CONFIRMED">Confirm the valid amount</option><option value="PARTIAL_ADJUSTMENT">Make a partial adjustment</option><option value="FULL_ADJUSTMENT">Remove the disputed amount</option></select></label><label>Valid sale amount (₦)<input type="number" min="0" step="0.01" bind:value={validNaira}/></label><label>Amount to remove (₦)<input type="number" min="0" step="0.01" bind:value={adjustmentNaira}/></label><label>Amount still disputed (₦)<input type="number" min="0" step="0.01" bind:value={remainingNaira}/></label><label>Reason<textarea bind:value={reason} minlength="8" rows="4" required></textarea></label><button disabled={busy}>{busy?'Saving…':'Record this decision'}</button></form></section>{/if}</div>{/if}</main>
<style>h1{font-family:Georgia,serif;font-size:clamp(2.5rem,6vw,4.5rem);font-weight:500}.summary,.columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin:1.5rem 0}.summary{grid-template-columns:repeat(4,minmax(0,1fr))}.summary div,article,li,.decision{padding:1rem;border:1px solid var(--color-border);background:var(--color-surface)}.summary div{display:grid;gap:.3rem}.summary span,li span{color:var(--color-muted)}ol{display:grid;gap:.7rem;padding:0;list-style:none}.decision{margin:.7rem 0}.action{align-self:start;padding:1.2rem;background:#17181b;color:white}.action form,.action label{display:grid;gap:.7rem}.action label{gap:.3rem}.action input,.action select,.action textarea,.action button{padding:.7rem;border:1px solid #555;background:#242529;color:white;font:inherit}.action button{background:#ff6848;color:#17181b;font-weight:850}@media(max-width:760px){.summary,.columns{grid-template-columns:1fr}}</style>
