<script lang="ts">
	import { page } from '$app/state'; import { onMount } from 'svelte';
	let dispute=$state<any>(null), evidence:any[]=$state([]), decisions:any[]=$state([]), error=$state(''), loading=$state(true);
	const money=(value:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format((value??0)/100);
	onMount(async()=>{const response=await fetch(`/api/v1/ops/disputes/${page.params.id}`,{credentials:'include'});const data=await response.json().catch(()=>({}));loading=false;if(!response.ok){error=data.detail??'The dispute could not be loaded.';return}dispute=data.dispute;evidence=data.evidence??[];decisions=data.decisions??[]});
</script>
<svelte:head><title>Dispute review — Kredit</title></svelte:head>
<main class="shell workspace"><p class="eyebrow">Operations / Dispute</p><h1>Dispute review</h1><p class="lede">Evidence and decisions are shown together before any financial adjustment is approved.</p>{#if loading}<p>Loading dispute…</p>{:else if error}<p class="error" role="alert">{error}</p>{:else}<section class="summary"><div><span>Status</span><strong>{dispute.state}</strong></div><div><span>Disputed</span><strong>{money(dispute.total_disputed_kobo)}</strong></div><div><span>Still contested</span><strong>{money(dispute.remaining_disputed_kobo)}</strong></div><div><span>Collection effect</span><strong>{dispute.collection_effect.replaceAll('_',' ')}</strong></div></section><article><h2>{dispute.reason}</h2><p>{dispute.explanation}</p></article><div class="columns"><section><h2>Evidence</h2>{#if evidence.length}<ol>{#each evidence as item}<li><p>{item.statement||'Document evidence'}</p><span>{new Date(item.submitted_at).toLocaleString()}</span></li>{/each}</ol>{:else}<p>No evidence has been recorded.</p>{/if}</section><section><h2>Decisions</h2>{#if decisions.length}<ol>{#each decisions as item}<li><strong>{item.outcome}</strong><p>{item.reason}</p><span>{new Date(item.decided_at).toLocaleString()}</span></li>{/each}</ol>{:else}<p>No decision has been recorded.</p>{/if}</section></div>{/if}</main>
<style>.summary,.columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin:1.5rem 0}.summary{grid-template-columns:repeat(4,minmax(0,1fr))}.summary div,article,li{padding:1rem;border:1px solid var(--color-border);border-radius:.8rem;background:var(--color-surface)}.summary div{display:grid;gap:.3rem}.summary span,li span{color:var(--color-muted)}ol{display:grid;gap:.7rem;padding:0;list-style:none}@media(max-width:760px){.summary,.columns{grid-template-columns:1fr}}</style>
