<script lang="ts">
 import VerifyIdentity from '$lib/components/VerifyIdentity.svelte';
 import {onMount} from 'svelte';import {adminGet,adminPost,localTime} from '$lib/admin-client';import {formatKobo} from '$lib/money';
 let changes:any[]=$state([]),busy=$state(false),error=$state(''),message=$state(''),consents:Record<string,boolean>=$state({}),offset=$state(0),more=$state(false);
 async function load(){busy=true;error='';try{const b=await adminGet(`/api/v1/buyer/amendments?offset=${offset}`);changes=b.changes.slice(0,100);more=b.changes.length>100}catch(e){error=String(e)}finally{busy=false}}
 async function decide(c:any,action:string){busy=true;error='';try{await adminPost(`/api/v1/buyer/amendments/${c.id}/decision`,{action,reason:action==='accept'?'I accept the exact dates shown on this page.':'I do not accept the new dates.'});message=action==='accept'?'Done. Your new payment days now apply.':'You said no. Your old payment days still stand.';await load()}catch(e){error=String(e)}finally{busy=false}}
 onMount(load);
</script>
<svelte:head><title>Changes to your payment days — Kredit</title></svelte:head>
<main class="shell workspace"><h1>Changes to your payment days</h1><VerifyIdentity/><p>Read every new date before you decide. Until you accept, your old payment days still stand. The money you owe and the agreed fee do not change.</p>{#if error}<p role="alert">{error}</p>{/if}{#if message}<p role="status">{message}</p>{/if}{#each changes as c}<article><h2>{c.state.replaceAll('_',' ')}</h2><p>{c.reason}</p><p>Reference: {c.obligation_id} · Expires {localTime(c.expires_at)}</p><table><thead><tr><th>Money still unpaid</th><th>Old date</th><th>New date being asked for</th></tr></thead><tbody>{#each c.dates as d}{@const item=c.items.find((i:any)=>i.id===d.item_id)}<tr><td>{formatKobo(item.principal_due_kobo-item.allocated_kobo)}</td><td>{localTime(item.due_at)}</td><td>{localTime(d.due_at)}</td></tr>{/each}</tbody></table>{#if c.state==='awaiting_buyer'}<label><input type="checkbox" bind:checked={consents[c.id]}/> I have read these exact dates and I agree to them.</label><button disabled={busy||!consents[c.id]} onclick={()=>decide(c,'accept')}>Yes, I accept these dates</button><button disabled={busy} onclick={()=>decide(c,'reject')}>No, keep my old dates</button>{/if}</article>{:else}<p>{busy?'Loading date changes…':'No repayment date changes to review.'}</p>{/each}<button disabled={busy||!offset} onclick={()=>{offset=Math.max(0,offset-100);load()}}>Previous</button><button disabled={busy||!more} onclick={()=>{offset+=100;load()}}>Next</button></main>
<style>article{padding:1.2rem;border:1px solid #ccc;margin:1rem 0;overflow:auto}td,th{padding:.6rem;text-align:left;border-bottom:1px solid #ccc}label{display:block;padding:1rem 0}button{padding:.7rem;margin:.5rem .5rem .5rem 0}p{overflow-wrap:anywhere}</style>
