<script lang="ts">
 import {onMount} from 'svelte';
 import {adminPost} from '$lib/admin-client';
 import {loadOnboardingSettings,settingsProfile} from '$lib/api/onboarding-settings';
 import {dev} from '$app/environment';import {productLabel} from '$lib/product-language';
 let orgID='',profile:Record<string,unknown>={},permissions:Record<string,unknown>={},message='',loadError='',busy=false,loading=true;
 let provider='',reference='',bank='',name='',last4='';
 async function load(){loading=true;loadError='';try{const result=await loadOnboardingSettings();orgID=result.orgID;profile=result.profile;permissions=result.permissions;provider=String(profile.settlement_provider??'');bank=String(profile.settlement_bank_name??'');name=String(profile.settlement_account_name??'');last4=String(profile.settlement_account_last4??'');}catch(cause){loadError=cause instanceof Error?cause.message:'We could not load these settings.';}finally{loading=false;}}
 async function save(){if(busy||loading||loadError||!orgID)return;busy=true;message='';try{const result=await adminPost(`/api/v1/organizations/${encodeURIComponent(orgID)}/onboarding/settlement`,{expected_version:profile.version,provider,provider_reference:reference,bank_name:bank,account_name:name,account_last4:last4},'PUT');profile=settingsProfile(result.profile);message='Saved. We are checking this account now.';}catch(cause){message=cause instanceof Error?cause.message:'We could not confirm this change.';}finally{busy=false;}}
 onMount(load);
</script>
<svelte:head><title>Bank account — Kredit</title></svelte:head><main class="shell workspace form-page"><p class="eyebrow">Settings / Bank account</p><h1>Where should we send your money?</h1><p class="lede">Add the business bank account that should receive your customers’ payments. Once you save it, we only ever show the last four digits.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}{#if loading}<p role="status">Loading your settings…</p>{:else if loadError}<p class="error" role="alert">{loadError}</p><button onclick={load}>Try again</button>{:else}<section class="card"><header><h2>Your bank account</h2><span>{productLabel(profile.settlement_state,'Not started')}</span></header>{#if profile.settlement_account_last4}<p class="masked">{profile.settlement_bank_name} · {profile.settlement_account_name} · •••• {profile.settlement_account_last4}</p>{/if}{#if permissions.settlement}<label>Payment company<select disabled={busy} bind:value={provider}><option value="">Choose one</option><option value="paystack">Paystack</option><option value="flutterwave">Flutterwave</option>{#if dev}<option value="mock-settlement">Testing only</option>{/if}</select></label><label>The setup number your payment company gave you<input disabled={busy} bind:value={reference} autocomplete="off" /></label><label>Bank name<input disabled={busy} bind:value={bank} /></label><label>Name on the account<input disabled={busy} bind:value={name} /></label><label>Last four digits of the account number<input disabled={busy} bind:value={last4} maxlength="4" inputmode="numeric" /></label><button disabled={busy||!provider||!reference||!/^\d{4}$/.test(last4)} onclick={save}>{busy?'Saving…':'Save this bank account'}</button>{:else}<p>You can look at this, but only the owner or somebody allowed to handle money can change it.</p>{/if}</section>{/if}<a href="/app/settings">← All settings</a></main>
<style>.form-page{max-width:52rem}.form-page h1{font-size:clamp(2.4rem,6vw,4.5rem);line-height:1}.card{display:grid;gap:.8rem;padding:1.4rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}header{display:flex;justify-content:space-between;gap:1rem}header span{text-transform:capitalize}.card label{display:grid;gap:.3rem;font-weight:700}.card input,.card select,.card button{padding:.75rem;border:1px solid var(--color-border);border-radius:.65rem;font:inherit}.card button{background:var(--color-primary);color:white;font-weight:800}.masked{font-size:1.15rem}.notice{padding:1rem;background:#eef5ff;border-radius:.7rem}</style>
