<script lang="ts">
	import { onMount } from 'svelte';
	import Money from '$lib/components/Money.svelte';
	import { productLabel } from '$lib/product-language';
	let claims:any[]=$state([]),loading=$state(true),error=$state('');
	onMount(async()=>{const response=await fetch('/api/v1/buyer/payment-claims',{credentials:'include'});const data=await response.json().catch(()=>({}));loading=false;if(!response.ok){error=data.detail??'We could not open the transfers you reported.';return}claims=(data.payment_claims??[]).sort((a:any,b:any)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime())});
</script>
<svelte:head><title>Transfers I reported — Kredit</title></svelte:head>
<main class="shell workspace reported"><p class="eyebrow">Transfers I reported</p><h1>See what happened after you told a seller you paid.</h1><p class="lede">A seller must check their bank account before your transfer can reduce the money you owe.</p>{#if loading}<p role="status">Opening your transfers…</p>{:else if error}<p class="error" role="alert">{error}</p>{:else if claims.length}<section>{#each claims as claim}<article><div><strong><Money amountKobo={claim.amount_kobo}/></strong><span>{productLabel(claim.state)}</span></div><dl><div><dt>Transfer number</dt><dd>{claim.transfer_reference}</dd></div><div><dt>Payment day</dt><dd>{new Date(claim.paid_at).toLocaleDateString('en-NG')}</dd></div>{#if claim.review_reason}<div><dt>Seller’s answer</dt><dd>{claim.review_reason}</dd></div>{/if}</dl>{#if claim.state==='pending'}<p>The seller has not answered yet. Your collection is paused for this amount until {new Date(claim.hold_expires_at).toLocaleString('en-NG')}.</p>{/if}</article>{/each}</section>{:else}<section class="empty-state"><h2>No reported transfers</h2><p>When you tell a seller about a bank transfer, you can follow the answer here.</p><a href="/buyer/obligations">Open money I owe →</a></section>{/if}</main>
<style>.reported{max-width:58rem}.reported>section{display:grid;gap:.8rem;margin-top:2rem}.reported article{padding:1.2rem;border:1px solid var(--color-border);background:var(--color-surface)}article>div{display:flex;justify-content:space-between;gap:1rem}article>div>strong{font-size:1.5rem}dl{display:grid;gap:.5rem}dl div{display:flex;justify-content:space-between;gap:1rem}dd{margin:0;text-align:right;font-weight:700}.error{color:var(--color-destructive)}</style>
