<script lang="ts">
	const safeguards = [
		['Safe sign-in', 'We send a private sign-in link. We ask you to check again before important actions.'],
		['Correct money', 'Balances are recorded in kobo. Payment references help prevent duplicate entries, and collection checks account for money already paid or reserved.'],
		['Private details', 'Account permissions restrict access to records. Document downloads use private, expiring links.'],
		['Copies of your records', 'Backup and restore procedures are tested before launch. Production recovery must be rehearsed and monitored.'],
		['Fair payments', 'You review the terms before accepting. Recorded disputes and reported payments affect the amount eligible for collection.'],
		['We test first', 'Checks cover sign-in, payment calculations, account permissions and recovery. Independent review remains part of launch preparation.']
	];
</script>


<main class="trust-page">
	<section class="trust-hero shell"><div><p class="eyebrow">Is it safe?</p><h1>How Kredit protects your records.</h1></div><div class="hero-side"><p>We control who can enter your account. We keep payment records. We stop if something looks wrong.</p><dl><div><dt>Your staff</dt><dd>See only what they need</dd></div><div><dt>Your sale</dt><dd>Changes need an audit trail</dd></div><div><dt>A problem</dt><dd>We stop and check</dd></div></dl></div></section>

	<section class="safeguards shell"><div class="section-head"><p class="eyebrow">How we keep it safe</p><h2>We check every important step.</h2></div><div class="safeguard-list">{#each safeguards as [title, body], index}<article><span>0{index + 1}</span><h3>{title}</h3><p>{body}</p></article>{/each}</div></section>

	<section class="boundaries-section"><div class="shell boundaries"><article><span>01 / SHARED LINKS</span><h2>We hide private details.</h2><p>Public receipt links omit full names, bank details and private notes. Private invitation and document links serve a different purpose; share them only with the intended recipient.</p></article><article><span>02 / SLOW PAYMENT</span><h2>We check before we debit again.</h2><p>If a payment is slow, we do not take the money again. We first ask the bank what happened.</p></article></div></section>

	<section class="reporting shell"><div><p class="eyebrow">Tell us about a problem</p><h2>Found a safety or privacy issue?</h2></div><div><p>Tell us what happened, but never send your password, one-time code, recovery code or full bank details.</p><a href="/legal/complaints">Report a problem <span>↗</span></a></div></section>

	<aside class="release shell"><strong>Before we go live</strong><p>Independent tests, payment-company approval, recovery practice and legal checks must be complete. The safety features above do not replace those reviews.</p></aside>
</main>

<style>
	.trust-page { color: #17181b; background: #f5f2ea; }.trust-hero { display: grid; grid-template-columns: 1.35fr .65fr; gap: clamp(4rem, 10vw, 10rem); align-items: end; padding-top: clamp(5rem, 10vw, 9rem); padding-bottom: clamp(6rem, 10vw, 9rem); }.trust-hero h1 { max-width: 11ch; margin: 1.1rem 0 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(4rem, 8vw, 7.5rem); font-weight: 500; line-height: .88; letter-spacing: -.065em; }.hero-side { padding-top: 1.2rem; border-top: 1px solid #17181b; }.hero-side > p { margin: 0 0 2rem; color: #5f615e; font-size: 1.05rem; line-height: 1.7; }.hero-side dl { margin: 0; }.hero-side dl div { display: flex; justify-content: space-between; gap: 2rem; padding: .75rem 0; border-top: 1px solid #cec9bf; }.hero-side dt { color: #62645f; font-size: .72rem; }.hero-side dd { margin: 0; font-size: .76rem; font-weight: 760; }
	.safeguards { padding-top: 8rem; padding-bottom: 9rem; border-top: 1px solid #cec9bf; }.section-head { display: grid; grid-template-columns: .55fr 1.45fr; gap: 3rem; }.section-head h2 { max-width: 12ch; margin: 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(3.2rem, 6vw, 6rem); font-weight: 500; line-height: .92; letter-spacing: -.055em; }.safeguard-list { display: grid; grid-template-columns: repeat(3, 1fr); margin-top: 5rem; border-top: 1px solid #cec9bf; border-left: 1px solid #cec9bf; }.safeguard-list article { min-height: 15rem; padding: 1.6rem; border-right: 1px solid #cec9bf; border-bottom: 1px solid #cec9bf; }.safeguard-list span { color: #2738d6; font-size: .68rem; font-weight: 800; }.safeguard-list h3 { margin: 3.5rem 0 .7rem; font-family: Georgia, 'Times New Roman', serif; font-size: 1.35rem; font-weight: 500; }.safeguard-list p { margin: 0; color: #686a66; line-height: 1.65; }
	.boundaries-section { padding: 8rem 0; color: #f5f2ea; background: #17181b; }.boundaries { display: grid; grid-template-columns: 1fr 1fr; gap: 0; border-top: 1px solid #55565a; border-left: 1px solid #55565a; }.boundaries article { min-height: 23rem; padding: clamp(2rem, 5vw, 4rem); border-right: 1px solid #55565a; border-bottom: 1px solid #55565a; }.boundaries span { color: #aeb4ff; font-size: .68rem; font-weight: 800; letter-spacing: .1em; }.boundaries h2 { max-width: 13ch; margin: 5rem 0 1.2rem; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(2.4rem, 4vw, 4rem); font-weight: 500; line-height: .98; letter-spacing: -.045em; }.boundaries p { max-width: 31rem; margin: 0; color: #aaa9a4; line-height: 1.7; }
	.reporting { display: grid; grid-template-columns: 1fr 1fr; gap: clamp(4rem, 10vw, 10rem); padding-top: 9rem; padding-bottom: 8rem; }.reporting h2 { max-width: 13ch; margin: 1rem 0 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(3rem, 5vw, 5rem); font-weight: 500; line-height: .95; letter-spacing: -.05em; }.reporting > div:last-child { padding-top: 1.2rem; border-top: 1px solid #17181b; }.reporting p { margin: 0 0 2rem; color: #686a66; line-height: 1.7; }.reporting a { display: inline-flex; gap: 3rem; padding: 1rem 1.2rem; color: white; background: #2738d6; font-weight: 760; text-decoration: none; }.reporting a span { color: #ffb8a7; }.release { display: grid; grid-template-columns: .4fr 1.6fr; gap: 3rem; margin-bottom: 8rem; padding-top: 1.3rem; border-top: 3px solid #ff5b3a; }.release p { max-width: 47rem; margin: 0; color: #686a66; line-height: 1.7; }
	@media (max-width: 800px) { .trust-hero, .section-head, .reporting { grid-template-columns: 1fr; gap: 2.5rem; }.hero-side { max-width: 32rem; }.safeguard-list { grid-template-columns: 1fr 1fr; } }
	@media (max-width: 560px) { .trust-hero { padding-top: 4rem; }.safeguards, .boundaries-section, .reporting { padding-top: 6rem; padding-bottom: 6rem; }.safeguard-list, .boundaries, .release { grid-template-columns: 1fr; }.safeguard-list article { min-height: auto; }.safeguard-list h3 { margin-top: 2rem; }.boundaries article { min-height: auto; }.boundaries h2 { margin-top: 3rem; }.release { gap: 1rem; margin-bottom: 6rem; } }
</style>
