<script lang="ts">
	const safeguards = [
		['Nobody signs in as you', 'We send a private code to your phone or email. And before anything touches money, we ask you to prove it is really you.'],
		['Every kobo is counted', 'We count in kobo, not rough figures. Transfer references stop the same payment being counted twice. And we always check what has already been paid before we ask for more.'],
		['Only the right eyes see it', 'Your staff see only what their job needs. Documents open through private links that stop working after a short while.'],
		['Your records are backed up', 'We keep copies, and we practise bringing them back. That gets tested before launch, and watched afterwards.'],
		['Nobody gets debited quietly', 'You read the terms before you accept. And if somebody reports a payment or raises a problem, that money cannot be touched while it is being sorted out.'],
		['Do not just take our word', 'We test sign-in, money calculations, staff permissions and account recovery. And outside reviewers check us before we launch.']
	];
</script>


<main class="trust-page">
	<section class="trust-hero shell"><div><p class="eyebrow">Is my money safe here?</p><h1>How Kredit protects you.</h1></div><div class="hero-side"><p>We control who gets into your account. We keep every payment record. And when something looks wrong, we stop and check before any money moves.</p><dl><div><dt>Your staff</dt><dd>See only what they need</dd></div><div><dt>Your sale</dt><dd>Every change is recorded</dd></div><div><dt>A problem</dt><dd>We pause and check</dd></div></dl></div></section>

	<section class="safeguards shell"><div class="section-head"><p class="eyebrow">How we keep it safe</p><h2>We check every money step.</h2></div><div class="safeguard-list">{#each safeguards as [title, body], index}<article><span>0{index + 1}</span><h3>{title}</h3><p>{body}</p></article>{/each}</div></section>

	<section class="boundaries-section"><div class="shell boundaries"><article><span>01 / LINKS YOU SHARE</span><h2>Shared receipts hide your details.</h2><p>A receipt you forward carries no full names, no bank details and no private notes. But a private invitation or document link is a different thing. Send those to one person only, the person they were meant for.</p></article><article><span>02 / WHEN A DEBIT IS SLOW</span><h2>We never debit twice.</h2><p>If a bank debit is slow, we do not just try again and hope. We go back and ask the bank what happened to the first one.</p></article></div></section>

	<section class="reporting shell"><div><p class="eyebrow">Tell us about a problem</p><h2>Have you seen something wrong?</h2></div><div><p>Tell us what happened. But never send your password, your one-time code, your recovery code or your bank details. Not to us, and not to anybody who says they are us.</p><a href="/legal/complaints">Report a problem <span>↗</span></a></div></section>

	<aside class="release shell"><strong>Before we go live</strong><p>Outside testing, payment-company approval, recovery practice and legal checks must all be finished first. The safety features above do not replace those checks.</p></aside>
</main>

<style>
	.trust-page { color: #17181b; background: #f5f2ea; }.trust-hero { display: grid; grid-template-columns: 1.35fr .65fr; gap: clamp(4rem, 10vw, 10rem); align-items: end; padding-top: clamp(5rem, 10vw, 9rem); padding-bottom: clamp(6rem, 10vw, 9rem); }.trust-hero h1 { max-width: 11ch; margin: 1.1rem 0 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(4rem, 8vw, 7.5rem); font-weight: 500; line-height: .88; letter-spacing: -.065em; }.hero-side { padding-top: 1.2rem; border-top: 1px solid #17181b; }.hero-side > p { margin: 0 0 2rem; color: #5f615e; font-size: 1.05rem; line-height: 1.7; }.hero-side dl { margin: 0; }.hero-side dl div { display: flex; justify-content: space-between; gap: 2rem; padding: .75rem 0; border-top: 1px solid #cec9bf; }.hero-side dt { color: #62645f; font-size: .72rem; }.hero-side dd { margin: 0; font-size: .76rem; font-weight: 760; }
	.safeguards { padding-top: 8rem; padding-bottom: 9rem; border-top: 1px solid #cec9bf; }.section-head { display: grid; grid-template-columns: .55fr 1.45fr; gap: 3rem; }.section-head h2 { max-width: 12ch; margin: 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(3.2rem, 6vw, 6rem); font-weight: 500; line-height: .92; letter-spacing: -.055em; }.safeguard-list { display: grid; grid-template-columns: repeat(3, 1fr); margin-top: 5rem; border-top: 1px solid #cec9bf; border-left: 1px solid #cec9bf; }.safeguard-list article { min-height: 15rem; padding: 1.6rem; border-right: 1px solid #cec9bf; border-bottom: 1px solid #cec9bf; }.safeguard-list span { color: #2738d6; font-size: .68rem; font-weight: 800; }.safeguard-list h3 { margin: 3.5rem 0 .7rem; font-family: Georgia, 'Times New Roman', serif; font-size: 1.35rem; font-weight: 500; }.safeguard-list p { margin: 0; color: #686a66; line-height: 1.65; }
	.boundaries-section { padding: 8rem 0; color: #f5f2ea; background: #17181b; }.boundaries { display: grid; grid-template-columns: 1fr 1fr; gap: 0; border-top: 1px solid #55565a; border-left: 1px solid #55565a; }.boundaries article { min-height: 23rem; padding: clamp(2rem, 5vw, 4rem); border-right: 1px solid #55565a; border-bottom: 1px solid #55565a; }.boundaries span { color: #aeb4ff; font-size: .68rem; font-weight: 800; letter-spacing: .1em; }.boundaries h2 { max-width: 13ch; margin: 5rem 0 1.2rem; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(2.4rem, 4vw, 4rem); font-weight: 500; line-height: .98; letter-spacing: -.045em; }.boundaries p { max-width: 31rem; margin: 0; color: #aaa9a4; line-height: 1.7; }
	.reporting { display: grid; grid-template-columns: 1fr 1fr; gap: clamp(4rem, 10vw, 10rem); padding-top: 9rem; padding-bottom: 8rem; }.reporting h2 { max-width: 13ch; margin: 1rem 0 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(3rem, 5vw, 5rem); font-weight: 500; line-height: .95; letter-spacing: -.05em; }.reporting > div:last-child { padding-top: 1.2rem; border-top: 1px solid #17181b; }.reporting p { margin: 0 0 2rem; color: #686a66; line-height: 1.7; }.reporting a { display: inline-flex; gap: 3rem; padding: 1rem 1.2rem; color: white; background: #2738d6; font-weight: 760; text-decoration: none; }.reporting a span { color: #ffb8a7; }.release { display: grid; grid-template-columns: .4fr 1.6fr; gap: 3rem; margin-bottom: 8rem; padding-top: 1.3rem; border-top: 3px solid #ff5b3a; }.release p { max-width: 47rem; margin: 0; color: #686a66; line-height: 1.7; }
	@media (max-width: 800px) { .trust-hero, .section-head, .reporting { grid-template-columns: 1fr; gap: 2.5rem; }.hero-side { max-width: 32rem; }.safeguard-list { grid-template-columns: 1fr 1fr; } }
	@media (max-width: 560px) { .trust-hero { padding-top: 4rem; }.safeguards, .boundaries-section, .reporting { padding-top: 6rem; padding-bottom: 6rem; }.safeguard-list, .boundaries, .release { grid-template-columns: 1fr; }.safeguard-list article { min-height: auto; }.safeguard-list h3 { margin-top: 2rem; }.boundaries article { min-height: auto; }.boundaries h2 { margin-top: 3rem; }.release { gap: 1rem; margin-bottom: 6rem; } }
</style>
