<script lang="ts">
 import { parseNaira } from '$lib/money';
	import { onMount } from 'svelte';
	import { csrfHeaders,idempotencyKey } from '$lib/api/client';
	import { productLabel } from '$lib/product-language';
	let organizations:any[]=$state([]),organizationID=$state(''),lines:any[]=$state([]),customers:any[]=$state([]),loading=$state(true),busy=$state(false),error=$state(''),notice=$state('');
	let buyerUserID=$state(''),buyerBusinessID=$state(''),mandateID=$state(''),limit=$state(''),cadence=$state('monthly'),grace=$state(48),startAt=$state(''),endAt=$state(''),termsVersion=$state('trade-line-v1');
	const money=(value:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format((value??0)/100);
	async function load(){loading=true;error='';try{if(!organizationID){const response=await fetch('/api/v1/organizations',{credentials:'include'});if(!response.ok)throw new Error('We could not open your businesses.');organizations=(await response.json()).organizations??[];organizationID=organizations[0]?.id??''}if(!organizationID){lines=[];return}const [lineResponse,customerResponse]=await Promise.all([fetch(`/api/v1/organizations/${organizationID}/trade-lines`,{credentials:'include'}),fetch(`/api/v1/organizations/${organizationID}/customers`,{credentials:'include'})]);const lineData=await lineResponse.json().catch(()=>({}));if(!lineResponse.ok)throw new Error(lineData.detail??'We could not open your customer limits.');lines=lineData.trade_lines??[];customers=customerResponse.ok?(await customerResponse.json()).customers??[]:[]}catch(cause){error=cause instanceof Error?cause.message:'We could not open your customer limits.'}finally{loading=false}}
	function selectCustomer(){const customer=customers.find((item)=>item.buyer_user_id===buyerUserID);buyerBusinessID=customer?.buyer_business_id??''}
	async function create(event:SubmitEvent){event.preventDefault();const approvedLimitKobo=parseNaira(limit);if(approvedLimitKobo<=0){error='Enter the most this customer can owe.';return}busy=true;error='';notice='';const response=await fetch(`/api/v1/organizations/${organizationID}/trade-lines`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({buyer_user_id:buyerUserID,buyer_business_id:buyerBusinessID,mandate_id:mandateID,approved_limit_kobo:approvedLimitKobo,cadence,default_grace_hours:Number(grace),start_at:new Date(startAt).toISOString(),end_at:new Date(endAt).toISOString(),terms_version:termsVersion})});const data=await response.json().catch(()=>({}));busy=false;if(!response.ok){error=data.detail??'We could not save this limit. Check the bank debit setup and try again.';return}notice=`Your customer can now owe up to ${money(approvedLimitKobo)}.`;buyerUserID='';buyerBusinessID='';mandateID='';limit='';await load()}
	onMount(load);
</script>
<svelte:head><title>Customer limits — Kredit</title></svelte:head>
<main class="shell workspace"><header><p class="eyebrow">Customer limits</p><h1>Let a good customer buy again.</h1><p class="lede">Choose the most they can owe you. Every new sale uses part of that amount.</p></header>
	{#if organizations.length>1}<label class="org">Business<select bind:value={organizationID} onchange={load}>{#each organizations as org}<option value={org.id}>{org.trading_name||org.legal_name}</option>{/each}</select></label>{/if}
	{#if error}<p class="error" role="alert">{error} <button onclick={load}>Refresh</button></p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
	<section class="card"><h2>Give a customer a limit</h2><p>The customer must allow bank debit before you can do this.</p><form onsubmit={create}><label>Customer<select bind:value={buyerUserID} onchange={selectCustomer} required><option value="">Choose a customer</option>{#each customers as customer}<option value={customer.buyer_user_id}>{customer.legal_name||customer.trading_name}</option>{/each}</select></label><label>Customer number<input bind:value={buyerBusinessID} required /></label><label>Bank debit setup number<input bind:value={mandateID} required /></label><label>Most they can owe (₦)<input bind:value={limit} inputmode="decimal" required /></label><label>How often they buy<select bind:value={cadence}><option value="weekly">Every week</option><option value="monthly">Every month</option><option value="quarterly">Every three months</option></select></label><label>Extra hours to pay<input bind:value={grace} type="number" min="0" max="720" required /></label><label>Start day<input bind:value={startAt} type="datetime-local" required /></label><label>End day<input bind:value={endAt} type="datetime-local" required /></label><details class="wide"><summary>Setup details</summary><label>Rules number<input bind:value={termsVersion} required /></label></details><button class="primary wide" disabled={busy||!buyerUserID||!mandateID||!limit||!startAt||!endAt}>{busy?'Saving…':`Give a ${money(parseNaira(limit))} limit`}</button></form></section>
	<section><h2>Customer limits</h2>{#if loading}<p role="status">Opening limits…</p>{:else if lines.length}<div class="lines">{#each lines as line}<article><header><strong>{money(line.available_limit_kobo)} left to use</strong><span class="status">{productLabel(line.state)}</span></header><dl><dt>Full limit</dt><dd>{money(line.approved_limit_kobo)}</dd><dt>Money owed</dt><dd>{money(line.current_exposure_kobo)}</dd><dt>Waiting</dt><dd>{money(line.reserved_pending_kobo)}</dd></dl><a href={`/app/trade-lines/${line.id}`}>Open this limit →</a></article>{/each}</div>{:else}<div class="empty-state"><h3>No customer limit</h3><p>Add one after your customer allows bank debit.</p></div>{/if}</section>
</main>
<style>h1{font-size:clamp(2.5rem,6vw,4.7rem);line-height:1}.org{display:grid;gap:.3rem;max-width:28rem}.card{margin:1.5rem 0;padding:1.25rem}.card form{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}.card label{display:grid;gap:.3rem;font-weight:700}input,select,button{box-sizing:border-box;width:100%;padding:.7rem;border:1px solid var(--color-border);border-radius:.6rem;background:var(--color-surface);color:inherit;font:inherit}.wide{grid-column:1/-1}.notice{padding:1rem;border-left:4px solid var(--color-positive);background:var(--color-surface-muted)}.lines{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.lines article{padding:1.2rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}.lines header{display:flex;justify-content:space-between;gap:1rem}.lines dl{display:grid;grid-template-columns:1fr 1fr;gap:.4rem}.lines dd{text-align:right;margin:0}.lines a{color:var(--color-primary);font-weight:700}@media(max-width:760px){.card form,.lines{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
