<script lang="ts">
 import {onMount} from 'svelte';
 let rates:{base_bps:number;collection_bps:number}|null=$state(null),pricingError=$state('');
 onMount(async()=>{try{const r=await fetch('/api/v1/pricing');if(!r.ok)throw new Error();const b=await r.json();if(!Number.isInteger(b.base_bps)||!Number.isInteger(b.collection_bps)||b.base_bps<0||b.base_bps>1000||b.collection_bps<0||b.collection_bps>1000)throw new Error();rates=b}catch{pricingError='We could not load today\u2019s rates. Refresh this page before you trust any figure below.'}});
 import { parseNaira } from '$lib/money';
	import Money from '$lib/components/Money.svelte';
	let principalNaira = $state(500000);
	const kobo = $derived(Math.max(0, parseNaira(principalNaira)));
	const voluntaryFee = $derived.by(()=>rates?Math.floor(kobo * rates.base_bps / 10000):null);
	const collectionFee = $derived.by(()=>rates&&voluntaryFee!==null?voluntaryFee + Math.floor(kobo * rates.collection_bps / 10000):null);
	const questions = [
		['What if my customer pays late?', 'Kredit sends reminders first. After the extra days you agreed, Kredit can ask their bank for the money, but only if that customer gave permission and there is no open problem. A bank debit can still fail, so nobody can promise you the money.'],
		['Does Kredit lend money?', 'No. You give the goods, and you choose who gets them. We only write it down and help you follow the money.'],
		['Must my customer install an app?', 'No. They just open a private link on their phone. Reminders and receipts reach them on WhatsApp.'],
		['Is there a monthly fee?', 'No. Nothing monthly, and nothing to join. Adding customers and writing sales down is free.']
	];
	function describe(value: number) { return new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(value); }
</script>

<main class="pricing-page">
	<section class="pricing-hero shell"><div><p class="eyebrow">What it costs</p><h1>Nothing to pay <em>until a sale starts.</em></h1></div><div class="hero-side"><p>Writing a sale down costs you nothing. Following what you are owed costs you nothing. You only pay a small base fee once your customer accepts a sale and it starts. And if we later collect money from their bank for you, there is a small fee on what we actually collect. If our rates change tomorrow, your old sales keep the rates you agreed on.</p><span>No monthly fee · No joining fee · Free to start</span></div></section>

 {#if pricingError}<p role="alert" class="shell">{pricingError}</p>{:else if !rates}<p class="shell">Loading today’s rates…</p>{/if}
 {#if rates}<section class="rates shell" aria-label="Kredit fee rates"><article><span>01 / BASE FEE WHEN THE SALE STARTS</span><strong>{rates.base_bps/100}%</strong><p>You pay this once, after your customer accepts the sale and it starts running.</p></article><article><span>02 / EXTRA FEE IF KREDIT COLLECTS</span><strong>{rates.collection_bps/100}%</strong><p>Only on money we actually pull from your customer's bank. If the debit fails, you pay us nothing extra.</p></article></section>{/if}

	<section class="calculator-section"><div class="shell calculator-layout"><div><p class="eyebrow inverse">Work out your fee</p><h2>Know the fee before you sell.</h2><p>Slide it to the value of your goods. You will see the base fee, and the most you would ever pay if we end up collecting the whole balance for you.</p></div><div class="calculator"><div class="value"><span>Value of goods</span><strong>{describe(principalNaira)}</strong></div><input type="range" min="50000" max="10000000" step="50000" bind:value={principalNaira} aria-label="Value of goods in naira" /><div class="range-labels"><span>₦50k</span><span>₦10m</span></div><dl><div><dt>Base fee when the sale starts <span>{rates?`${rates.base_bps/100}%`:"—"}</span></dt><dd><Money amountKobo={voluntaryFee} /></dd></div><div><dt>Most you would pay, if Kredit collects everything <span>{rates?`${(rates.base_bps+rates.collection_bps)/100}%`:"—"}</span></dt><dd><Money amountKobo={collectionFee} /></dd></div><div><dt>Writing the sale down and following it</dt><dd>₦0</dd></div></dl></div></div></section>

	<section class="questions shell"><div class="section-head"><p class="eyebrow">Good to know</p><h2>Straight answers.</h2></div><div class="question-list">{#each questions as [question, answer], index}<article><span>0{index + 1}</span><h3>{question}</h3><p>{answer}</p></article>{/each}</div></section>

	<section class="pricing-cta shell"><p>Ready to write down your first sale?</p><a href="/app">Start free <span>↗</span></a></section>
</main>

<style>
	.pricing-page { color: #17181b; background: #f5f2ea; }.pricing-hero { display: grid; grid-template-columns: 1.35fr .65fr; gap: clamp(4rem, 10vw, 10rem); align-items: end; padding-top: clamp(5rem, 10vw, 9rem); padding-bottom: 7rem; }.pricing-hero h1 { margin: 1rem 0 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(4rem, 8vw, 7.5rem); font-weight: 500; line-height: .88; letter-spacing: -.065em; } .pricing-hero h1 em { color: #2738d6; font-weight: 500; }.hero-side { padding-top: 1.2rem; border-top: 1px solid #17181b; }.hero-side p { margin: 0 0 2rem; color: #5f615e; font-size: 1.08rem; line-height: 1.7; }.hero-side span { color: #2738d6; font-size: .72rem; font-weight: 760; }
	.rates { display: grid; grid-template-columns: 1fr 1fr; padding-bottom: 9rem; }.rates article { min-height: 23rem; padding: 2rem; border: 1px solid #cec9bf; }.rates article + article { border-left: 0; }.rates span { color: #2738d6; font-size: .68rem; font-weight: 800; letter-spacing: .1em; }.rates strong { display: block; margin: 3.5rem 0 1.5rem; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(5rem, 10vw, 9rem); font-weight: 500; line-height: .8; letter-spacing: -.07em; }.rates p { max-width: 30rem; margin: 0; color: #686a66; line-height: 1.7; }
	.calculator-section { padding: 8rem 0; color: #f5f2ea; background: #2738d6; }.calculator-layout { display: grid; grid-template-columns: .7fr 1.3fr; gap: clamp(4rem, 10vw, 10rem); }.inverse { color: #c9cdff; }.calculator-layout h2 { max-width: 10ch; margin: 1.2rem 0 1.5rem; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(3.2rem, 6vw, 5.8rem); font-weight: 500; line-height: .93; letter-spacing: -.05em; }.calculator-layout > div:first-child > p:last-child { max-width: 28rem; color: #d0d3ff; line-height: 1.7; }.calculator { padding: clamp(1.5rem, 4vw, 3rem); color: #17181b; background: #f5f2ea; }.value { display: flex; justify-content: space-between; gap: 2rem; align-items: baseline; }.value span { font-size: .75rem; font-weight: 760; }.value strong { font-family: Georgia, 'Times New Roman', serif; font-size: clamp(2.5rem, 5vw, 4.5rem); font-weight: 500; letter-spacing: -.045em; }.calculator input { width: 100%; height: 2px; margin: 3rem 0 0; accent-color: #b83d26; }.range-labels { display: flex; justify-content: space-between; color: #62645f; font-size: .65rem; }.calculator dl { margin: 3rem 0 0; border-top: 1px solid #cec9bf; }.calculator dl div { display: flex; justify-content: space-between; gap: 2rem; padding: 1.1rem 0; border-bottom: 1px solid #cec9bf; }.calculator dt { font-size: .78rem; }.calculator dt span { margin-left: .4rem; color: #2738d6; font-weight: 760; }.calculator dd { margin: 0; font-size: 1rem; font-weight: 800; }
	.questions { padding-top: 9rem; padding-bottom: 9rem; }.section-head { display: grid; grid-template-columns: .55fr 1.45fr; gap: 3rem; }.section-head h2 { max-width: 12ch; margin: 0; font-family: Georgia, 'Times New Roman', serif; font-size: clamp(3.2rem, 6vw, 6rem); font-weight: 500; line-height: .92; letter-spacing: -.055em; }.question-list { margin-top: 5rem; border-top: 1px solid #cec9bf; }.question-list article { display: grid; grid-template-columns: 3rem .8fr 1.2fr; gap: clamp(1rem, 5vw, 5rem); padding: 2rem 0; border-bottom: 1px solid #cec9bf; }.question-list article > span { color: #2738d6; font-size: .68rem; font-weight: 800; }.question-list h3 { margin: 0; font-family: Georgia, 'Times New Roman', serif; font-size: 1.4rem; font-weight: 500; }.question-list p { max-width: 39rem; margin: 0; color: #686a66; line-height: 1.7; }.pricing-cta { display: flex; justify-content: space-between; gap: 2rem; align-items: center; padding-top: 1.5rem; padding-bottom: 7rem; border-top: 3px solid #17181b; }.pricing-cta p { margin: 0; font-family: Georgia, 'Times New Roman', serif; font-size: 1.4rem; }.pricing-cta a { display: inline-flex; gap: 3rem; padding: 1rem 1.2rem; color: white; background: #2738d6; font-weight: 760; text-decoration: none; }.pricing-cta a span { color: #ffb8a7; }
	@media (max-width: 800px) { .pricing-hero, .calculator-layout, .section-head { grid-template-columns: 1fr; gap: 2.5rem; }.hero-side { max-width: 32rem; }.question-list article { grid-template-columns: 2rem 1fr; }.question-list p { grid-column: 2; } }
	@media (max-width: 560px) { .pricing-hero { padding-top: 4rem; }.rates { grid-template-columns: 1fr; padding-bottom: 6rem; }.rates article { min-height: auto; }.rates article + article { border-top: 0; border-left: 1px solid #cec9bf; }.calculator-section, .questions { padding-top: 6rem; padding-bottom: 6rem; }.value { align-items: flex-start; flex-direction: column; gap: .5rem; }.question-list article { gap: 1rem; }.pricing-cta { align-items: flex-start; flex-direction: column; padding-bottom: 6rem; } }
</style>
