<script lang="ts">
 import VerifyIdentity from '$lib/components/VerifyIdentity.svelte';
 import {onMount} from 'svelte';import {adminGet,localTime,localInput,lagosISO} from '$lib/admin-client';import {formatKobo,parseNaira,exactKobo} from '$lib/money';
 import {LatestRequest,record,rows,text} from '$lib/api/reliable';
 import {MutationIntent} from '$lib/api/mutation';
 const reads=new LatestRequest();
 const intents=new Map<string,MutationIntent>();
 function write(url:string,payload:unknown,decode:(value:unknown)=>unknown){let intent=intents.get(url);if(!intent){intent=new MutationIntent('admin-financial-changes',url);intents.set(url,intent);}return intent.run(payload,decode);}
 function snapshot(value:unknown,requireItems=false){const result=record(value);if(exactKobo(result.outstanding_kobo as any)===null)throw new Error('Outstanding amount was incomplete');if(requireItems||result.items!==undefined){rows('items',value=>{const item=record(value);text(item.id);text(item.due_at);if(exactKobo(item.principal_due_kobo as any)===null||exactKobo(item.allocated_kobo as any)===null)throw new Error('Schedule amounts were incomplete');return item;})(result);}return result;}
 function change(value:unknown){const item=record(value);for(const key of ['id','kind','state','reason','proposed_by','proposer','expires_at','obligation_id'])text(item[key]);const proposed=record(item.proposed_values);snapshot(item.before_values,item.kind==='schedule_amendment');if(item.kind==='schedule_amendment'){rows('dates',value=>{const date=record(value);text(date.item_id);text(date.due_at);return date;})(proposed);}else if(exactKobo(proposed.amount_kobo as any)===null)throw new Error('Proposed amount was incomplete');return item;}
 function difference(a:any,b:any){const x=exactKobo(a),y=exactKobo(b);return formatKobo(x===null||y===null?null:x-y)}
 let changes:any[]=$state([]),context:any=$state(null),reference=$state(''),kind=$state('write_off'),amount=$state(''),reason=$state(''),expires=$state(''),dates:Record<string,string>=$state({}),notes:Record<string,string>=$state({});let proposalID=$state(crypto.randomUUID()),busy=$state(false),error=$state(''),message=$state(''),actor=$state(''),roles:string[]=$state([]),q=$state(''),offset=$state(0),more=$state(false);
 let isPlatformOwner=$state(false),governanceMode=$state('unavailable');
 let canPropose=$derived(roles.includes('platform_admin')||roles.includes('finance_operator')||roles.includes('platform_owner'));let canApprove=$derived(roles.includes('platform_admin')||roles.includes('approver')||roles.includes('platform_owner'));
 async function load(){const read=reads.begin();busy=true;error='';changes=[];more=false;roles=[];governanceMode='unavailable';isPlatformOwner=false;try{const [b,c,gov]=await Promise.all([adminGet(`/api/v1/ops/admin-changes?q=${encodeURIComponent(q)}&offset=${offset}`,read.signal),adminGet('/api/v1/ops/capabilities',read.signal),adminGet('/api/v1/ops/governance',read.signal)]);if(!read.current())return;if(!Array.isArray(b.changes)||!Array.isArray(c.roles)||!['solo_owner','delegated_team'].includes(gov.governance?.mode))throw new Error('Proposals and approval rules could not be verified.');const verified=rows('changes',change)(b);c.roles.forEach(text);text(c.actor_id);changes=verified.slice(0,100);more=verified.length>100;actor=c.actor_id;roles=c.roles;isPlatformOwner=c.roles?.includes('platform_owner')||false;if(gov.governance?.mode)governanceMode=gov.governance?.mode;}catch(e){if(read.current())error=e instanceof Error?e.message:'That did not go through. Try again.'}finally{if(read.current())busy=false}}
 async function lookup(){if(busy)return;busy=true;error='';context=null;try{const loaded=await adminGet(`/api/v1/ops/change-context?q=${encodeURIComponent(reference)}`);text(loaded.obligation_id);snapshot(loaded.snapshot,true);context=loaded;dates=Object.fromEntries(context.snapshot.items.filter((i:any)=>!i.cancelled&&i.principal_due_kobo>i.allocated_kobo).map((i:any)=>[i.id,localInput(i.due_at)]));proposalID=crypto.randomUUID()}catch(e){error=e instanceof Error?e.message:'That did not go through. Try again.'}finally{busy=false}}
 async function propose(){if(busy)return;busy=true;error='';message='';try{const values=kind==='schedule_amendment'?{amount_kobo:0,dates:Object.entries(dates).map(([item_id,date])=>({item_id,due_at:lagosISO(date)}))}:{amount_kobo:parseNaira(amount),dates:[]};const expectedID=proposalID;await write('/api/v1/ops/admin-changes',{id:expectedID,obligation_id:context.obligation_id,kind,reason,values,expires_at:lagosISO(expires)},value=>{if(record(value).id!==expectedID)throw new Error('Proposal was not confirmed');return true;});context=null;amount='';reason='';message='Proposal recorded for review.';await load()}catch(e){error=e instanceof Error?e.message:'That did not go through. Try again.'}finally{busy=false}}
 async function decide(c:any,action:string){if(busy)return;busy=true;error='';try{await write(`/api/v1/ops/admin-changes/${encodeURIComponent(c.id)}/decision`,{action,reason:notes[c.id]||''},value=>{if(record(value).recorded!==true)throw new Error('Decision was not confirmed');return true;});message='Decision recorded.';await load()}catch(e){error=e instanceof Error?e.message:'That did not go through. Try again.'}finally{busy=false}}
 async function soloApprove(c:any){if(busy)return;busy=true;error='';message='';try{await write('/api/v1/ops/solo-owner/approve',{target_type:'financial_change',target_id:c.id,reason:notes[c.id]||'',confirm:true},value=>{if(record(value).approved!==true)throw new Error('Approval was not confirmed');return true;});message='Approved. The change is recorded.';await load()}catch(e){error=e instanceof Error?e.message:'That did not go through. Try again.'}finally{busy=false}}
 onMount(()=>{q=new URLSearchParams(location.search).get('change')||'';void load();return()=>reads.cancel();});
</script>
<svelte:head><title>Financial changes — Kredit admin</title></svelte:head>
<main class="shell workspace"><h1>Financial changes</h1><VerifyIdentity/><p>{governanceMode === 'solo_owner' ? 'You approve your own corrections, with a fresh authenticator code and a written reason.' : governanceMode === 'delegated_team' ? 'Every correction needs a second administrator to approve it.' : 'Who approves a correction could not be read just now. Record the proposal; the approval rule is applied when the decision is made.'} Changing a payment date also needs the customer to accept it. The amounts and the original agreement are never overwritten when dates change.</p>{#if error}<p role="alert">{error}</p>{/if}{#if message}<p role="status">{message}</p>{/if}
 {#if canPropose}<section><h2>Propose a change</h2><form onsubmit={(e)=>{e.preventDefault();lookup()}}><label>Sale or obligation reference<input disabled={busy} bind:value={reference} required/></label><button disabled={busy}>Load the current details</button></form>
 {#if context}<p>Outstanding: <strong>{formatKobo(context.snapshot.outstanding_kobo)}</strong></p><form onsubmit={(e)=>{e.preventDefault();propose()}}><label>Change<select disabled={busy} bind:value={kind}><option value="write_off">Write off money owed</option><option value="fee_waiver">Cancel seller fees</option><option value="schedule_amendment">Change payment dates</option></select></label>
 {#if kind==='schedule_amendment'}<p>List every unpaid part-payment in its current order. Dates must leave enough notice. Any debit with an unclear result must be settled first.</p>{#each context.snapshot.items.filter((i:any)=>i.id in dates) as item}<label>{difference(item?.principal_due_kobo,item?.allocated_kobo)} · currently {localTime(item?.due_at || '')}<input type="datetime-local" disabled={busy} bind:value={dates[item.id]} required/></label>{/each}{:else}<label>Amount (₦)<input disabled={busy} inputmode="decimal" bind:value={amount} required/></label>{/if}
 <label>Proposal expires (Lagos, within 30 days)<input type="datetime-local" disabled={busy} bind:value={expires} required/></label><label>Reason<textarea disabled={busy} bind:value={reason} minlength="8" maxlength="2000" required></textarea></label><button disabled={busy}>{governanceMode === 'solo_owner' ? 'Record this proposal' : 'Send for approval'}</button></form>{/if}</section>{/if}
 <h2>Review proposals</h2><form onsubmit={(e)=>{e.preventDefault();offset=0;load()}}><label>Proposal or obligation reference<input type="search" bind:value={q}/></label><button disabled={busy}>Find a proposal</button></form>
 {#each changes as c}<article id={c.id}><h3>{c.kind.replaceAll('_',' ')} · {c.state.replaceAll('_',' ')}</h3><p>{c.reason}</p><p>Proposed by {c.proposer}{#if c.approver} · Approved by {c.approver}{/if}</p><p>Expires {localTime(c.expires_at)} · Reference {c.obligation_id}</p>
 {#if c.kind==='schedule_amendment'}<table><thead><tr><th>Unpaid amount</th><th>Current date at proposal</th><th>Proposed date</th></tr></thead><tbody>{#each c.proposed_values.dates as date}{@const item=c.before_values.items.find((i:any)=>i.id===date.item_id)}<tr><td>{difference(item?.principal_due_kobo,item?.allocated_kobo)}</td><td>{localTime(item?.due_at || '')}</td><td>{localTime(date.due_at)}</td></tr>{/each}</tbody></table><p>Approval sends these dates to the buyer. Dates take effect only after the buyer accepts.</p>{:else}<p>Proposed {c.kind==='write_off'?'principal reduction':'fee waiver'}: <strong>{formatKobo(c.proposed_values.amount_kobo)}</strong></p><p>Outstanding at proposal: {formatKobo(c.before_values.outstanding_kobo)}</p>{/if}
 {#if ['pending','awaiting_buyer'].includes(c.state)}<label>Decision notes<textarea disabled={busy} bind:value={notes[c.id]} minlength="8" maxlength="2000"></textarea></label>{#if canApprove&&c.state==='pending'&&c.proposed_by!==actor}<button disabled={busy||(notes[c.id]||'').trim().length<8} onclick={()=>decide(c,'approve')}>Approve exactly this</button><button disabled={busy||(notes[c.id]||'').trim().length<8} onclick={()=>decide(c,'reject')}>Reject</button>{/if}{#if c.state==='pending'&&c.proposed_by===actor&&isPlatformOwner&&governanceMode==='solo_owner'}<button class="primary" disabled={busy||(notes[c.id]||'').trim().length<8} onclick={()=>soloApprove(c)}>Approve my own change</button>{/if}{#if c.proposed_by===actor||canApprove}<button disabled={busy||(notes[c.id]||'').trim().length<8} onclick={()=>decide(c,'cancel')}>Cancel proposal</button>{/if}{/if}<p><a href={`/admin/history?q=${c.id}`}>See every decision</a></p></article>{:else}{#if !busy&&!error}<p>No matching proposals.</p>{/if}{/each}
 <button disabled={busy||!offset} onclick={()=>{offset=Math.max(0,offset-100);load()}}>Previous</button><button disabled={busy||!more} onclick={()=>{offset+=100;load()}}>Next</button>
</main>
<style>section,article{border:1px solid #bbb6ac;padding:1.2rem;background:#fffdf6;margin:1.5rem 0;overflow:auto}label{display:block;margin:.8rem 0}input,select,textarea{display:block;width:30rem;max-width:100%;padding:.7rem}button{padding:.7rem;margin:.5rem .5rem .5rem 0}th,td{text-align:left;padding:.7rem;border-bottom:1px solid #ccc}p{overflow-wrap:anywhere}</style>
