<script lang="ts">
 import VerifyIdentity from '$lib/components/VerifyIdentity.svelte';
 import {onMount} from 'svelte';import {adminGet,adminPost,localTime,localInput,lagosISO} from '$lib/admin-client';import {formatKobo,parseNaira} from '$lib/money';
 let changes:any[]=$state([]),context:any=$state(null),reference=$state(''),kind=$state('write_off'),amount=$state(''),reason=$state(''),expires=$state(''),dates:Record<string,string>=$state({}),notes:Record<string,string>=$state({});let proposalID=$state(crypto.randomUUID()),busy=$state(false),error=$state(''),message=$state(''),actor=$state(''),roles:string[]=$state([]),q=$state(''),offset=$state(0),more=$state(false);
 let canPropose=$derived(roles.includes('platform_admin')||roles.includes('finance_operator'));let canApprove=$derived(roles.includes('platform_admin')||roles.includes('approver'));
 async function load(){busy=true;error='';try{const [b,c]=await Promise.all([adminGet(`/api/v1/ops/admin-changes?q=${encodeURIComponent(q)}&offset=${offset}`),adminGet('/api/v1/ops/capabilities')]);changes=b.changes.slice(0,100);more=b.changes.length>100;actor=c.actor_id;roles=c.roles}catch(e){error=String(e)}finally{busy=false}}
 async function lookup(){busy=true;error='';context=null;try{context=await adminGet(`/api/v1/ops/change-context?q=${encodeURIComponent(reference)}`);dates=Object.fromEntries(context.snapshot.items.filter((i:any)=>!i.cancelled&&i.principal_due_kobo>i.allocated_kobo).map((i:any)=>[i.id,localInput(i.due_at)]));proposalID=crypto.randomUUID()}catch(e){error=String(e)}finally{busy=false}}
 async function propose(){busy=true;error='';message='';try{const values=kind==='schedule_amendment'?{amount_kobo:0,dates:Object.entries(dates).map(([item_id,date])=>({item_id,due_at:lagosISO(date)}))}:{amount_kobo:parseNaira(amount),dates:[]};await adminPost('/api/v1/ops/admin-changes',{id:proposalID,obligation_id:context.obligation_id,kind,reason,values,expires_at:lagosISO(expires)});context=null;amount='';reason='';message='Proposal recorded for independent review.';await load()}catch(e){error=String(e)}finally{busy=false}}
 async function decide(c:any,action:string){busy=true;error='';try{await adminPost(`/api/v1/ops/admin-changes/${c.id}/decision`,{action,reason:notes[c.id]||''});message='Decision recorded.';await load()}catch(e){error=String(e)}finally{busy=false}}
 onMount(()=>{q=new URLSearchParams(location.search).get('change')||'';load()});
</script>
<svelte:head><title>Financial changes — Kredit admin</title></svelte:head>
<main class="shell workspace"><h1>Financial changes</h1><VerifyIdentity/><p>Corrections require independent approval. Repayment-date changes also need the buyer’s explicit acceptance. Amounts and original agreement records are preserved when dates change.</p>{#if error}<p role="alert">{error}</p>{/if}{#if message}<p role="status">{message}</p>{/if}
 {#if canPropose}<section><h2>Propose a change</h2><form onsubmit={(e)=>{e.preventDefault();lookup()}}><label>Obligation or credit request reference<input bind:value={reference} required/></label><button disabled={busy}>Load current details</button></form>
 {#if context}<p>Outstanding: <strong>{formatKobo(context.snapshot.outstanding_kobo)}</strong></p><form onsubmit={(e)=>{e.preventDefault();propose()}}><label>Change<select bind:value={kind}><option value="write_off">Write off principal</option><option value="fee_waiver">Waive supplier fees</option><option value="schedule_amendment">Change repayment dates</option></select></label>
 {#if kind==='schedule_amendment'}<p>Include every unpaid instalment in its existing order. Dates must allow the current notice period. Any unresolved debit must be reconciled first.</p>{#each context.snapshot.items.filter((i:any)=>i.id in dates) as item}<label>{formatKobo(item.principal_due_kobo-item.allocated_kobo)} · currently {localTime(item.due_at)}<input type="datetime-local" bind:value={dates[item.id]} required/></label>{/each}{:else}<label>Amount (₦)<input inputmode="decimal" bind:value={amount} required/></label>{/if}
 <label>Proposal expires (Lagos, within 30 days)<input type="datetime-local" bind:value={expires} required/></label><label>Reason<textarea bind:value={reason} minlength="8" maxlength="2000" required></textarea></label><button disabled={busy}>Submit for independent approval</button></form>{/if}</section>{/if}
 <h2>Review proposals</h2><form onsubmit={(e)=>{e.preventDefault();offset=0;load()}}><label>Proposal or obligation reference<input type="search" bind:value={q}/></label><button disabled={busy}>Find proposals</button></form>
 {#each changes as c}<article id={c.id}><h3>{c.kind.replaceAll('_',' ')} · {c.state.replaceAll('_',' ')}</h3><p>{c.reason}</p><p>Proposed by {c.proposer}{#if c.approver} · Approved by {c.approver}{/if}</p><p>Expires {localTime(c.expires_at)} · Reference {c.obligation_id}</p>
 {#if c.kind==='schedule_amendment'}<table><thead><tr><th>Unpaid amount</th><th>Current date at proposal</th><th>Proposed date</th></tr></thead><tbody>{#each c.proposed_values.dates as date}{@const item=c.before_values.items.find((i:any)=>i.id===date.item_id)}<tr><td>{formatKobo(item.principal_due_kobo-item.allocated_kobo)}</td><td>{localTime(item.due_at)}</td><td>{localTime(date.due_at)}</td></tr>{/each}</tbody></table><p>Approval sends these dates to the buyer. Dates take effect only after the buyer accepts.</p>{:else}<p>Proposed {c.kind==='write_off'?'principal reduction':'fee waiver'}: <strong>{formatKobo(c.proposed_values.amount_kobo)}</strong></p><p>Outstanding at proposal: {formatKobo(c.before_values.outstanding_kobo)}</p>{/if}
 {#if ['pending','awaiting_buyer'].includes(c.state)}<label>Decision notes<textarea bind:value={notes[c.id]} minlength="8" maxlength="2000"></textarea></label>{#if canApprove&&c.state==='pending'&&c.proposed_by!==actor}<button disabled={busy||(notes[c.id]||'').trim().length<8} onclick={()=>decide(c,'approve')}>Approve exact proposal</button><button disabled={busy||(notes[c.id]||'').trim().length<8} onclick={()=>decide(c,'reject')}>Reject</button>{/if}{#if c.proposed_by===actor||canApprove}<button disabled={busy||(notes[c.id]||'').trim().length<8} onclick={()=>decide(c,'cancel')}>Cancel proposal</button>{/if}{/if}<p><a href={`/admin/history?q=${c.id}`}>View complete decision history</a></p></article>{:else}<p>No matching proposals.</p>{/each}
 <button disabled={busy||!offset} onclick={()=>{offset=Math.max(0,offset-100);load()}}>Previous</button><button disabled={busy||!more} onclick={()=>{offset+=100;load()}}>Next</button>
</main>
<style>section,article{border:1px solid #bbb6ac;padding:1.2rem;background:#fffdf6;margin:1.5rem 0;overflow:auto}label{display:block;margin:.8rem 0}input,select,textarea{display:block;width:30rem;max-width:100%;padding:.7rem}button{padding:.7rem;margin:.5rem .5rem .5rem 0}th,td{text-align:left;padding:.7rem;border-bottom:1px solid #ccc}p{overflow-wrap:anywhere}</style>
