<script lang="ts">
	let { data } = $props();
	let effectiveDate = $derived(data.legal.effectiveDate
		? new Date(`${data.legal.effectiveDate}T12:00:00Z`).toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' })
		: '');
</script>

<svelte:head><title>Terms of service — Kredit</title></svelte:head>

<main class="shell prose-page legal-page">
	<p class="eyebrow">Terms of service · {data.legal.termsVersion}</p>
	<h1>Clear rules for using Kredit.</h1>
	<p class="lede">Kredit helps a seller and customer put a credit sale in writing, confirm the goods and keep one payment record. These terms explain each person's responsibility.</p>

	{#if data.legal.active}<aside class="active-note"><strong>Effective {effectiveDate}</strong><p>These terms form an agreement between you and {data.legal.entityName} when you accept them while using Kredit.</p></aside>{:else}<aside class="review-note"><strong>Complete pre-launch draft — legal approval pending</strong><p>The product and commercial rules are described below. Kredit's final registered company name, service address, effective date and approved provider disclosures must be added before launch. These terms are not active and no user will be asked to accept them until legal and provider review is complete.</p></aside>{/if}
	<div class="document-meta" aria-label="Document information"><span>{data.legal.termsVersion}</span><span>{data.legal.active ? `Effective ${effectiveDate}` : 'Last reviewed 31 August 2026'}</span><span>Nigeria</span></div>

	<nav class="contents" aria-label="Terms contents"><strong>On this page</strong><a href="#service">1. What Kredit does</a><a href="#accounts">2. Accounts and businesses</a><a href="#sale">3. Making a credit sale</a><a href="#goods">4. Goods and problems</a><a href="#payments">5. Payments and fees</a><a href="#debit">6. Bank-debit permission</a><a href="#responsibilities">7. Responsibilities</a><a href="#ending">8. Suspension and closure</a><a href="#legal">9. Legal terms</a><a href="#help">10. Help and complaints</a></nav>

	<section id="agreement"><h2>Before you use Kredit</h2><p>Read these terms together with the Privacy Notice, the exact sale shown before acceptance, the payment mandate and any fee shown to the seller. If you act for a business, “you” includes that business where the context requires it.</p><p>By accepting these terms, you confirm that you understand them and have authority to use the account. Accepting these general terms does not force a customer to accept any sale. Each sale needs its own clear acceptance.</p></section>

	<section id="service"><h2>1. What Kredit does</h2><p>Kredit provides tools that allow an existing seller and customer to:</p><ul><li>record the goods, price, payment day, extra time and any payment plan;</li><li>show the same terms to the customer before the customer says yes;</li><li>keep evidence of acceptance, goods release and customer receipt;</li><li>record payments made to the seller or through an approved provider;</li><li>show the amount still unpaid;</li><li>send account and payment reminders;</li><li>report and review a problem; and</li><li>request an authorised bank debit for an eligible unpaid amount after the agreed time.</li></ul><p><strong>Kredit is not the seller and does not supply the goods.</strong> Kredit does not choose the customer, decide the quality of goods or promise that a customer will pay. In the first release, Kredit does not lend the purchase money to either side. The seller supplies its own goods and allows payment later.</p><p>Kredit is not a bank, wallet, credit bureau, insurance company, marketplace or debt buyer. Any regulated identity, banking or payment function must be performed through an appropriately approved provider. A provider's own terms may also apply to that function.</p></section>

	<section id="accounts"><h2>2. Accounts, age and business authority</h2><ul><li>You must be at least 18 years old and able to enter a binding agreement.</li><li>You must give correct, current information and update it when it changes.</li><li>You must control the phone number or email used for your account.</li><li>If you represent a business, you must have permission to bind or act for it.</li><li>A business does not need a CAC registration number merely to begin setup, but Kredit or a provider may require other proof before money can move.</li><li>You must complete identity, business, bank-account or extra sign-in checks when a sensitive action requires them.</li></ul><p>A business owner may invite staff and choose their roles. The owner is responsible for removing access when a staff member should no longer act. Kredit records important access and account actions.</p><p>Keep your device, sign-in method, OTP, authenticator and recovery codes secure. Do not share them. Tell Kredit quickly if an account or device may have been taken over. Kredit will never ask for your bank PIN or a full card number in a support message.</p></section>

	<section id="sale"><h2>3. Making a credit sale</h2><h3>The seller creates the offer</h3><p>The seller chooses the customer and enters the goods, price, payment date, extra time, payment plan and bank-debit timing. The seller must check these details before sending them. A draft may be changed or deleted before it is sent.</p><h3>The customer checks and accepts</h3><p>The customer receives a private link, confirms the required details and sees the exact sale before accepting. The customer may say no. A sale does not become active merely because the seller created it, sent a link or obtained a general account registration.</p><h3>Accepted terms cannot be secretly changed</h3><p>Kredit keeps a version and protected document hash for accepted terms. A seller cannot replace the accepted amount, goods or dates without a new, lawful agreement. Where the product allows payment dates to be changed, both sides must first agree and the change cannot rewrite a payment already made.</p><h3>Keep your own commercial records</h3><p>Kredit records the transaction in the service but does not replace every invoice, tax record, stock record, warranty or document a business may be required to keep.</p></section>

	<section id="goods"><h2>4. Goods, delivery and problems</h2><p>The seller is responsible for the goods, description, price, quality, safety, delivery and any promise made about them. Kredit does not inspect or approve goods.</p><p>After customer acceptance, the seller records when and how the goods leave. The customer confirms receipt or reports a problem. Both sides must act honestly and keep useful evidence such as a delivery number, receipt, photo or document.</p><p>If the customer reports a genuine problem, Kredit may pause bank debit for the amount affected while the matter is reviewed. The remaining undisputed amount may still be due where the accepted sale and applicable law allow it. Reporting a problem does not automatically cancel the full sale, and it must not be used only to delay payment.</p><p>The seller and customer should first try to settle the matter with clear evidence. Kredit may help record the decision or apply a permitted adjustment, but is not a court and may require a formal complaint or external legal process where the issue cannot be resolved in the product.</p></section>

	<section id="payments"><h2>5. Payments, balances and Kredit fees</h2><h3>Payments</h3><p>A customer may pay the seller directly or through an available approved payment method. When a customer reports a direct transfer, the seller must check the seller's bank before confirming it. Kredit reduces the amount left only when the payment is recognised. A reversed or failed payment may make money due again.</p><p>A customer must not pay more than the amount lawfully due. Kredit recalculates the true unpaid amount before any bank-debit request and uses controls intended to prevent duplicate collection. A pending payment, provider delay or reconciliation issue may temporarily stop another money action.</p><h3>Fees paid by the seller</h3><p>Adding a customer or draft sale has no fee. The rates recorded in each offer govern that sale:</p><ul><li>the supplier base service fee applies to activated principal after the required acceptance and goods steps; and</li><li>the recorded additional collection fee applies only to money successfully collected through Kredit at or after the permitted collection time.</li></ul><p>Changing the published rates does not change existing offers. <a href="/pricing">Current pricing</a> applies to new offers. A failed debit does not earn the additional collection fee. A sale cancelled before activation does not earn the base fee. The seller must review the applicable rates before agreeing to the sale.</p><p>The customer pays the accepted price of the goods and any customer charge clearly included in the individual sale and permitted by law. Kredit does not silently add the seller's platform fee to the customer's debt.</p><p>Taxes may apply to Kredit fees. The final invoice and tax treatment will follow applicable law. If a fee or payment record is wrong, use the correction or complaint process; do not edit a completed financial record outside the provided reversal or correction flow.</p></section>

	<section id="debit"><h2>6. Bank-debit permission and late payment</h2><p>A customer may be asked to create a separate mandate with a bank or approved payment provider. The mandate is authority for payments within its stated amount, duration and scope. It is not itself proof that the underlying sale is valid, and it does not give Kredit unrestricted access to every account.</p><p>Before a sale is accepted, the customer sees the payment day, extra time and the earliest time an automatic debit may be requested. Kredit may request only an eligible unpaid amount within the accepted terms and active mandate. Reminders, provider availability, a payment claim, a dispute, a risk hold or a legal requirement may change whether or when a request is sent.</p><p>The customer may stop or cancel a mandate through an available provider or Kredit control. Cancelling a mandate stops future use of that permission when the cancellation takes effect; it does not erase money already owed under a valid sale. The customer should arrange another payment method with the seller.</p><p>A bank or provider may reject, delay, partially complete or reverse a request. Kredit does not promise successful collection. Both sides must wait for a final confirmed result before treating an uncertain provider response as payment.</p></section>

	<section id="communications"><h2>Messages and electronic records</h2><p>You agree that Kredit may send required service, security, sale, payment, recovery and complaint messages by the contact method connected to your account. You may control optional messages and quiet hours, but you cannot turn off a message needed to protect the account or complete a transaction.</p><p>Electronic acceptance, timestamps, audit records, provider confirmations and protected document hashes may be used as evidence of what happened. Download or print any record you need for your business. Delivery of a message can fail, so you should also check the account for an important update.</p></section>

	<section id="responsibilities"><h2>7. What every user must and must not do</h2><p>You must use Kredit honestly, follow applicable law and cooperate with a reasonable check or correction. You must not:</p><ul><li>create a false person, business, sale, delivery, payment, receipt or dispute;</li><li>use another person's contact, bank or identity information without authority;</li><li>sell illegal, unsafe, stolen or prohibited goods through a Kredit record;</li><li>split, repeat or manipulate a sale to avoid a limit or review;</li><li>attempt to collect money already paid, reversed, adjusted or genuinely disputed;</li><li>harass, threaten, shame or mislead a seller or customer;</li><li>probe, copy, damage or interfere with Kredit or another user's account;</li><li>upload malware or a document you have no right to use; or</li><li>use Kredit to hide fraud, money laundering or another unlawful activity.</li></ul><p>Kredit may limit a document type, transaction size, customer group, business industry, provider, retry or other pilot feature. A displayed limit does not mean Kredit has approved a customer's creditworthiness or guaranteed a transaction.</p></section>

	<section id="availability"><h2>Service availability and third parties</h2><p>Kredit aims to keep the service available and records accurate, but maintenance, poor networks, banks, providers or events outside reasonable control may delay a page, message or payment result. Financial actions that require the server are not completed or queued merely because a device is offline.</p><p>We may improve, replace or stop a non-essential feature after reasonable notice. We will not intentionally rewrite an accepted agreement or completed financial history because a feature changes. If a provider becomes unavailable or a result is unknown, Kredit may pause the affected action and reconcile it before trying again.</p></section>

	<section id="ending"><h2>8. Suspension, closure and records after closure</h2><p>You may stop using Kredit and ask to close the account, subject to any open sale, payment, dispute, investigation or legal record. Closing an account does not cancel a valid agreement or amount already due.</p><p>Kredit may restrict or suspend an account, business or money action to protect users, obey the law, investigate suspected abuse, respond to a provider issue or enforce these terms. Where safe and lawful, we will explain the reason and how to ask for review. Urgent security action may happen before notice.</p><p>After closure, some information may be kept for the approved legal, financial, fraud-prevention and dispute period. Other information is removed or anonymised under the Privacy Notice.</p></section>

	<section id="legal"><h2>9. Legal responsibility and governing law</h2><p>Each seller remains responsible for its goods and each customer remains responsible for a valid accepted payment duty. Kredit remains responsible for providing its service with reasonable care and for rights that cannot lawfully be excluded.</p><p>To the extent allowed by law, Kredit is not responsible for a seller's goods, a customer's business decision, loss caused by false information from a user, or a bank/provider failure outside Kredit's reasonable control. Nothing in these terms removes a right, remedy or responsibility that Nigerian law says cannot be removed. Any limitation in the final approved terms must be fair, clear and proportionate to the service.</p><p>These terms and the Kredit service are governed by the laws of the Federal Republic of Nigeria. The parties should first use the complaint process. If the matter is not resolved, a person may use a competent court or regulator.{data.legal.active ? ` Legal notices may be sent to ${data.legal.entityName}, ${data.legal.serviceAddress}.` : ' The final company and legal-service details will be inserted before these terms become active.'}</p></section>

	<section id="changes"><h2>Changes to these terms</h2><p>A new version will show its date and important changes. A material change that affects existing users will be communicated before it applies, and a new acceptance will be requested where required. The version accepted for an individual sale remains part of that sale's record. We will not use a later general update to secretly change accepted goods, price or payment dates.</p><p>If one part of these terms cannot be enforced, the remaining parts continue where the law allows. Delay in enforcing a term is not a permanent waiver. You may not transfer an account or agreement without the permissions required by the product and law. Kredit may transfer the service to a lawful successor with appropriate notice and protection of user rights.</p></section>

	<section id="help"><h2>10. Help, complaints and regulators</h2><p>Use <a href="/legal/complaints">Help and complaints</a> and include the Kredit reference, date, amount, what happened and the result you expect. Never send your password, OTP, bank PIN or full card number.</p>{#if data.legal.active}<p>You may also email <a href={`mailto:${data.legal.legalEmail}`}>{data.legal.legalEmail}</a> or write to {data.legal.entityName}, {data.legal.serviceAddress}.</p>{/if}<p>If the concern is not resolved, you may use a competent Nigerian regulator or court. Consumer concerns may fall within the remit of the <a href="https://fccpc.gov.ng/" rel="noreferrer">Federal Competition and Consumer Protection Commission</a>. Privacy complaints may be made to the <a href="https://www.ndpc.gov.ng/" rel="noreferrer">Nigeria Data Protection Commission</a>. A bank or payment-provider complaint may also need the provider's process or the appropriate financial regulator.</p></section>

	<div class="document-actions"><a class="primary-button" href="/how-it-works">See how Kredit works</a><a href="/pricing">See the price</a><a href="/legal/privacy">Read the privacy notice</a></div>
</main>

<style>
	.legal-page{max-width:72rem;padding-bottom:7rem}.legal-page>h1{max-width:12ch;font-family:Georgia,'Times New Roman',serif;font-size:clamp(3.5rem,8vw,7rem);font-weight:500;line-height:.9;letter-spacing:-.06em}.review-note,.active-note{margin:2rem 0;padding:1.25rem;border-left:5px solid #ad641b;background:#fff4e6}.active-note{border-color:#176b45;background:#edf8f2}.review-note p,.active-note p,.legal-page li,.legal-page section>p{color:var(--color-muted);line-height:1.72}.document-meta{display:flex;flex-wrap:wrap;gap:.5rem 1.5rem;padding:1rem 0;border-top:1px solid var(--color-border);border-bottom:1px solid var(--color-border);font-size:.82rem;font-weight:750}.contents{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem 2rem;margin:3rem 0;padding:1.5rem;color:#fff;background:#17181b}.contents strong{grid-column:1/-1}.contents a{color:#c9cdff}.legal-page section{scroll-margin-top:2rem;margin:3.5rem 0}.legal-page h2{max-width:22ch;font-family:Georgia,'Times New Roman',serif;font-size:clamp(2rem,4vw,3.1rem);font-weight:500;line-height:1}.legal-page h3{margin-top:1.5rem;font-size:1.05rem}.legal-page li{margin:.7rem 0}.document-actions{display:flex;align-items:center;flex-wrap:wrap;gap:1.5rem;margin-top:4rem;padding-top:1.5rem;border-top:3px solid #17181b}.document-actions>a:not(.primary-button){font-weight:750}@media(max-width:640px){.contents{grid-template-columns:1fr}.contents strong{grid-column:auto}.document-actions{align-items:flex-start;flex-direction:column}}
</style>
