<script lang="ts">
 import { localDateTime } from '$lib/datetime';
 import {feeDisclosure} from "$lib/fee-terms";
 import { parseNaira } from '$lib/money';
	import { page } from '$app/state';
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	import Money from '$lib/components/Money.svelte';
	import ShareActions from '$lib/components/ShareActions.svelte';
	import { productLabel } from '$lib/product-language';
	const id = $derived(page.params.id);
	let organizationID = $state(''), view: any = $state(null), payments: any[] = $state([]), error = $state(''), busy = $state(false);
	let scheduleRecord:any=$state(null),scheduleItems:any[]=$state([]),paymentClaims:any[]=$state([]),collectionAttempts:any[]=$state([]),eligibility:any=$state(null),teamMembers:any[]=$state([]),notice=$state('');
	let deliveryMethod = $state('supplier_delivery'), releaseNotes = $state(''), paymentAmount = $state(''), paymentReference = $state(''), paymentSource = $state('supplier_recorded_transfer');
	let paymentNotice = $state('');
	let reversePaymentID=$state(''),reverseReason=$state(''),claimReviewReason=$state(''),operationType=$state('write-off'),operationAmount=$state(''),operationReason=$state(''),approvedBy=$state('');
	let editScheduleType=$state('one_time'),editScheduleCount=$state(2),editScheduleCadence=$state('monthly'),editScheduleStart=$state(''),editScheduleGrace=$state(24),editCustomSchedule=$state('');
	let draftPrincipal = $state(''), draftGoods = $state(''), draftDueDate = $state(''), draftCollectionAt = $state(''), draftGraceHours = $state(0);
	let disputeAmount=$state(''),disputeReason=$state(''),disputeExplanation=$state(''),disputeEffect=$state('CONTESTED_ONLY');
	async function load() {
		organizationID = page.url.searchParams.get('organization') ?? organizationID;
		if (!organizationID) { const organizations = await fetch('/api/v1/organizations', { credentials: 'include' }); if (organizations.ok) organizationID = (await organizations.json()).organizations?.[0]?.id ?? ''; }
		if (!organizationID) { error = 'Add your business before opening a sale.'; return; }
		const response = await fetch(`/api/v1/organizations/${organizationID}/credit-requests/${id}`, { credentials: 'include' });
		if (!response.ok) { error = 'We could not open this sale.'; return; }
		view = await response.json();
		if (view.request.state === 'DRAFT') { draftPrincipal = String(view.request.principal_kobo / 100); draftGoods = view.request.goods_description; draftDueDate = view.request.due_date; draftCollectionAt = localDateTime(view.request.collection_at); draftGraceHours = view.request.grace_hours; }
		if (view.obligation) {
			const base=`/api/v1/organizations/${organizationID}/credit-requests/${id}`;
			const [paymentResponse,scheduleResponse,claimResponse,eligibilityResponse,collectionResponse,memberResponse]=await Promise.all([fetch(`${base}/payments`,{credentials:'include'}),fetch(`${base}/schedule`,{credentials:'include'}),fetch(`${base}/payment-claims`,{credentials:'include'}),fetch(`${base}/collection/eligibility`,{credentials:'include'}),fetch(`${base}/collections`,{credentials:'include'}),fetch(`/api/v1/organizations/${organizationID}/members`,{credentials:'include'})]);
			payments=paymentResponse.ok?(await paymentResponse.json()).payments??[]:[];if(scheduleResponse.ok){const scheduleData=await scheduleResponse.json();scheduleRecord=scheduleData.schedule;scheduleItems=scheduleData.items??[];editScheduleType=scheduleRecord?.schedule_type==='custom'?'custom':scheduleItems.length===1?'one_time':'equal';editScheduleCount=Math.max(2,scheduleItems.length);editScheduleCadence=scheduleRecord?.cadence==='custom'?'monthly':scheduleRecord?.cadence??'monthly';editScheduleStart=scheduleItems[0]?.due_at?.slice(0,10)??view.request.due_date;editScheduleGrace=scheduleRecord?.grace_hours??view.request.grace_hours;editCustomSchedule=scheduleItems.map((item:any)=>`${item.principal_due_kobo/100}, ${item.due_at.slice(0,10)}`).join('\n')}paymentClaims=claimResponse.ok?(await claimResponse.json()).payment_claims??[]:[];eligibility=eligibilityResponse.ok?await eligibilityResponse.json():null;collectionAttempts=collectionResponse.ok?(await collectionResponse.json()).attempts??[]:[];teamMembers=memberResponse.ok?(await memberResponse.json()).members??[]:[];
		}
	}
	async function updateDraft() {
		busy = true; error = '';
		const principalKobo = parseNaira(draftPrincipal);
		const response = await fetch(`/api/v1/organizations/${organizationID}/credit-requests/${id}`, { method: 'PATCH', credentials: 'include', headers: { 'Content-Type':'application/json', 'Idempotency-Key': idempotencyKey(), ...csrfHeaders() }, body: JSON.stringify({ expected_version: view.request.version, principal_kobo: principalKobo, goods_description: draftGoods, due_date: draftDueDate, grace_hours: Number(draftGraceHours), collection_at: new Date(draftCollectionAt).toISOString() }) });
		const result = await response.json().catch(() => ({})); busy = false;
		if (!response.ok) { error = result.detail ?? 'The draft could not be updated.'; return; }
		await load();
	}
	async function command(path: string, body: any = undefined) {
		busy = true; error = '';
		const response = await fetch(`/api/v1/organizations/${organizationID}/credit-requests/${id}/${path}`, { method: 'POST', credentials: 'include', headers: { ...(body ? {'Content-Type':'application/json'} : {}), 'Idempotency-Key': idempotencyKey(), ...csrfHeaders() }, body: body ? JSON.stringify(body) : undefined });
		const result = await response.json().catch(() => ({})); busy = false;
		if (!response.ok) { error = result.detail ?? 'The action could not be completed.'; return; }
		await load();
	}
	async function recordPayment() {
		const amount = parseNaira(paymentAmount);
		if (amount <= 0) { error = 'Enter a valid payment amount.'; return; }
		await command('payments', { amount_kobo: amount, currency: 'NGN', source_type: paymentSource, provider_reference: paymentReference, paid_at: new Date().toISOString() });
		if (!error) paymentNotice = `${new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(amount/100)} payment saved.`;
		paymentAmount = ''; paymentReference = '';
	}
	async function openDispute(event:SubmitEvent){event.preventDefault();const amount=parseNaira(disputeAmount);if(amount<=0||!disputeReason.trim()){error='Enter the contested amount and reason.';return}await command('disputes',{disputed_amount_kobo:amount,reason:disputeReason,explanation:disputeExplanation,collection_effect:disputeEffect});if(!error){disputeAmount='';disputeReason='';disputeExplanation=''}}
	async function outsideCommand(path:string,body:any={}){busy=true;error='';notice='';const response=await fetch(path,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));busy=false;if(!response.ok){error=data.detail??'We could not complete this action.';return false}await load();return true}
	async function startCollection(){if(await outsideCommand(`/api/v1/organizations/${organizationID}/credit-requests/${id}/collection`,{idempotency_key:idempotencyKey()}))notice='Bank debit was sent. You can follow it below.'}
	async function collectionAction(attempt:any,action:string){if(await outsideCommand(`/api/v1/organizations/${organizationID}/collections/${attempt.id}/${action}`))notice=action==='retry'?'Bank debit was sent again.':'We checked the latest result.'}
	async function reversePayment(){if(!reversePaymentID||!reverseReason.trim()){error='Choose a payment and write why it should be removed.';return}if(await outsideCommand(`/api/v1/organizations/${organizationID}/credit-requests/${id}/payments/${reversePaymentID}/reverse`,{reason:reverseReason})){notice='The payment was reversed and the money left was updated.';reversePaymentID='';reverseReason=''}}
	async function decidePaymentClaim(claim:any,decision:string){if(!claimReviewReason.trim()){error='Write why you are accepting or rejecting this payment.';return}if(await outsideCommand(`/api/v1/organizations/${organizationID}/payment-claims/${claim.id}/decide`,{decision,reason:claimReviewReason})){notice=decision==='confirmed'?'The transfer was accepted and added as a payment.':'The customer was told that the transfer was not accepted.';claimReviewReason=''}}
	async function changeMoney(){const amount_kobo=parseNaira(operationAmount);if(amount_kobo<=0||!operationReason.trim()){error='Enter the amount and reason.';return}const path=operationType==='write-off'?'write-off':'fee-waiver';if(await outsideCommand(`/api/v1/organizations/${organizationID}/credit-requests/${id}/${path}`,{amount_kobo,reason:operationReason,approved_by:''})){notice=operationType==='write-off'?'Money owed was reduced.':'The Kredit fee was reduced.';operationAmount='';operationReason='';approvedBy=''}}
	async function openInvoice(){
        error='';
        try {
            const response=await fetch(`/api/v1/organizations/${organizationID}/documents/${view.request.invoice_document_id}/download`,{credentials:'include'});
            const result=await response.json();
            if(!response.ok){error=result.detail??'The invoice is not available.';return}
            window.location.assign(result.url);
        } catch { error='The invoice could not be opened. Please try again.' }
    }
	onMount(load);
</script>

<svelte:head><title>Sale {id} — Kredit</title></svelte:head>
<section class="page-shell">
	<a href="/app/overview">← Your sales</a>
	{#if error}<p class="error" role="alert">{error}</p>{/if}
	{#if notice}<p class="success notice" role="status">{notice}</p>{/if}
	{#if !view}<p>Opening sale…</p>{:else}
		<p class="eyebrow">Sale · {productLabel(view.request.state)}</p><h1>{view.request.buyer_legal_name}</h1>
		<p class="muted">Sale number <strong>{id}</strong>. The sale, goods and payments stay together.</p>
		<div class="quick-actions"><a class="repeat" href={`/app/credit/new?customer=${encodeURIComponent(view.request.buyer_user_id ?? '')}&goods=${encodeURIComponent(view.request.goods_description)}&amount=${view.request.principal_kobo / 100}`}>Sell these goods again</a><ShareActions compact title="Kredit payment reminder" text={`Hello ${view.request.buyer_legal_name}, this is a reminder that ${new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format((view.obligation?.outstanding_kobo ?? view.request.principal_kobo)/100)} is left for ${view.request.goods_description}. Payment day: ${scheduleItems.find((i:any)=>i.state!=='CANCELLED'&&i.principal_due_kobo>i.allocated_kobo)?.due_at?.slice(0,10)??(view.obligation?'Check your current payment schedule':view.request.due_date)}.`} /></div>
		<section class="detail-grid"><article class="card"><h2>The sale</h2><p>{feeDisclosure(view.request.fee_terms)}</p><dl><div><dt>Money to pay</dt><dd><Money amountKobo={view.request.principal_kobo} /></dd></div><div><dt>Goods</dt><dd>{view.request.goods_description}</dd></div><div><dt>{view.obligation?'Original payment day':'Pay before'}</dt><dd>{view.request.due_date}</dd></div><div><dt>{view.obligation?'Original bank debit date':'Bank debit after'}</dt><dd>{new Date(view.request.collection_at).toLocaleString()}</dd></div><div><dt>Extra time</dt><dd>{view.request.grace_hours} hours</dd></div></dl>{#if view.request.invoice_document_id}<p><button type="button" onclick={openInvoice}>Open the invoice →</button></p>{/if}</article>
		<article class="card"><h2>What is happening?</h2><p><strong>{productLabel(view.request.state)}</strong></p>{#if view.agreement?.document_hash}<details><summary>Technical record</summary><p>Sale record code<br/><code>{view.agreement.document_hash}</code></p></details>{/if}{#if view.obligation}<p>Money left<br/><strong><Money amountKobo={view.obligation.outstanding_kobo} /></strong></p><p><a href={`/api/v1/organizations/${organizationID}/credit-requests/${id}/agreement-document`} target="_blank" rel="noreferrer">Print or save this sale →</a></p>{/if}</article></section>
		{#if view.request.state === 'DRAFT'}<section class="card action"><h2>Check before you send</h2><p>You can change this sale now. After you send it, the customer must see the same sale.</p><label>Money to pay (₦)<input bind:value={draftPrincipal} inputmode="decimal" /></label><label>Goods<textarea bind:value={draftGoods}></textarea></label><label>Payment day<input type="date" bind:value={draftDueDate} /></label><label>Bank debit day and time<input type="datetime-local" bind:value={draftCollectionAt} /></label><label>Extra hours<input type="number" min="0" max="720" bind:value={draftGraceHours} /></label><div class="button-row"><button disabled={busy} onclick={updateDraft}>Save for later</button><button class="primary" disabled={busy} onclick={() => command('send')}>Send to customer</button><button class="danger" disabled={busy} onclick={() => command('cancel')}>Delete this sale</button></div></section>{/if}
		{#if view.request.state === 'SENT' || view.request.state === 'BUYER_REVIEWING'}<section class="card action"><h2>Waiting for your customer</h2><p>You can cancel if you no longer want to make this sale. The old record will stay.</p><button class="danger" disabled={busy} onclick={() => command('cancel')}>Cancel this sale</button></section>{/if}
		{#if view.request.state === 'READY_TO_RELEASE'}<section class="card action"><h2>Did the goods leave?</h2><label>How did the customer get them?<select bind:value={deliveryMethod}><option value="supplier_delivery">We delivered</option><option value="buyer_collection">Customer picked up</option><option value="third_party_delivery">Another person delivered</option></select></label><label>Delivery note<textarea bind:value={releaseNotes}></textarea></label><button class="primary" disabled={busy} onclick={() => command('release',{delivery_method:deliveryMethod,notes:releaseNotes})}>Yes, the goods left</button></section>{/if}
		{#if view.obligation}
			<section class="card action"><h2>Add money you received</h2><p>Save only money that has reached you. Check your bank app before saving a transfer.</p>{#if paymentNotice}<p class="success" role="status">{paymentNotice}</p>{/if}<label>How did the customer pay?<select bind:value={paymentSource}><option value="supplier_recorded_transfer">Bank transfer or POS</option><option value="cash_recorded">Cash</option></select></label><label>Money received (₦)<input bind:value={paymentAmount} inputmode="decimal" /></label><label>{paymentSource === 'cash_recorded' ? 'Receipt or note' : 'Transfer or POS number'} <small>optional</small><input bind:value={paymentReference} /></label>{#if paymentSource === 'cash_recorded'}<p class="warning">For cash, give the customer a receipt before you save this payment.</p>{/if}<button class="primary" disabled={busy} onclick={recordPayment}>Save this payment</button><h3>Past payments</h3>{#if payments.length}<ul class="plain-list">{#each payments as payment}<li><span><Money amountKobo={payment.amount_kobo} /> · {productLabel(payment.source_type)}</span><strong>{productLabel(payment.state)}</strong></li>{/each}</ul>{:else}<p>No payment yet.</p>{/if}</section>

			<section class="card action"><h2>Payment dates</h2>{#if scheduleItems.length}<div class="table-wrap"><table><thead><tr><th>Pay before</th><th>Expected</th><th>Paid</th><th>Now</th></tr></thead><tbody>{#each scheduleItems as item}<tr><td>{new Date(item.due_at).toLocaleDateString('en-NG')}</td><td><Money amountKobo={item.principal_due_kobo} /></td><td><Money amountKobo={item.allocated_kobo} /></td><td>{productLabel(item.state)}</td></tr>{/each}</tbody></table></div>{:else}<p>This sale has one payment date.</p>{/if}<p class="muted">These are the current payment dates. Changes require independent review and the customer’s acceptance of an amendment. Contact support to request a date change.</p></section>

			<section class="card action"><h2>Transfers reported by the customer</h2><p>Check your bank before accepting any transfer. Accepting it will reduce the money left.</p>{#if paymentClaims.length}<div class="claim-list">{#each paymentClaims as claim}<article><div><strong><Money amountKobo={claim.amount_kobo} /></strong><span>{productLabel(claim.state)} · {claim.transfer_reference}</span><small>Reported {new Date(claim.paid_at).toLocaleString('en-NG')}</small></div>{#if claim.state?.toLowerCase()==='pending'}<label>Why are you accepting or rejecting it?<input bind:value={claimReviewReason} placeholder="For example: Seen in our bank account" /></label><div class="button-row"><button class="primary" disabled={busy} onclick={()=>decidePaymentClaim(claim,'confirmed')}>I received this money</button><button disabled={busy} onclick={()=>decidePaymentClaim(claim,'rejected')}>I did not receive it</button></div>{:else if claim.review_reason}<p>{claim.review_reason}</p>{/if}</article>{/each}</div>{:else}<p>The customer has not reported a transfer.</p>{/if}</section>

			<section class="card action"><h2>Collect late money</h2>{#if eligibility?.eligible}<p>Kredit can collect <strong><Money amountKobo={eligibility.amount_kobo} /></strong> from the customer’s approved bank account.</p><button class="primary" disabled={busy} onclick={startCollection}>Collect this money</button>{:else}<p>Bank debit cannot start now.</p>{#if eligibility?.reasons?.length}<ul>{#each eligibility.reasons as reason}<li>{productLabel(reason)}</li>{/each}</ul>{/if}{/if}{#if collectionAttempts.length}<h3>Bank debit history</h3><ul class="plain-list">{#each collectionAttempts as attempt}<li><span><Money amountKobo={attempt.requested_amount_kobo} /> · {productLabel(attempt.state)}<small>{new Date(attempt.requested_at).toLocaleString('en-NG')}</small></span><span class="button-row">{#if attempt.state==='FAILED'}<button disabled={busy} onclick={()=>collectionAction(attempt,'retry')}>Try again</button>{/if}{#if attempt.state==='SUBMITTED'||attempt.state==='UNKNOWN'}<button disabled={busy} onclick={()=>collectionAction(attempt,'reconcile')}>Check result</button>{/if}</span></li>{/each}</ul>{/if}</section>

			<details class="card action"><summary><strong>Correct a payment or balance</strong></summary><p>Use these only when a saved record is wrong. Every change is kept in the business activity record.</p><h3>Remove a wrong payment</h3><label>Payment<select bind:value={reversePaymentID}><option value="">Choose a payment</option>{#each payments.filter((payment)=>payment.state?.toUpperCase()==='RECOGNIZED') as payment}<option value={payment.id}>{new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(payment.amount_kobo/100)} · {payment.provider_reference||productLabel(payment.source_type)}</option>{/each}</select></label><label>Why is it wrong?<textarea bind:value={reverseReason} rows="3"></textarea></label><button disabled={busy} onclick={reversePayment}>Reverse this payment</button><hr/><h3>Reduce money on this sale</h3><label>What do you want to change?<select bind:value={operationType}><option value="write-off">Reduce money the customer owes</option><option value="fee-waiver">Remove a Kredit fee</option></select></label><label>Amount (₦)<input bind:value={operationAmount} inputmode="decimal" /></label><label>Reason<textarea bind:value={operationReason} rows="3"></textarea></label><p>Corrections of ₦10,000 or more are unavailable until separate approval can be verified.</p><button disabled={busy} onclick={changeMoney}>Save this correction</button></details>

			<section class="card action"><h2>Report a problem</h2><p>Add the money affected and what happened.</p><form onsubmit={openDispute}><label>Money affected (₦)<input bind:value={disputeAmount} inputmode="decimal" required /></label><label>Short reason<input bind:value={disputeReason} required /></label><label>What happened?<textarea bind:value={disputeExplanation} rows="4"></textarea></label><label>What should happen to bank debit?<select bind:value={disputeEffect}><option value="CONTESTED_ONLY">Stop only the money affected</option><option value="FULL_BLOCK">Stop all bank debit</option><option value="NO_AUTOMATIC_BLOCK">Save the problem but do not stop debit</option></select></label><button class="primary" disabled={busy}>Report this problem</button></form></section>
		{/if}
	{/if}
	</section>
<style>.detail-grid{display:grid;grid-template-columns:2fr 1fr;gap:1rem;margin:1.5rem 0}.card{padding:1.5rem}.notice{padding:.8rem 1rem;background:#e6f7ed}.quick-actions{display:flex;flex-wrap:wrap;align-items:center;gap:.7rem}.repeat{display:inline-flex;align-items:center;min-height:2.5rem;padding:.35rem .75rem;border:1px solid var(--color-border);font-weight:750;text-decoration:none}dl div{display:flex;justify-content:space-between;gap:2rem;border-bottom:1px solid var(--color-border);padding:.7rem 0}dd{margin:0;text-align:right;font-weight:700}.action,.action form{display:grid;gap:.8rem;margin:1rem 0}.action form{margin:0}.action label{display:grid;gap:.35rem;font-weight:700}.action input,.action select,.action textarea{padding:.75rem;border:1px solid var(--color-border);border-radius:.7rem;font:inherit}.button-row{display:flex;flex-wrap:wrap;gap:.7rem}.danger{color:var(--color-destructive);border-color:var(--color-destructive);background:var(--color-surface)}.warning{padding:.75rem;border-left:4px solid #b7791f;background:#fff8e6}.success{color:var(--color-positive);font-weight:750}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:.75rem;border-bottom:1px solid var(--color-border);white-space:nowrap}.plain-list,.claim-list{display:grid;gap:.65rem;padding:0;list-style:none}.plain-list li,.claim-list article{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:.8rem;border:1px solid var(--color-border);border-radius:.75rem}.plain-list span,.claim-list article>div{display:grid;gap:.2rem}.claim-list article{align-items:stretch;display:grid}.claim-list small,.plain-list small{display:block;color:var(--color-muted)}details summary{cursor:pointer}hr{width:100%;border:0;border-top:1px solid var(--color-border)}code{overflow-wrap:anywhere}@media(max-width:720px){.detail-grid{grid-template-columns:1fr}.plain-list li{align-items:flex-start;flex-direction:column}}
</style>
