<script lang="ts">
	import{onMount}from'svelte';import{csrfHeaders,idempotencyKey}from'$lib/api/client';import ProtectedActionDialog from'$lib/components/ProtectedActionDialog.svelte';
	let events=$state<any[]>([]),selected=$state<any>(null),message=$state(''),dialogOpen=$state(false),loading=$state(true);
	async function load(){loading=true;const response=await fetch('/api/v1/ops/provider-events',{credentials:'include'});events=response.ok?(await response.json()).events??[]:[];loading=false}
	function input(reason:string){return{command_type:'retry_webhook',target_type:selected.provider,target_id:selected.event_id,reason,expected_version:selected.attempts+1}}
	async function preview(reason:string){const response=await fetch('/api/v1/ops/commands/preview',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',...csrfHeaders()},body:JSON.stringify(input(reason))});const body=await response.json().catch(()=>({}));if(!response.ok){message=body.detail??'Preview failed. Nothing was changed.';return}return body.command.impact_preview.effect as string}
	async function confirm(reason:string){const response=await fetch('/api/v1/ops/commands',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify(input(reason))});const body=await response.json().catch(()=>({}));message=response.ok?'Webhook safely requeued.':body.detail??'Replay failed.';if(response.ok)await load();return response.ok}
	onMount(load);
</script>
<svelte:head><title>Provider events — Kredit</title></svelte:head>
<main class="shell workspace"><p class="eyebrow">Operations / Provider events</p><h1>Webhook processing history.</h1><p class="lede">Raw payloads remain private. Duplicate identity is preserved through every controlled replay.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}{#if loading}<p role="status">Loading provider events…</p>{:else}{#each events as item}<article><header><strong>{item.provider} · {item.event_type}</strong><span class="status">{item.state}</span></header><code>{item.event_id}</code><p>{item.attempts} processing attempts</p>{#if item.state==='failed'}<button onclick={()=>{selected=item;dialogOpen=true}}>Preview safe replay</button>{/if}</article>{:else}<section class="empty-state"><h2>No provider events found</h2><p>No events are visible in the selected operational window.</p></section>{/each}{/if}</main>
{#if selected}<ProtectedActionDialog bind:open={dialogOpen} title="Replay this provider event safely" description="The original provider event identity and idempotency controls are preserved. Confirm only after checking the provider's final state." confirmLabel="Confirm safe replay" {preview} onconfirm={confirm}/>{/if}
<style>article{padding:1rem;margin:1rem 0;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}header{display:flex;justify-content:space-between;gap:1rem}article button{padding:.7rem;border:1px solid var(--color-border);border-radius:.6rem;background:var(--color-surface);color:var(--color-foreground);font:inherit;font-weight:700;cursor:pointer}</style>
