<script lang="ts">
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	import { productLabel } from '$lib/product-language';
	import Money from '$lib/components/Money.svelte';
	let organizations:any[]=$state([]),organizationID=$state(''),events:any[]=$state([]),actions:any[]=$state([]),corrections:any[]=$state([]),provider:any=$state(null),readiness:any=$state(null),loading=$state(true),error=$state(''),notice=$state(''),busy=$state(''),decisionReason=$state('');
	async function load(){if(!organizationID)return;loading=true;error='';const names=['audit-events','operations','corrections','provider-status','readiness'];const responses=await Promise.all(names.map(name=>fetch(`/api/v1/organizations/${organizationID}/${name}`,{credentials:'include'})));events=responses[0].ok?(await responses[0].json()).events??[]:[];actions=responses[1].ok?(await responses[1].json()).actions??[]:[];corrections=responses[2].ok?(await responses[2].json()).corrections??[]:[];provider=responses[3].ok?await responses[3].json():null;readiness=responses[4].ok?await responses[4].json():null;if(!responses.some(r=>r.ok))error='You do not have permission to open these business records.';loading=false}
	async function decide(item:any,outcome:string){if(outcome!=='UNDER_REVIEW'&&!decisionReason.trim()){error='Write why you are making this decision.';return}busy=item.id;error='';notice='';const response=await fetch(`/api/v1/organizations/${organizationID}/corrections/${item.id}/decide`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({outcome,reason:decisionReason})});const data=await response.json().catch(()=>({}));busy='';if(!response.ok){error=data.detail??'We could not save this answer.';return}decisionReason='';notice='Your answer was saved.';await load()}
	onMount(async()=>{const response=await fetch('/api/v1/organizations',{credentials:'include'});if(response.ok){organizations=(await response.json()).organizations??[];organizationID=organizations[0]?.id??'';await load()}else{loading=false;error='We could not open your businesses.'}});
</script>
<svelte:head><title>Business activity — Kredit</title></svelte:head>
<main class="shell workspace activity"><p class="eyebrow">Business activity</p><h1>See important changes in one place.</h1><p class="lede">Check corrections, money changes, account activity and whether bank debit is available.</p>{#if organizations.length>1}<label class="business">Business<select bind:value={organizationID} onchange={load}>{#each organizations as item}<option value={item.id}>{item.trading_name||item.legal_name}</option>{/each}</select></label>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}{#if loading}<p role="status">Opening business activity…</p>{:else}
	<section class="status-grid"><article><span>Bank debit service</span><strong>{provider?.feature_enabled&&provider?.health?.healthy?'Working':'Needs checking'}</strong><small>{provider?.name||'Provider not connected'}</small></article><article><span>Account readiness</span><strong>{readiness?.ready?'Ready':productLabel(readiness?.state,'Check setup')}</strong><a href="/app/onboarding">Open setup →</a></article></section>
	<section class="card"><h2>Customer correction requests</h2><p>Customers can ask you to correct a wrong sale or payment record.</p>{#if corrections.length}<div class="corrections">{#each corrections as item}<article><div><strong>{productLabel(item.subject_type)} correction</strong><span>{productLabel(item.state)}</span></div><p>{item.reason}</p><small>Requested {new Date(item.created_at).toLocaleString('en-NG')}</small>{#if ['OPEN','UNDER_REVIEW'].includes(item.state)}<label>Why are you making this decision?<textarea bind:value={decisionReason} rows="2"></textarea></label><div class="buttons">{#if item.state==='OPEN'}<button disabled={busy===item.id} onclick={()=>decide(item,'UNDER_REVIEW')}>I am checking it</button>{/if}<button disabled={busy===item.id} onclick={()=>decide(item,'APPROVED')}>Correct the record</button><button class="secondary" disabled={busy===item.id} onclick={()=>decide(item,'REJECTED')}>Do not change it</button></div>{/if}</article>{/each}</div>{:else}<p>No customer has asked for a correction.</p>{/if}</section>
	<section class="columns"><article class="card"><h2>Money changes</h2>{#if actions.length}<ul>{#each actions as item}<li><strong>{productLabel(item.action_type)}</strong> · <Money amountKobo={item.amount_kobo}/><small>{item.reason} · {new Date(item.created_at).toLocaleString('en-NG')}</small></li>{/each}</ul>{:else}<p>No write-off or fee change has been made.</p>{/if}</article><article class="card"><h2>Account record</h2>{#if events.length}<ul>{#each events.slice(0,30) as item}<li><strong>{productLabel(item.action)}</strong><small>{new Date(item.created_at).toLocaleString('en-NG')}</small></li>{/each}</ul>{:else}<p>No account activity is available.</p>{/if}</article></section>{/if}</main>
<style>.activity{max-width:68rem}.business{display:grid;gap:.35rem;max-width:22rem;margin:1rem 0}.business select,textarea{padding:.7rem;border:1px solid var(--color-border);font:inherit}.status-grid,.columns{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1.5rem 0}.status-grid article,.card{padding:1.2rem;border:1px solid var(--color-border);background:var(--color-surface)}.status-grid span,.status-grid strong,.status-grid small{display:block}.status-grid strong{margin:.4rem 0;font-size:1.35rem}.corrections,.card ul{display:grid;gap:.7rem;padding:0;list-style:none}.corrections>article,.card li{padding:.8rem;border-left:4px solid var(--color-primary);background:var(--color-surface-muted)}.corrections>article>div{display:flex;justify-content:space-between;gap:1rem}.corrections label{display:grid;gap:.35rem}.buttons{display:flex;flex-wrap:wrap;gap:.5rem;margin-top:.6rem}.buttons button{padding:.6rem;border:1px solid var(--color-primary);background:var(--color-primary);color:#fff;font:inherit;font-weight:750}.buttons .secondary{border-color:var(--color-foreground);background:var(--color-surface);color:var(--color-foreground)}.card small{display:block;margin-top:.3rem;color:var(--color-muted)}.notice{padding:.8rem;border-left:4px solid var(--color-positive)}.error{color:var(--color-destructive)}@media(max-width:720px){.status-grid,.columns{grid-template-columns:1fr}}</style>
