<script lang="ts">
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	let sellers:any[]=$state([]),consents:any[]=$state([]),loading=$state(true),error=$state(''),notice=$state(''),busy=$state('');
	function current(orgID:string){return consents.filter(item=>item.supplier_organization_id===orgID&&item.consent_type==='payment_reminders').sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime())[0]}
	async function load(){loading=true;const [salesResponse,consentResponse]=await Promise.all([fetch('/api/v1/buyer/credit-requests',{credentials:'include'}),fetch('/api/v1/buyer/relationships/consents',{credentials:'include'})]);const sales=salesResponse.ok?(await salesResponse.json()).requests??[]:[];consents=consentResponse.ok?(await consentResponse.json()).consents??[]:[];const seen=new Map();for(const view of sales){const request=view.request??view;if(request.supplier_organization_id&&!seen.has(request.supplier_organization_id))seen.set(request.supplier_organization_id,{id:request.supplier_organization_id,name:request.supplier_trading_name||request.supplier_legal_name||'Seller'})}sellers=[...seen.values()];if(!salesResponse.ok||!consentResponse.ok)error='We could not open all your seller permissions.';loading=false}
	async function save(seller:any,granted:boolean){busy=seller.id;error='';notice='';const words=`payment_reminders|v1|${seller.id}|${granted}`;const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(words));const evidence_hash=[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join('');const response=await fetch('/api/v1/buyer/relationships/consents',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({supplier_organization_id:seller.id,consent_type:'payment_reminders',version:'v1',evidence_hash,granted})});const data=await response.json().catch(()=>({}));busy='';if(!response.ok){error=data.detail??'We could not save this permission.';return}notice=granted?`${seller.name} may send payment reminders.`:`${seller.name} may no longer send optional payment reminders.`;await load()}
	onMount(load);
</script>
<svelte:head><title>Seller permissions — Kredit</title></svelte:head>
<main class="shell workspace permissions"><p class="eyebrow">Seller permissions</p><h1>Choose who may remind you.</h1><p class="lede">Important sale, payment and safety messages still come from Kredit. This setting is only for optional payment reminders from a seller.</p>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}{#if loading}<p role="status">Opening permissions…</p>{:else if sellers.length}<section>{#each sellers as seller}{@const allowed=current(seller.id)?.granted===true}<article><div><strong>{seller.name}</strong><span>{allowed?'Reminders allowed':'Reminders stopped'}</span></div><button disabled={busy===seller.id} onclick={()=>save(seller,!allowed)}>{busy===seller.id?'Saving…':allowed?'Stop optional reminders':'Allow payment reminders'}</button></article>{/each}</section>{:else}<section class="empty-state"><h2>No sellers yet</h2><p>Your seller permissions will appear after you join a seller on Kredit.</p></section>{/if}</main>
<style>.permissions{max-width:54rem}.permissions section{display:grid;gap:.75rem;margin-top:2rem}.permissions article{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1rem;border:1px solid var(--color-border);background:var(--color-surface)}.permissions article div,.permissions article span{display:block}.permissions article span{margin-top:.3rem;color:var(--color-muted)}.permissions button{padding:.7rem;border:1px solid var(--color-primary);background:var(--color-primary);color:#fff;font:inherit;font-weight:750}.notice{padding:.8rem;border-left:4px solid var(--color-positive)}.error{color:var(--color-destructive)}@media(max-width:600px){.permissions article{align-items:stretch;flex-direction:column}}
</style>
