<script lang="ts">
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	import { productLabel } from '$lib/product-language';
	let orgID='', profile:any={}, readiness:any={requirements:[],missing:[]}, permissions:any={}, terms='',privacy='', loading=true,busy=false,message='';
	let repName='',repTitle='',contact='',channel='phone',challengeID='',code='';
	async function load(){loading=true;message='';const orgs=await fetch('/api/v1/organizations',{credentials:'include'});if(orgs.status===401){location.assign('/app');return}const od=await orgs.json();orgID=od.organizations?.[0]?.id??'';if(!orgID){loading=false;return}const r=await fetch(`/api/v1/organizations/${orgID}/onboarding`,{credentials:'include'});const d=await r.json();if(!r.ok){message=d.detail??'Onboarding could not be loaded.';loading=false;return}profile=d.profile;readiness=d.readiness;permissions=d.permissions;terms=d.current_terms_version;privacy=d.current_privacy_version;repName=profile.authorized_representative_name??'';repTitle=profile.authorized_representative_title??'';loading=false}
	async function mutate(path:string,method:string,body:any){busy=true;message='';const r=await fetch(`/api/v1/organizations/${orgID}/onboarding/${path}`,{method,credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));busy=false;if(!r.ok){message=d.detail??'This step could not be saved.';return null}if(d.profile){profile=d.profile;readiness=d.readiness}message='Saved. Your readiness review has been updated.';return d}
	async function saveRepresentative(){await mutate('representative','PATCH',{expected_version:profile.version,name:repName,title:repTitle})}
	async function requestContact(){const d=await mutate('contacts/challenges','POST',{identifier:contact,channel});if(d){challengeID=d.challenge_id;code=d.development_code??'';message='Verification code sent. Enter it below.'}}
	async function verifyContact(){const d=await mutate('contacts/verify','POST',{identifier:contact,channel,challenge_id:challengeID,code});if(d){challengeID='';code='';contact=''}}
	async function submitKYB(){await mutate('kyb','POST',{expected_version:profile.version})}
	async function refreshKYB(){await mutate('kyb/reconcile','POST',{})}
	async function acceptConsents(){await mutate('consents','POST',{expected_version:profile.version,terms_version:terms,privacy_version:privacy})}
	function simpleStep(code:string,label:string){return ({business_identity:'Who runs the business',email_verified:'Verify your email',phone_verified:'Verify your phone number',kyb_approved:'Business or owner verification',settlement_verified:'Settlement bank account',billing_configured:'Kredit fee payment method',credit_policy:'Normal sale limits',current_consents:'Terms and privacy notice',owner_mfa:'Extra sign-in protection',finance_mfa:'Protection for staff who handle money'} as Record<string,string>)[code]??label}
	onMount(load);
</script>
<svelte:head><title>Seller onboarding — Kredit</title></svelte:head>
<main class="shell workspace onboarding"><header><p class="eyebrow">Set up Kredit</p><h1>Start selling first.<br />Finish money setup as you go.</h1><p class="lede">You do not need to complete every money-movement requirement before you understand the product or create your first credit sale.</p><p class="unregistered"><strong>Your business does not need a CAC number to start.</strong> Choose “Not registered yet” when you add it. Kredit will tell you clearly when identity, business or bank verification is required before money can move.</p></header>
{#if loading}<p>Opening your setup…</p>{:else if !orgID}<section class="card"><h2>Add your business first</h2><p>Create the business profile, then return here to continue.</p><a href="/app/overview">Go to dashboard →</a></section>{:else}
<section class="activation"><div><p class="eyebrow">Fastest path to value</p><h2>Create one real credit sale.</h2><p>Choose a customer, enter the goods and amount, set the payment day, then let the customer review it. That is enough to experience Kredit’s core workflow.</p></div><div><a class="activation-cta" href="/app/credit/quick">Create my first sale →</a><small>You can complete settlement, billing, limits and extra security before money moves.</small></div></section>
<section class="readiness" class:ready={readiness.ready}><div><p class="eyebrow">Money-readiness</p><h2>{readiness.ready?'Ready for money movement':productLabel(readiness.state,'Finish the steps below')}</h2><p>{readiness.ready?'The required account, consent and safety controls are complete.':`${readiness.missing?.length??0} requirement${(readiness.missing?.length??0)===1?'':'s'} still need attention before all financial actions are available.`}</p></div><strong>{readiness.requirements?.filter((r:any)=>r.complete).length}/{readiness.requirements?.length}</strong></section>
{#if message}<p class="notice" role="status">{message} {#if message.includes('MFA')}<a href="/app/settings/security">Open security</a>{/if}</p>{/if}
<section class="steps" aria-label="Setup progress">{#each readiness.requirements??[] as requirement}<article class:done={requirement.complete}><span>{requirement.complete?'✓':'○'}</span><div><strong>{simpleStep(requirement.code,requirement.label)}</strong>{#if !requirement.complete}<a href={requirement.manage_path}>Complete this →</a>{/if}</div></article>{/each}</section>
<div class="forms">
{#if permissions.business}<section class="card"><p class="step">1 · Business representative</p><h2>Who is responsible for this business?</h2><label>Full name<input bind:value={repName} autocomplete="name" /></label><label>Role in the business<input bind:value={repTitle} placeholder="For example: owner or manager" /></label><button disabled={busy||!repName||!repTitle} onclick={saveRepresentative}>Save representative</button></section>{/if}
{#if permissions.consents}<section class="card"><p class="step">2 · Contact verification</p><h2>Verify your phone or email</h2><div class="row"><label>Channel<select bind:value={channel}><option value="phone">Phone</option><option value="email">Email</option></select></label><label>Email or phone<input bind:value={contact} type={channel==='phone'?'tel':'email'} autocomplete={channel==='phone'?'tel':'email'} placeholder={channel==='phone'?'+234…':'you@business.com'} /></label></div>{#if challengeID}<label>Six-digit code<input bind:value={code} inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" /></label><button disabled={busy||code.length!==6} onclick={verifyContact}>Verify {channel}</button>{:else}<button disabled={busy||!contact} onclick={requestContact}>Send verification code</button>{/if}</section>{/if}
{#if permissions.business}<section class="card"><p class="step">3 · Business verification</p><h2>Verify the business or owner</h2><p>Registered and unregistered businesses can begin here. Kredit may ask for owner details, business papers or another proof depending on the account and financial action. Never share a password or bank PIN.</p>{#if profile.kyb_provider_reference && !['approved','rejected'].includes(profile.kyb_state)}<button disabled={busy} onclick={refreshKYB}>Refresh verification status</button>{:else}<button disabled={busy} onclick={submitKYB}>Start verification</button>{/if}<small>Current status: {productLabel(profile.kyb_state)}</small></section>{/if}
{#if permissions.consents}<section class="card"><p class="step">4 · Terms & privacy</p><h2>Read what you are agreeing to</h2><p>Read the <a href="/legal/terms">terms</a> and <a href="/legal/privacy">privacy notice</a> before accepting them.</p><button disabled={busy||(profile.terms_version===terms&&profile.privacy_version===privacy)} onclick={acceptConsents}>{profile.terms_version===terms&&profile.privacy_version===privacy?'Accepted':'I have read and agree'}</button></section>{/if}
<section class="card links"><p class="step">5 · Money & security</p><h2>Finish the controls needed for financial actions</h2><a href="/app/settings/settlement">Settlement bank account →</a><a href="/app/settings/billing">Kredit fee payment method →</a><a href="/app/settings/credit-policy">Normal sale limits →</a><a href="/app/settings/security">Extra sign-in protection →</a><a href="/app/team">Protect staff who handle money →</a></section>
</div>{/if}</main>
<style>.onboarding header{max-width:58rem}.onboarding h1{max-width:14ch;font-family:Georgia,'Times New Roman',serif;font-size:clamp(3rem,6vw,5.2rem);font-weight:500;line-height:.94;letter-spacing:-.055em}.unregistered{max-width:50rem;padding:1rem;border-left:4px solid #2738d6;background:#eef0ff}.activation{display:grid;grid-template-columns:1fr auto;gap:3rem;align-items:center;margin:2rem 0;padding:1.5rem 1.7rem;color:#fff;background:#2738d6;box-shadow:8px 8px 0 #17181b}.activation h2{margin:.4rem 0;font-family:Georgia,'Times New Roman',serif;font-size:clamp(2rem,4vw,3rem);font-weight:500}.activation p:last-child{max-width:45rem;color:#d8dbff;line-height:1.6}.activation>div:last-child{display:grid;gap:.7rem;max-width:18rem}.activation-cta{display:inline-flex;padding:.85rem 1rem;background:#fff;color:#17181b;font-weight:850;text-decoration:none}.activation small{color:#d8dbff;line-height:1.45}.readiness{display:flex;justify-content:space-between;align-items:center;margin:2rem 0;padding:1.4rem;border:1px solid #e0b54f;background:#fff8e6}.readiness.ready{border-color:var(--color-positive);background:#effbf3}.readiness h2,.readiness p{margin:.2rem 0}.readiness>strong{font-size:2rem}.steps{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem;margin:1.5rem 0}.steps article{display:flex;gap:.7rem;padding:.9rem;border:1px solid var(--color-border);background:#fffdf8}.steps article.done span{color:var(--color-positive)}.steps article div{display:grid;gap:.25rem}.forms{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.card{display:grid;align-content:start;gap:.75rem;padding:1.3rem;border:1px solid var(--color-border);border-radius:0;background:var(--color-surface)}.card h2,.card p{margin:0}.card label{display:grid;gap:.35rem;font-weight:700}.card input,.card select,.card button{box-sizing:border-box;width:100%;padding:.75rem;border:1px solid var(--color-border);border-radius:0;font:inherit}.card button{background:var(--color-primary);color:white;font-weight:800;cursor:pointer}.card button:disabled{opacity:.55}.row{display:grid;grid-template-columns:8rem 1fr;gap:.5rem}.links a{font-weight:750}.step{color:var(--color-primary);font-weight:800}.notice{padding:1rem;background:#eef5ff}@media(max-width:720px){.activation,.steps,.forms{grid-template-columns:1fr}.activation{gap:1rem;box-shadow:6px 6px 0 #17181b}.activation>div:last-child{max-width:none}.row{grid-template-columns:1fr}.readiness>strong{font-size:1.4rem}}</style>