<script lang="ts">
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	import { productLabel } from '$lib/product-language';
	let orgID='', profile:any={}, readiness:any={requirements:[],missing:[]}, permissions:any={}, terms='',privacy='', loading=true,busy=false,message='';
	let repName='',repTitle='',contact='',channel='phone',challengeID='',code='';
	async function load(){loading=true;message='';const orgs=await fetch('/api/v1/organizations',{credentials:'include'});if(orgs.status===401){location.assign('/app');return}const od=await orgs.json();orgID=od.organizations?.[0]?.id??'';if(!orgID){loading=false;return}const r=await fetch(`/api/v1/organizations/${orgID}/onboarding`,{credentials:'include'});const d=await r.json();if(!r.ok){message=d.detail??'Onboarding could not be loaded.';loading=false;return}profile=d.profile;readiness=d.readiness;permissions=d.permissions;terms=d.current_terms_version;privacy=d.current_privacy_version;repName=profile.authorized_representative_name??'';repTitle=profile.authorized_representative_title??'';loading=false}
	async function mutate(path:string,method:string,body:any){busy=true;message='';const r=await fetch(`/api/v1/organizations/${orgID}/onboarding/${path}`,{method,credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));busy=false;if(!r.ok){message=d.detail??'This step could not be saved.';return null}if(d.profile){profile=d.profile;readiness=d.readiness}message='Saved. Your readiness review has been updated.';return d}
	async function saveRepresentative(){await mutate('representative','PATCH',{expected_version:profile.version,name:repName,title:repTitle})}
	async function requestContact(){const d=await mutate('contacts/challenges','POST',{identifier:contact,channel});if(d){challengeID=d.challenge_id;code=d.development_code??'';message='Verification code sent. Enter it below.'}}
	async function verifyContact(){const d=await mutate('contacts/verify','POST',{identifier:contact,channel,challenge_id:challengeID,code});if(d){challengeID='';code='';contact=''}}
	async function submitKYB(){await mutate('kyb','POST',{expected_version:profile.version})}
	async function acceptConsents(){await mutate('consents','POST',{expected_version:profile.version,terms_version:terms,privacy_version:privacy})}
	function simpleStep(code:string,label:string){return ({business_identity:'Who runs the business',email_verified:'Check your email',phone_verified:'Check your phone number',kyb_approved:'Check the business or owner',settlement_verified:'Add the bank account for your money',billing_configured:'Choose how to pay Kredit fees',credit_policy:'Choose your normal sale limits',current_consents:'Accept the rules and privacy notice',owner_mfa:'Add extra sign-in safety',finance_mfa:'Protect every staff member who handles money'} as Record<string,string>)[code]??label}
	onMount(load);
</script>
<svelte:head><title>Supplier onboarding — Kredit</title></svelte:head>
<main class="shell workspace onboarding"><header><p class="eyebrow">Finish setup</p><h1>Get your account ready.</h1><p class="lede">Do each step below. Your work is saved, so you can come back later.</p><p class="unregistered"><strong>Your business does not need a CAC number to start.</strong> Choose “Not registered yet” when you add it. We will tell you clearly if we need an owner’s ID or another document before money can move.</p></header>
{#if loading}<p>Opening your setup…</p>{:else if !orgID}<section class="card"><h2>Add your business first</h2><a href="/app">Go back</a></section>{:else}
<section class="readiness" class:ready={readiness.ready}><div><p class="eyebrow">Your progress</p><h2>{readiness.ready?'Ready to use':productLabel(readiness.state,'Finish the steps below')}</h2><p>{readiness.ready?'You can add sales, confirm goods and receive money.':`${readiness.missing?.length??0} step(s) left.`}</p></div><strong>{readiness.requirements?.filter((r:any)=>r.complete).length}/{readiness.requirements?.length}</strong></section>
{#if message}<p class="notice" role="status">{message} {#if message.includes('MFA')}<a href="/app/settings/security">Open security</a>{/if}</p>{/if}
<section class="steps" aria-label="Setup progress">{#each readiness.requirements??[] as requirement}<article class:done={requirement.complete}><span>{requirement.complete?'✓':'○'}</span><div><strong>{simpleStep(requirement.code,requirement.label)}</strong>{#if !requirement.complete}<a href={requirement.manage_path}>Do this now →</a>{/if}</div></article>{/each}</section>
<div class="forms">
{#if permissions.business}<section class="card"><p class="step">1 · Person in charge</p><h2>Who is responsible for this business?</h2><label>Full name<input bind:value={repName} autocomplete="name" /></label><label>What do they do?<input bind:value={repTitle} placeholder="For example: owner or manager" /></label><button disabled={busy||!repName||!repTitle} onclick={saveRepresentative}>Save this person</button></section>{/if}
{#if permissions.consents}<section class="card"><p class="step">2 · Your phone and email</p><h2>Let us check your contact</h2><div class="row"><label>Choose one<select bind:value={channel}><option value="phone">Phone</option><option value="email">Email</option></select></label><label>Email or phone<input bind:value={contact} type={channel==='phone'?'tel':'email'} autocomplete={channel==='phone'?'tel':'email'} placeholder={channel==='phone'?'+234…':'you@business.com'} /></label></div>{#if challengeID}<label>Six-digit code<input bind:value={code} inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" /></label><button disabled={busy||code.length!==6} onclick={verifyContact}>Check my {channel}</button>{:else}<button disabled={busy||!contact} onclick={requestContact}>Send me a code</button>{/if}</section>{/if}
{#if permissions.business}<section class="card"><p class="step">3 · Business check</p><h2>Check the business or owner</h2><p>Registered and unregistered businesses can start here. We may ask for the owner's details, business papers or another proof. Never share a password or bank PIN.</p><button disabled={busy} onclick={submitKYB}>Start the check</button><small>Now: {productLabel(profile.kyb_state)}</small></section>{/if}
{#if permissions.consents}<section class="card"><p class="step">4 · Kredit rules</p><h2>Read and agree</h2><p>Read the <a href="/legal/terms">terms</a> and <a href="/legal/privacy">privacy notice</a>, then agree to continue.</p><button disabled={busy||(profile.terms_version===terms&&profile.privacy_version===privacy)} onclick={acceptConsents}>{profile.terms_version===terms&&profile.privacy_version===privacy?'You have agreed':'I have read and agree'}</button></section>{/if}
<section class="card links"><p class="step">5 · Money and safety</p><h2>Finish the last steps</h2><a href="/app/settings/settlement">Bank account for your money →</a><a href="/app/settings/billing">How to pay Kredit fees →</a><a href="/app/settings/credit-policy">Your normal sale limits →</a><a href="/app/settings/security">Extra sign-in safety →</a><a href="/app/team">Protect staff who handle money →</a></section>
</div>{/if}</main>
<style>.onboarding header{max-width:55rem}.onboarding h1{font-size:clamp(2.4rem,6vw,4.8rem);line-height:1;letter-spacing:-.05em}.unregistered{max-width:48rem;padding:1rem;border-left:4px solid #2738d6;background:#eef0ff}.readiness{display:flex;justify-content:space-between;align-items:center;margin:2rem 0;padding:1.4rem;border:1px solid #e0b54f;border-radius:1.1rem;background:#fff8e6}.readiness.ready{border-color:var(--color-positive);background:#effbf3}.readiness h2,.readiness p{margin:.2rem 0;text-transform:capitalize}.readiness>strong{font-size:2rem}.steps{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem;margin:1.5rem 0}.steps article{display:flex;gap:.7rem;padding:.9rem;border:1px solid var(--color-border);border-radius:.8rem}.steps article.done span{color:var(--color-positive)}.steps article div{display:grid;gap:.25rem}.forms{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.card{display:grid;align-content:start;gap:.75rem;padding:1.3rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}.card h2,.card p{margin:0}.card label{display:grid;gap:.35rem;font-weight:700}.card input,.card select,.card button{box-sizing:border-box;width:100%;padding:.75rem;border:1px solid var(--color-border);border-radius:.65rem;font:inherit}.card button{background:var(--color-primary);color:white;font-weight:800;cursor:pointer}.card button:disabled{opacity:.55}.row{display:grid;grid-template-columns:8rem 1fr;gap:.5rem}.links a{font-weight:750}.step{color:var(--color-primary);font-weight:800}.notice{padding:1rem;border-radius:.7rem;background:#eef5ff}@media(max-width:720px){.steps,.forms{grid-template-columns:1fr}.row{grid-template-columns:1fr}.readiness>strong{font-size:1.4rem}}</style>
