<script lang="ts">
	import{onMount}from'svelte';import Money from'$lib/components/Money.svelte';
	let organizations=$state<any[]>([]),query=$state(''),loading=$state(true),error=$state('');
	async function load(){loading=true;error='';const r=await fetch(`/api/v1/ops/organizations?q=${encodeURIComponent(query.trim())}`,{credentials:'include'});const d=await r.json().catch(()=>({}));loading=false;if(!r.ok){error=d.detail??'Businesses could not be loaded.';return}organizations=d.organizations??[]}
	onMount(load);
</script>
<svelte:head><title>Businesses — Kredit admin</title></svelte:head>
<main class="shell workspace directory"><header><div><p class="eyebrow">Admin / Businesses</p><h1>Every business on Kredit.</h1><p>Registered and unregistered businesses appear together, with their real account status and money position.</p></div><form onsubmit={(e)=>{e.preventDefault();load()}}><label>Find a business<input type="search" bind:value={query} placeholder="Business name or ID" /></label><button>Search</button></form></header>{#if error}<p class="error">{error}</p>{:else if loading}<p>Loading businesses…</p>{:else}<section>{#each organizations as org}<article><div class="top"><div><small>{org.business_type.replaceAll('_',' ')}</small><h2>{org.trading_name||org.legal_name}</h2>{#if org.trading_name}<p>{org.legal_name}</p>{/if}</div><span class:attention={!['verified','active'].includes(org.status)}>{org.status.replaceAll('_',' ')}</span></div><dl><div><dt>Money owed</dt><dd><Money amountKobo={org.outstanding_kobo}/></dd></div><div><dt>Open sales</dt><dd>{org.open_sales}</dd></div><div><dt>Team members</dt><dd>{org.member_count}</dd></div><div><dt>Industry</dt><dd>{org.industry}</dd></div></dl><footer><code>{org.id}</code><a href={`/admin/controls?target_type=organization&target_id=${org.id}&organization_id=${org.id}&version=${org.version}&status=${org.status}`}>Manage business →</a></footer></article>{/each}</section>{#if !organizations.length}<div class="empty-state"><h2>No business found</h2><p>Try the business name or exact organization ID.</p></div>{/if}{/if}</main>
<style>.directory>header{display:flex;align-items:end;justify-content:space-between;gap:2rem;padding:2rem 0;border-bottom:3px solid #17181b}.directory h1{margin:.4rem 0;font-family:Georgia,serif;font-size:clamp(2.5rem,6vw,4.5rem);font-weight:500;line-height:.95}.directory header p{max-width:40rem}.directory form{display:flex;align-items:end;gap:.5rem;min-width:min(100%,28rem)}label{display:grid;flex:1;gap:.35rem;font-size:.78rem;font-weight:750}input,button{min-height:2.8rem;padding:.6rem .75rem;border:1px solid #17181b;background:#faf8f2;font:inherit}button{background:#2738d6;color:white;font-weight:800}.directory>section{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin-top:2rem}article{display:grid;gap:1.3rem;padding:1.25rem;border:1px solid #bbb6ac;background:#faf8f2}.top{display:flex;justify-content:space-between;gap:1rem}.top small{text-transform:capitalize;color:#66635e}.top h2{margin:.25rem 0;font-family:Georgia,serif;font-size:1.5rem;font-weight:500}.top p{margin:0;color:#66635e}.top>span{align-self:start;padding:.3rem .5rem;background:#e5f4ed;color:#216448;font-size:.7rem;font-weight:850;text-transform:capitalize}.top .attention{background:#fff0e7;color:#9b351f}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));margin:0;border-top:1px solid #d4cfc5;border-left:1px solid #d4cfc5}dl div{padding:.7rem;border-right:1px solid #d4cfc5;border-bottom:1px solid #d4cfc5}dt{color:#66635e;font-size:.7rem}dd{margin:.25rem 0 0;font-weight:800}footer{display:flex;align-items:center;justify-content:space-between;gap:1rem}code{overflow:hidden;color:#77736d;font-size:.68rem;text-overflow:ellipsis}a{color:#2738d6;font-weight:800;white-space:nowrap}@media(max-width:760px){.directory>header{align-items:stretch;flex-direction:column}.directory form{min-width:0}.directory>section{grid-template-columns:1fr}}</style>
