<script lang="ts">
 import {onMount} from 'svelte';
 import {adminPost} from '$lib/admin-client';
 import {loadOnboardingSettings,settingsProfile} from '$lib/api/onboarding-settings';
 import {productLabel} from '$lib/product-language';
 let orgID='',profile:Record<string,unknown>={},permissions:Record<string,unknown>={},message='',loadError='',busy=false,loading=true;
 let method='split_settlement',reference='',cycle='per_settlement';
 async function load(){loading=true;loadError='';try{const result=await loadOnboardingSettings();orgID=result.orgID;profile=result.profile;permissions=result.permissions;method=typeof profile.billing_method==='string'&&profile.billing_method?profile.billing_method:method;cycle=typeof profile.billing_cycle==='string'&&profile.billing_cycle?profile.billing_cycle:cycle;}catch(cause){loadError=cause instanceof Error?cause.message:'We could not load these settings.';}finally{loading=false;}}
 async function save(){if(busy||loading||loadError||!orgID)return;busy=true;message='';try{const result=await adminPost(`/api/v1/organizations/${encodeURIComponent(orgID)}/onboarding/billing`,{expected_version:profile.version,method,provider_reference:reference,cycle},'PUT');profile=settingsProfile(result.profile);message='Saved. That is how you will pay Kredit fees.';}catch(cause){message=cause instanceof Error?cause.message:'We could not confirm this change.';}finally{busy=false;}}
 onMount(load);
</script>
<svelte:head><title>Kredit fees — Kredit</title></svelte:head><main class="shell workspace form-page"><p class="eyebrow">Settings / Kredit fees</p><h1>How should Kredit take its fee?</h1><p class="lede">Choose whatever is easiest for your business. You will always see the fee before any money moves.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}{#if loading}<p role="status">Loading your settings…</p>{:else if loadError}<p class="error" role="alert">{loadError}</p><button onclick={load}>Try again</button>{:else}<section class="card"><header><h2>Paying Kredit</h2><span>{productLabel(profile.billing_state,'Not started')}</span></header>{#if permissions.billing}<label>How should we take our fee?<select disabled={busy} bind:value={method}><option value="split_settlement">Take it out of customer payments as they come in</option><option value="authorized_debit">Debit it from my business bank account</option><option value="consolidated_invoice">Send me one bill</option></select></label><label>Payment setup number<input disabled={busy} bind:value={reference} autocomplete="off" /><small>Your payment company gives you this number.</small></label><label>How often?<select disabled={busy} bind:value={cycle}><option value="per_settlement">After each payment</option><option value="weekly">Once a week</option><option value="monthly">Once a month</option></select></label><aside><strong>What Kredit charges</strong><p>You pay the base fee on each sale once it starts. You only pay the collection fee on money Kredit actually collects for you. If a debit fails, you pay nothing extra. <a href="/pricing">See today’s rates</a>.</p></aside><button disabled={busy||!reference} onclick={save}>{busy?'Saving…':'Save how I will pay'}</button>{:else}<p>You can look at this, but only the owner or somebody allowed to handle money can change it.</p>{/if}</section>{/if}<a href="/app/settings">← All settings</a></main>
<style>.form-page{max-width:52rem}.form-page h1{font-size:clamp(2.4rem,6vw,4.5rem);line-height:1}.card{display:grid;gap:.8rem;padding:1.4rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}header{display:flex;justify-content:space-between}.card label{display:grid;gap:.3rem;font-weight:700}.card input,.card select,.card button{padding:.75rem;border:1px solid var(--color-border);border-radius:.65rem;font:inherit}.card button{background:var(--color-primary);color:white;font-weight:800}aside,.notice{padding:1rem;background:#eef5ff;border-radius:.7rem}aside p{margin:.3rem 0}</style>
