<script lang="ts">
 import {onMount} from 'svelte';
 import {adminPost} from '$lib/admin-client';
 import {loadOnboardingSettings,settingsProfile} from '$lib/api/onboarding-settings';
 import VerifyIdentity from '$lib/components/VerifyIdentity.svelte';
 import FeeAuthorization from '$lib/components/FeeAuthorization.svelte';
 import FeeOperations from '$lib/components/FeeOperations.svelte';
 import FeeInvoices from '$lib/components/FeeInvoices.svelte';
 import {productLabel} from '$lib/product-language';
 let organizationName='',orgID='',profile:Record<string,unknown>={},permissions:Record<string,unknown>={},message='',loadError='',busy=false,loading=true;
 let method='split_settlement',reference='',cycle='per_settlement';
 async function load(){loading=true;loadError='';try{const result=await loadOnboardingSettings(orgID || new URLSearchParams(location.search).get('organization'));orgID=result.orgID;organizationName=result.organizationName;profile=result.profile;permissions=result.permissions;method=typeof profile.billing_method==='string'&&profile.billing_method?profile.billing_method:method;reference=typeof profile.billing_provider_reference==='string'?profile.billing_provider_reference:'';cycle=typeof profile.billing_cycle==='string'&&profile.billing_cycle?profile.billing_cycle:cycle;}catch(cause){loadError=cause instanceof Error?cause.message:'We could not load these settings.';}finally{loading=false;}}
 async function save(){if(busy||loading||loadError||!orgID)return;busy=true;message='';try{const result=await adminPost(`/api/v1/organizations/${encodeURIComponent(orgID)}/onboarding/billing`,{expected_version:profile.version,method,provider_reference:reference,cycle},'PUT');profile=settingsProfile(result.profile);message='Preference saved. Kredit will review the arrangement before it becomes active.';}catch(cause){message=cause instanceof Error?cause.message:'We could not confirm this change.';}finally{busy=false;}}
 onMount(load);
</script>
<svelte:head><title>Kredit fees — Kredit</title></svelte:head><main class="shell workspace form-page"><p class="eyebrow">Settings / Kredit fees</p><h1>How should Kredit take its fee?</h1><p class="lede">Save your preferred arrangement. Kredit must verify the payment setup before it becomes active.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}{#if loading}<p role="status">Loading your settings…</p>{:else if loadError}<p class="error" role="alert">{loadError}</p><button onclick={load}>Try again</button>{:else}<p class="business-name">Business: {organizationName}</p><VerifyIdentity /><section class="card"><header><h2>Paying Kredit</h2><span>{productLabel(profile.billing_state,'Not started')}</span></header>{#if permissions.billing}<label>How should we take our fee?<select disabled={busy} bind:value={method} onchange={()=>cycle=method==='split_settlement'?'per_settlement':'monthly'}><option value="split_settlement">Take it out of customer payments as they come in</option><option value="authorized_debit">Debit it from my business bank account</option><option value="consolidated_invoice">Send me one bill</option></select></label>{#if method==='authorized_debit'}<FeeAuthorization org={orgID} onselect={id=>reference=id} /><p>Selected fee permission: {reference||'Choose a saved permission above.'}</p>{/if}<label>How often?<select disabled={busy} bind:value={cycle}>{#if method==='split_settlement'}<option value="per_settlement">After each payment</option>{:else}<option value="weekly">Once a week</option><option value="monthly">Once a month</option>{/if}</select></label>{#if method==='consolidated_invoice'}<p>Weekly bills close on Monday; monthly bills close on the first day of the month. Each bill is due seven days after it is issued.</p>{/if}{#if method==='split_settlement'}<p>We deduct the accepted fees from customer collections. Any fees still unpaid at month-end are billed separately, due seven days after issue. Fees already deducted are credited on the bill.</p>{/if}<aside><strong>What Kredit charges</strong><p>You pay the base fee on each sale once it starts. You only pay the collection fee on money Kredit actually collects for you. If a debit fails, you pay nothing extra. <a href="/pricing">See today’s rates</a>.</p></aside><button disabled={busy||(method==='authorized_debit'&&!reference)} onclick={save}>{busy?'Saving…':'Save how I will pay'}</button>{:else}<p>You can look at this, but only the owner or somebody allowed to handle money can change it.</p>{/if}</section><FeeOperations org={orgID} /><FeeInvoices url={`/api/v1/organizations/${encodeURIComponent(orgID)}/fee-invoices`} />{/if}<a href="/app/settings">← All settings</a></main>
<style>.form-page{max-width:52rem}.form-page h1{font-size:clamp(2.4rem,6vw,4.5rem);line-height:1}.card{display:grid;gap:.8rem;padding:1.4rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}header{display:flex;justify-content:space-between}.card label{display:grid;gap:.3rem;font-weight:700}.card select,.card button{padding:.75rem;border:1px solid var(--color-border);border-radius:.65rem;font:inherit}.card button{background:var(--color-primary);color:white;font-weight:800}aside,.notice{padding:1rem;background:#eef5ff;border-radius:.7rem}aside p{margin:.3rem 0}</style>
