<script lang="ts">
	import{onMount}from'svelte';
	let users=$state<any[]>([]),query=$state(''),loading=$state(true),error=$state('');
	async function load(){loading=true;error='';const r=await fetch(`/api/v1/ops/users?q=${encodeURIComponent(query.trim())}`,{credentials:'include'});const d=await r.json().catch(()=>({}));loading=false;if(!r.ok){error=d.detail??'Users could not be loaded.';return}users=d.users??[]}
	onMount(load);
</script>
<svelte:head><title>Users — Kredit admin</title></svelte:head>
<main class="shell workspace admin-page"><header><div><p class="eyebrow">Admin / Users</p><h1>Every Kredit user.</h1><p>Find an account, understand its status and use protected controls when necessary.</p></div><form onsubmit={(e)=>{e.preventDefault();load()}}><label>Find a user<input type="search" bind:value={query} placeholder="Name, email, phone or user ID" /></label><button>Search</button></form></header>{#if error}<p class="error" role="alert">{error}</p>{:else if loading}<p role="status">Loading users…</p>{:else}<div class="table-wrap"><table><caption>{users.length} user{users.length===1?'':'s'} shown</caption><thead><tr><th>User</th><th>Status</th><th>Businesses</th><th>Last sign-in</th><th></th></tr></thead><tbody>{#each users as user}<tr><td><strong>{user.display_name}</strong><small>{user.identifier}</small><code>{user.id}</code></td><td><span class:bad={user.status!=='active'}>{user.status}</span></td><td>{user.organization_count}</td><td>{user.last_authenticated_at?new Date(user.last_authenticated_at).toLocaleString('en-NG'):'Never'}</td><td><a href={`/admin/controls?target_type=user&target_id=${user.id}&status=${user.status}`}>Manage →</a></td></tr>{/each}</tbody></table></div>{#if !users.length}<section class="empty-state"><h2>No user found</h2><p>Check the spelling or use the exact email, phone number or user ID.</p></section>{/if}{/if}</main>
<style>.admin-page>header{display:flex;align-items:end;justify-content:space-between;gap:2rem;padding:2rem 0;border-bottom:3px solid #17181b}.admin-page h1{margin:.4rem 0;font-family:Georgia,serif;font-size:clamp(2.5rem,6vw,4.5rem);font-weight:500;line-height:.95}.admin-page header p{max-width:38rem}.admin-page form{display:flex;align-items:end;gap:.5rem;min-width:min(100%,28rem)}label{display:grid;flex:1;gap:.35rem;font-size:.78rem;font-weight:750}input,button{min-height:2.8rem;padding:.6rem .75rem;border:1px solid #17181b;background:#faf8f2;font:inherit}button{background:#2738d6;color:white;font-weight:800}.table-wrap{overflow-x:auto;margin-top:2rem}table{width:100%;border-collapse:collapse;background:#faf8f2}caption{text-align:left;padding:.75rem 0;font-weight:800}th,td{padding:1rem;text-align:left;border-bottom:1px solid #cdc8be;vertical-align:top}td strong,td small,td code{display:block}td small,td code{margin-top:.3rem;color:#66635e;font-size:.76rem}td span{padding:.25rem .45rem;background:#e5f4ed;color:#216448;font-size:.7rem;font-weight:800;text-transform:capitalize}.bad{background:#fff0e7!important;color:#9b351f!important}td a{color:#2738d6;font-weight:800;white-space:nowrap}@media(max-width:760px){.admin-page>header{align-items:stretch;flex-direction:column}.admin-page form{min-width:0}}</style>
