<script lang="ts">
 import {onMount} from 'svelte';
 import {adminPost} from '$lib/admin-client';
 import {loadOnboardingSettings,settingsProfile} from '$lib/api/onboarding-settings';
 import {parseNaira} from '$lib/money';
 let organizationName='',orgID='',profile:Record<string,unknown>={},permissions:Record<string,unknown>={},message='',loadError='',busy=false,loading=true;
 let limitNaira=5000000,days=30,grace=48;
 async function load(){loading=true;loadError='';try{const result=await loadOnboardingSettings(orgID || new URLSearchParams(location.search).get('organization'));orgID=result.orgID;organizationName=result.organizationName;profile=result.profile;permissions=result.permissions;if(typeof profile.default_credit_limit_kobo==='number')limitNaira=profile.default_credit_limit_kobo/100;if(typeof profile.default_payment_days==='number')days=profile.default_payment_days;if(typeof profile.default_grace_hours==='number')grace=profile.default_grace_hours;}catch(cause){loadError=cause instanceof Error?cause.message:'We could not load these settings.';}finally{loading=false;}}
 async function save(){if(busy||loading||loadError||!orgID)return;busy=true;message='';try{const result=await adminPost(`/api/v1/organizations/${encodeURIComponent(orgID)}/onboarding/credit-policy`,{expected_version:profile.version,credit_limit_kobo:parseNaira(limitNaira),payment_days:Number(days),grace_hours:Number(grace)},'PUT');profile=settingsProfile(result.profile);message='Saved. We will use these on your next sale.';}catch(cause){message=cause instanceof Error?cause.message:'We could not confirm this change.';}finally{busy=false;}}
 onMount(load);
</script>
<svelte:head><title>Normal sale settings — Kredit</title></svelte:head><main class="shell workspace form-page"><p class="eyebrow">Settings / Normal sales</p><h1>Set what we fill in for a new sale.</h1><p class="lede">We put these in automatically each time you add a sale, so you type less. You can still change them for any customer.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}{#if loading}<p role="status">Loading your settings…</p>{:else if loadError}<p class="error" role="alert">{loadError}</p><button onclick={load}>Try again</button>{:else}<p class="business-name">Business: {organizationName}</p><section class="card">{#if permissions.credit_policy}<label>Most one customer should owe you at once (₦)<input disabled={busy} type="number" min="1" bind:value={limitNaira} /></label><label>How many days you normally give<input disabled={busy} type="number" min="1" max="365" bind:value={days} /></label><label>Extra hours you normally give after that<input disabled={busy} type="number" min="0" max="720" bind:value={grace} /></label><button disabled={busy||limitNaira<=0} onclick={save}>{busy?'Saving…':'Save these choices'}</button>{:else}<p>You can look at these, but only the owner or an allowed worker can change them.</p>{/if}</section>{/if}<a href="/app/onboarding">← Back to account setup</a></main>
<style>.form-page{max-width:52rem}.form-page h1{font-size:clamp(2.4rem,6vw,4.5rem);line-height:1}.card{display:grid;gap:.8rem;padding:1.4rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}.card label{display:grid;gap:.3rem;font-weight:700}.card input,.card button{padding:.75rem;border:1px solid var(--color-border);border-radius:.65rem;font:inherit}.card button{background:var(--color-primary);color:white;font-weight:800}.notice{padding:1rem;background:#eef5ff;border-radius:.7rem}</style>
