<script lang="ts">
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	let organizations:any[]=$state([]),organizationID=$state(''),targetType=$state('email'),target=$state(''),legalName=$state(''),tradingName=$state(''),businessType=$state('unregistered_business'),address=$state(''),industry=$state(''),busy=$state(false),error=$state(''),invitationURL=$state(''),copied=$state(false);
	onMount(async()=>{const response=await fetch('/api/v1/organizations',{credentials:'include'});if(response.status===401){location.assign('/app');return}if(response.ok){organizations=(await response.json()).organizations??[];organizationID=organizations[0]?.id??'';}});
	async function submit(event:SubmitEvent){event.preventDefault();busy=true;error='';invitationURL='';const response=await fetch(`/api/v1/organizations/${organizationID}/buyer-invitations`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({target,target_type:targetType,legal_name:legalName,trading_name:tradingName,business_type:businessType,business_address:address,industry})});const result=await response.json().catch(()=>({}));busy=false;if(!response.ok){error=result.detail??'The invitation could not be created.';return}invitationURL=result.invitation_url;}
	async function copy(){await navigator.clipboard.writeText(invitationURL);copied=true;setTimeout(()=>copied=false,1800)}
</script>
<svelte:head><title>Invite a customer — Kredit</title></svelte:head>
<main class="shell workspace invite"><a href="/app/customers">← Customers</a><p class="eyebrow">Add a customer</p><h1>Who will take the goods?</h1><p class="lede">Add the customer, then send them a private link. They will check their details and say yes.</p>
{#if error}<p class="error" role="alert">{error}</p>{/if}
{#if invitationURL}<section class="card result" aria-live="polite"><h2>The link is ready</h2><p>Send this private link to your customer. It works once and will expire.</p><input value={invitationURL} readonly aria-label="Customer link"/><button class="primary" onclick={copy}>{copied?'Copied':'Copy the link'}</button><a href="/app/customers">Back to customers</a></section>{:else}
<form class="card" onsubmit={submit}><div class="grid"><label>Your business<select bind:value={organizationID} required>{#each organizations as organization}<option value={organization.id}>{organization.trading_name||organization.legal_name}</option>{/each}</select></label><label>Send link by<select bind:value={targetType}><option value="email">Email</option><option value="phone">Phone</option></select></label><label>Customer's {targetType==='email'?'email':'phone number'}<input bind:value={target} type={targetType==='email'?'email':'tel'} required autocomplete="off"/></label><label>Customer or business name<input bind:value={legalName} required/></label><label>Shop name <small>if different</small><input bind:value={tradingName}/></label><label>Business type<select bind:value={businessType}><option value="unregistered_business">Not registered yet</option><option value="registered_business">Business name registered with CAC</option><option value="sole_proprietor">One-person business</option><option value="limited_company">Limited company</option><option value="partnership">Partnership</option></select></label><label>What do they sell?<input bind:value={industry} required/></label><label class="wide">Where is the business?<textarea bind:value={address} rows="3" required></textarea></label></div><button class="primary" disabled={busy||!organizationID}>{busy?'Making the link…':'Make customer link'}</button></form>{/if}</main>
<style>.invite{max-width:52rem}.invite h1{font-size:clamp(2.7rem,6vw,4.5rem);line-height:1;margin:.5rem 0}.card{margin-top:2rem;padding:2rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin-bottom:1.3rem}.grid label{display:grid;gap:.4rem;font-weight:700}.grid input,.grid select,.grid textarea,.result input{box-sizing:border-box;width:100%;padding:.75rem;border:1px solid var(--color-border);border-radius:.7rem;font:inherit}.wide{grid-column:span 2}.result{display:grid;gap:1rem}.result .primary{width:max-content}@media(max-width:680px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.card{padding:1.2rem}}</style>
