<script lang="ts">
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	let p:any={preferred_channel:'whatsapp',fallback_channel:'email',payment_reminders_enabled:true,product_updates_enabled:false,quiet_start_hour:22,quiet_end_hour:7,timezone:'Africa/Lagos',version:1};
	let message='',busy=false,loading=true;
	async function load(){const r=await fetch('/api/v1/me/notification-preferences',{credentials:'include'});if(r.ok)p=(await r.json()).preferences;loading=false}
	async function save(){busy=true;message='';const r=await fetch('/api/v1/me/notification-preferences',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({...p,expected_version:p.version})});const d=await r.json().catch(()=>({}));busy=false;if(r.ok){p=d.preferences;message='Preferences saved. Future optional messages will follow these choices.'}else message=d.detail??'Preferences could not be saved.'}
	onMount(load);
</script>
<svelte:head><title>Notification preferences — Kredit</title></svelte:head>
<main class="shell workspace settings"><p class="eyebrow">Settings / Notifications</p><h1>Choose how Kredit reaches you.</h1><p class="lede">Payment reminders and product news are optional. Security alerts and financial receipts remain on to protect your account and records.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}<section><h2>Delivery</h2><label>Preferred channel<select disabled={loading} bind:value={p.preferred_channel}><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Fallback channel<select disabled={loading} bind:value={p.fallback_channel}><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></label><div class="hours"><label>Quiet time starts<input disabled={loading} type="number" min="0" max="23" bind:value={p.quiet_start_hour}/></label><label>Quiet time ends<input disabled={loading} type="number" min="0" max="23" bind:value={p.quiet_end_hour}/></label></div><p>Times use Africa/Lagos. Urgent security and transactional messages are delivered during quiet hours.</p></section><section><h2>Optional messages</h2><label class="check"><input disabled={loading} type="checkbox" bind:checked={p.payment_reminders_enabled}/> Payment reminders</label><label class="check"><input disabled={loading} type="checkbox" bind:checked={p.product_updates_enabled}/> Product updates</label></section><button onclick={save} disabled={loading||busy||p.preferred_channel===p.fallback_channel}>{busy?'Saving…':'Save preferences'}</button></main>
<style>.settings{max-width:48rem}.settings h1{font-size:clamp(2.4rem,6vw,4.5rem);line-height:1}.settings section{display:grid;gap:.8rem;margin:1rem 0;padding:1.3rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}label{display:grid;gap:.35rem;font-weight:700}select,input,button{padding:.75rem;border:1px solid var(--color-border);border-radius:.65rem;font:inherit}.hours{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.check{display:flex;align-items:center}.check input{width:1.2rem;height:1.2rem}button{background:var(--color-primary);color:white;font-weight:800}.notice{padding:1rem;background:#eef5ff;border-radius:.7rem}@media(max-width:560px){.hours{grid-template-columns:1fr}}</style>
