<script lang="ts">
	import{onMount}from'svelte';import{csrfHeaders,idempotencyKey}from'$lib/api/client';import ProtectedActionDialog from'$lib/components/ProtectedActionDialog.svelte';
	let items=$state<any[]>([]),selected=$state<any>(null),decision=$state(''),message=$state(''),dialogOpen=$state(false),loading=$state(true);
	async function load(){loading=true;const response=await fetch('/api/v1/ops/privacy-requests',{credentials:'include'});items=response.ok?(await response.json()).requests??[]:[];loading=false}
	function begin(item:any,nextDecision:string){selected=item;decision=nextDecision;dialogOpen=true}
	async function confirm(reason:string){const response=await fetch(`/api/v1/ops/privacy-requests/${selected.id}/decide`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({decision,reason,expected_version:selected.version})});const body=await response.json().catch(()=>({}));message=response.ok?'Decision recorded. A different reviewer must complete destructive work.':body.detail??'Decision failed.';if(response.ok)await load();return response.ok}
	onMount(load);
</script>
<svelte:head><title>Privacy review — Kredit</title></svelte:head>
<main class="shell workspace"><p class="eyebrow">Operations / Privacy</p><h1>Privacy request queue.</h1><p class="lede">Legal holds preserve required financial records. Destructive completion needs a different reviewer.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}{#if loading}<p role="status">Loading privacy requests…</p>{:else}{#each items as item}<article><header><strong>{item.request_type}</strong><span class="status">{item.state}</span></header><p>Due {new Date(item.due_at).toLocaleDateString('en-NG')} · {item.details}</p><div class="actions"><button onclick={()=>begin(item,'APPROVED')}>Approve</button><button onclick={()=>begin(item,'CLARIFICATION_REQUIRED')}>Ask for clarification</button><button class="danger" onclick={()=>begin(item,'REJECTED')}>Reject</button></div></article>{:else}<section class="empty-state"><h2>No requests awaiting review</h2><p>New identity-verified privacy requests will appear here.</p></section>{/each}{/if}</main>
{#if selected}<ProtectedActionDialog bind:open={dialogOpen} title={`${decision.replaceAll('_',' ').toLowerCase()} privacy request`} description="Record the precise legal or compliance basis. This decision is audited and may require a separate completion reviewer." confirmLabel="Record decision" onconfirm={confirm}/>{/if}
<style>article{margin:1rem 0;padding:1rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}header{display:flex;justify-content:space-between;gap:1rem}.actions{display:flex;flex-wrap:wrap;gap:.5rem}.actions button{padding:.65rem .85rem;border:1px solid var(--color-border);border-radius:.6rem;background:var(--color-surface);color:var(--color-foreground);font:inherit;font-weight:700;cursor:pointer}.actions .danger{color:var(--color-destructive)}</style>
