<script lang="ts">
	import{onMount}from'svelte';import{csrfHeaders,idempotencyKey}from'$lib/api/client';import ProtectedActionDialog from'$lib/components/ProtectedActionDialog.svelte';
	let items=$state<any[]>([]),selected=$state<any>(null),decision=$state(''),message=$state(''),dialogOpen=$state(false),loading=$state(true);
	async function load(){loading=true;const response=await fetch('/api/v1/ops/privacy-requests',{credentials:'include'});items=response.ok?(await response.json()).requests??[]:[];loading=false}
	function begin(item:any,nextDecision:string){selected=item;decision=nextDecision;dialogOpen=true}
	async function confirm(reason:string){const completing=decision==='COMPLETE';const response=await fetch(`/api/v1/ops/privacy-requests/${selected.id}/${completing?'complete':'decide'}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify(completing?{decision_reviewer_id:selected.decided_by,expected_version:selected.version}:{decision,reason,expected_version:selected.version})});const body=await response.json().catch(()=>({}));message=response.ok?(completing?'Request completed. The customer can now see the result.':'Decision recorded. A different reviewer must complete the request.'):body.detail??'The action failed.';if(response.ok)await load();return response.ok}
	onMount(load);
</script>
<svelte:head><title>Privacy review — Kredit</title></svelte:head>
<main class="shell workspace"><p class="eyebrow">Operations / Privacy</p><h1>Privacy request queue.</h1><p class="lede">Keep required financial records. A different reviewer must finish an approved request.</p>{#if message}<p class="notice" role="status">{message}</p>{/if}{#if loading}<p role="status">Loading privacy requests…</p>{:else}{#each items as item}<article><header><strong>{item.request_type}</strong><span class="status">{item.state}</span></header><p>Due {new Date(item.due_at).toLocaleDateString('en-NG')} · {item.details}</p><div class="actions">{#if item.state==='APPROVED'||item.state==='PARTIALLY_APPROVED'}<button onclick={()=>begin(item,'COMPLETE')}>Finish this request</button>{:else if item.state!=='COMPLETED'}<button onclick={()=>begin(item,'APPROVED')}>Approve</button><button onclick={()=>begin(item,'CLARIFICATION_REQUIRED')}>Ask for more information</button><button class="danger" onclick={()=>begin(item,'REJECTED')}>Reject</button>{/if}</div></article>{:else}<section class="empty-state"><h2>No privacy requests</h2><p>New information requests will appear here.</p></section>{/each}{/if}</main>
{#if selected}<ProtectedActionDialog bind:open={dialogOpen} title={decision==='COMPLETE'?'Finish privacy request':`${decision.replaceAll('_',' ').toLowerCase()} privacy request`} description={decision==='COMPLETE'?'You must be a different reviewer from the person who approved it. This action is recorded.':'Write the clear reason for this decision. A different reviewer must finish an approved request.'} confirmLabel={decision==='COMPLETE'?'Finish request':'Record decision'} onconfirm={confirm}/>{/if}
<style>article{margin:1rem 0;padding:1rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}header{display:flex;justify-content:space-between;gap:1rem}.actions{display:flex;flex-wrap:wrap;gap:.5rem}.actions button{padding:.65rem .85rem;border:1px solid var(--color-border);border-radius:.6rem;background:var(--color-surface);color:var(--color-foreground);font:inherit;font-weight:700;cursor:pointer}.actions .danger{color:var(--color-destructive)}</style>
