<script lang="ts">
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	import { productLabel } from '$lib/product-language';
	let organizations:any[]=$state([]),organizationID=$state(''),cases:any[]=$state([]),message=$state(''),notice=$state(''),error=$state(''),busy=$state(false);
	async function loadCases(){if(!organizationID)return;const response=await fetch(`/api/v1/organizations/${organizationID}/support-cases`,{credentials:'include'});if(response.ok)cases=(await response.json()).cases??[];}
	async function send(event:SubmitEvent){event.preventDefault();busy=true;error='';notice='';const response=await fetch(`/api/v1/organizations/${organizationID}/support-cases`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({subject_type:'business_account',subject_id:organizationID,message})});const result=await response.json().catch(()=>({}));busy=false;if(!response.ok){error=result.detail??'We could not send your message.';return}message='';notice=`Your message was sent. Help number: ${result.case.id}`;await loadCases()}
	async function updateCase(item:any,state:string){busy=true;error='';notice='';const response=await fetch(`/api/v1/organizations/${organizationID}/support-cases/${item.id}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({state,note:state==='RESOLVED'?'Customer says the problem is solved.':'Customer closed this help request.'})});const data=await response.json().catch(()=>({}));busy=false;if(!response.ok){error=data.detail??'We could not update this help request.';return}notice=state==='RESOLVED'?'Marked as solved. You can close it after checking everything.':'Help request closed.';await loadCases()}
	onMount(async()=>{const response=await fetch('/api/v1/organizations',{credentials:'include'});if(response.ok){organizations=(await response.json()).organizations??[];organizationID=organizations[0]?.id??'';await loadCases();}});
</script>
<svelte:head><title>Get help — Kredit</title></svelte:head>
<main class="shell workspace help"><p class="eyebrow">Get help</p><h1>Talk to a real person.</h1><p class="lede">Tell us what happened in simple words. A support person can check your Kredit records and reply safely.</p>
{#if notice}<p class="notice" role="status">{notice}</p>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}
<section class="card"><h2>Send a message</h2>{#if organizations.length>1}<label>Business<select bind:value={organizationID} onchange={loadCases}>{#each organizations as organization}<option value={organization.id}>{organization.trading_name||organization.legal_name}</option>{/each}</select></label>{/if}<form onsubmit={send}><label>What do you need help with?<textarea bind:value={message} maxlength="2000" rows="6" placeholder="For example: My customer paid, but I cannot see the payment." required></textarea></label><button class="primary" disabled={busy||!organizationID||message.trim().length<5}>{busy?'Sending…':'Send to support'}</button></form><p><small>Never send your password, verification code, bank PIN or full card number.</small></p></section>
<section class="card"><h2>Your help requests</h2>{#if cases.length}<div class="cases">{#each cases as item}<article><strong>Help number {item.id}</strong><span>{productLabel(item.state)}</span><small>Sent {new Date(item.created_at).toLocaleDateString('en-NG')}</small>{#if item.state==='RESOLVED'}<button disabled={busy} onclick={()=>updateCase(item,'CLOSED')}>Close this request</button>{:else if item.state!=='CLOSED'}<button disabled={busy} onclick={()=>updateCase(item,'RESOLVED')}>My problem is solved</button>{/if}</article>{/each}</div>{:else}<p>You have not asked for help yet.</p>{/if}</section>
<p><a href="/legal/complaints">Make a formal complaint →</a></p></main>
<style>.help{max-width:54rem}.help h1{font-family:Georgia,'Times New Roman',serif;font-size:clamp(3rem,7vw,5rem);line-height:.95}.card,form,label,.cases{display:grid;gap:.75rem}textarea,select{box-sizing:border-box;width:100%;padding:.8rem;border:1px solid var(--color-border);font:inherit}.cases article{display:grid;grid-template-columns:1fr auto;gap:.35rem;padding:.9rem 0;border-bottom:1px solid var(--color-border)}.cases small{grid-column:1/-1}.cases button{grid-column:1/-1;width:max-content;padding:.55rem .7rem;border:1px solid var(--color-border);background:var(--color-surface);font:inherit;font-weight:750}.notice{padding:1rem;border-left:4px solid var(--color-positive);background:#eef8f2}.error{color:var(--color-destructive)}</style>
