<script lang="ts">
 import VerifyIdentity from '$lib/components/VerifyIdentity.svelte';
 import {onMount} from 'svelte';import {adminGet,adminPost,localTime,localInput,lagosISO} from '$lib/admin-client';
 let items:any[]=$state([]),actor=$state(''),q=$state(''),offset=$state(0),more=$state(false),busy=$state(false),error=$state(''),message=$state('');let selected:any=$state(null),due=$state(''),reason=$state('');
 async function load(){busy=true;error='';try{const b=await adminGet(`/api/v1/ops/approval-inbox?q=${encodeURIComponent(q)}&offset=${offset}`);more=b.items.length>200;items=b.items.slice(0,200);actor=b.actor_id}catch(e){error=String(e)}finally{busy=false}}
 async function assign(clear=false){busy=true;error='';try{await adminPost('/api/v1/ops/review-assignments',{kind:selected.kind,id:selected.id,owner_id:clear?'':actor,due_at:lagosISO(due),reason});selected=null;reason='';message='Ownership and deadline recorded.';await load()}catch(e){error=String(e)}finally{busy=false}}
 onMount(load);
</script>
<svelte:head><title>Approval inbox — Kredit</title></svelte:head>
<main class="shell workspace"><h1>Approval inbox</h1><VerifyIdentity/><p>Policy changes, financial corrections, disputes, recovery and privacy reviews, with one place to track ownership and deadlines. Only work allowed by your role appears.</p><form onsubmit={(e)=>{e.preventDefault();offset=0;load()}}><label>Search reviews<input bind:value={q} type="search"/></label><button disabled={busy}>Search</button></form>{#if error}<p role="alert">{error}</p>{/if}{#if message}<p role="status">{message}</p>{/if}
 {#each items as item}<article><h2><a href={item.href}>{item.title}</a></h2><p>{item.kind.replaceAll('_',' ')} · {item.state.replaceAll('_',' ')} · Proposed by {item.author}</p><p><strong>{item.owner||'Unassigned'}</strong> · Due {localTime(item.due_at)} {new Date(item.due_at)<new Date()?'— overdue':''}</p><a href={item.href}>Review and decide →</a> <button disabled={busy} onclick={()=>{selected=item;due=localInput(item.due_at);reason=''}}>Manage ownership and deadline</button></article>{:else}{#if !busy}<p>No matching reviews.</p>{/if}{/each}
 <button disabled={busy||offset===0} onclick={()=>{offset=Math.max(0,offset-200);load()}}>Previous</button><button disabled={busy||!more} onclick={()=>{offset+=200;load()}}>Next</button>
 {#if selected}<section><h2>Manage review</h2><p>{selected.title}</p><form onsubmit={(e)=>{e.preventDefault();assign()}}><label>Review deadline (Lagos)<input type="datetime-local" bind:value={due} required/></label><label>Reason<textarea bind:value={reason} required minlength="8" maxlength="2000"></textarea></label><button disabled={busy}>Assign to me and save deadline</button><button type="button" disabled={busy||reason.trim().length<8} onclick={()=>assign(true)}>Return to unassigned</button><button type="button" onclick={()=>selected=null}>Close</button></form></section>{/if}
</main>
<style>article,section{padding:1.2rem;border:1px solid #bbb6ac;margin:1rem 0;background:#fffdf6}h2{font-size:1.25rem}label{display:block;margin:.8rem 0}input,textarea{display:block;padding:.6rem;max-width:100%;width:28rem}button{padding:.6rem;margin:.5rem .5rem .5rem 0}a{color:#2635ae}p{overflow-wrap:anywhere}</style>
