<script lang="ts">
	import { onMount } from 'svelte'; import { page } from '$app/state';
	import { productLabel } from '$lib/product-language';
	let data:any=$state(null);let error=$state('');
	onMount(async()=>{const response=await fetch(`/api/v1/buyer/obligations/${page.params.id}`,{credentials:'include'});const result=await response.json().catch(()=>({}));if(response.ok)data=result;else error=result.detail??'We could not open this sale.'});
	const money=(value:number)=>`₦${(Number(value||0)/100).toLocaleString('en-NG',{minimumFractionDigits:2})}`;
</script>
<svelte:head><title>Money you owe — Kredit</title></svelte:head>
<main class="shell workspace"><p class="eyebrow">Money I owe</p>{#if data}<h1>{data.view.request.goods_description}</h1><section class="summary"><article><span>Money left</span><strong>{money(data.view.obligation.outstanding_kobo)}</strong></article><article><span>Now</span><strong>{productLabel(data.view.obligation.payment_status)}</strong></article><article><span>Pay before</span><strong>{new Date(data.view.request.due_date).toLocaleDateString('en-NG')}</strong></article></section><h2>When to pay</h2>{#if data.schedule_items.length}<div class="table"><table><thead><tr><th>Pay before</th><th>Money to pay</th><th>Money paid</th><th>Now</th></tr></thead><tbody>{#each data.schedule_items as item}<tr><td>{new Date(item.due_at).toLocaleDateString('en-NG')}</td><td>{money(item.principal_due_kobo)}</td><td>{money(item.allocated_kobo)}</td><td>{productLabel(item.state)}</td></tr>{/each}</tbody></table></div>{:else}<p>You will pay once.</p>{/if}<h2>Your payments</h2><p>{data.payments.length} {data.payments.length===1?'payment':'payments'} saved. {data.payment_claims.length} waiting for the seller to check.</p><a href={`/buyer/credit-requests/${data.view.request.id}`}>Pay or tell us about a problem →</a>{:else if error}<h1>We could not open this sale.</h1><p role="alert">{error}</p>{:else}<p>Opening your sale…</p>{/if}</main>
<style>.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.summary article{display:grid;gap:.5rem;padding:1rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}.summary span,th{color:var(--color-muted)}.table{overflow-x:auto}table{width:100%;border-collapse:collapse;background:var(--color-surface)}th,td{padding:.8rem;text-align:left;border-bottom:1px solid var(--color-border)}@media(max-width:700px){.summary{grid-template-columns:1fr}}</style>
