<script lang="ts">
	import { page } from '$app/state'; import { onMount } from 'svelte';import{csrfHeaders,idempotencyKey}from'$lib/api/client';
	let item=$state<any>(null), timeline:any[]=$state([]), error=$state(''), notice=$state(''),loading=$state(true),busy=$state(false),nextState=$state('IN_PROGRESS'),note=$state('');
	async function load(){const response=await fetch(`/api/v1/ops/cases/${page.params.id}`,{credentials:'include'});const data=await response.json().catch(()=>({}));loading=false;if(!response.ok){error=data.detail??'The case could not be loaded.';return}item=data.case;timeline=data.timeline??[];nextState=item.state==='OPEN'?'IN_PROGRESS':item.state==='IN_PROGRESS'?'RESOLVED':'CLOSED'}
	async function update(e:SubmitEvent){e.preventDefault();busy=true;error='';const r=await fetch(`/api/v1/ops/cases/${page.params.id}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({state:nextState,note})});const d=await r.json().catch(()=>({}));busy=false;if(!r.ok){error=d.detail??'The case could not be updated.';return}notice='Case updated. The note was added to its permanent history.';note='';await load()}
	onMount(load);
</script>
<svelte:head><title>Support case — Kredit</title></svelte:head>
<main class="shell workspace"><a href="/admin/cases">← All support cases</a><p class="eyebrow">Admin / Support case</p><h1>Support case</h1>{#if notice}<p class="notice">{notice}</p>{/if}{#if loading}<p>Loading case…</p>{:else if error}<p class="error" role="alert">{error}</p>{:else}<section class="summary"><div><span>Status</span><strong>{item.state.replaceAll('_',' ')}</strong></div><div><span>Subject</span><strong>{item.subject_type.replaceAll('_',' ')}</strong></div><div><span>Reference</span><code>{item.subject_id}</code></div><div><span>Opened</span><strong>{new Date(item.created_at).toLocaleString('en-NG')}</strong></div></section><div class="columns"><section><h2>Case history</h2><ol>{#each timeline as event}<li><strong>{event.action.replaceAll('_',' ')}</strong><span>{new Date(event.created_at).toLocaleString('en-NG')}</span>{#if event.note}<p>{event.note}</p>{/if}</li>{/each}</ol></section>{#if item.state!=='CLOSED'}<section class="action"><h2>Move this case forward</h2><form onsubmit={update}><label>New status<select bind:value={nextState}><option value="OPEN">Open</option><option value="IN_PROGRESS">Being handled</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></label><label>What happened?<textarea bind:value={note} minlength="4" rows="5" required></textarea></label><button class="primary" disabled={busy}>{busy?'Saving…':'Save case update'}</button></form></section>{/if}</div>{/if}</main>
<style>h1{font-family:Georgia,serif;font-size:clamp(2.5rem,6vw,4.5rem);font-weight:500}.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:1rem;margin:1.5rem 0}.summary div,li{padding:1rem;border:1px solid var(--color-border);background:var(--color-surface)}.summary div{display:grid;gap:.3rem}.summary span,li span{color:var(--color-muted)}.columns{display:grid;grid-template-columns:1.3fr .7fr;gap:2rem}ol{display:grid;gap:.7rem;padding:0;list-style:none}li span{display:block;font-size:.9rem;margin-top:.25rem}.action{align-self:start;padding:1.2rem;background:#17181b;color:white}.action form,.action label{display:grid;gap:.7rem}.action label{gap:.3rem}.action select,.action textarea,.action button{padding:.7rem;border:1px solid #555;background:#242529;color:white;font:inherit}.action button{background:#ff6848;color:#17181b;font-weight:850}@media(max-width:760px){.columns{grid-template-columns:1fr}}</style>
