import { createHmac } from 'node:crypto';
import { env } from '$env/dynamic/private';
import type { Handle } from '@sveltejs/kit';
import { assertLaunchWebConfig } from '$lib/server/legal-config';

assertLaunchWebConfig();

// Keep browser cookies first-party while the API remains an internal service.
// The same-origin proxy is used by the production Node adapter; Vite's proxy
// serves the equivalent role during local development.

// Applied to every HTML response the Node adapter serves; the Go API sets the
// equivalent headers for /api traffic. Content-Security-Policy is generated by
// SvelteKit from kit.csp so framework inline scripts receive hashes/nonces.
const SECURITY_HEADERS: Record<string, string> = {
	'x-content-type-options': 'nosniff',
	'x-frame-options': 'DENY',
	'referrer-policy': 'no-referrer',
	'permissions-policy': 'camera=(), microphone=(), geolocation=()',
	'cross-origin-opener-policy': 'same-origin',
	'cross-origin-resource-policy': 'same-origin',
	// Browsers ignore HSTS over plain HTTP, so it is safe to always send.
	'strict-transport-security': 'max-age=31536000; includeSubDomains'
};

export const handle: Handle = async ({ event, resolve }) => {
	if (!event.url.pathname.startsWith('/api/')) {
		const protectedAccountRoute = /^(?:\/app\/.+|\/buyer(?:\/|$)|\/admin(?:\/|$))/.test(event.url.pathname);
		if (protectedAccountRoute && !event.cookies.get('kredit_session')) {
			const next = `${event.url.pathname}${event.url.search}`;
			return new Response(null, {
				status: 303,
				headers: {
					location: `/app?next=${encodeURIComponent(next)}`,
					'cache-control': 'private, no-store'
				}
			});
		}
		const response = await resolve(event);
		for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
			response.headers.set(name, value);
		}
		const privateRoute = /^\/(app|buyer|admin|c|pay|receipt|secure|recover|buyer-invitations)(\/|$)/.test(event.url.pathname);
		if (!response.headers.has('cache-control')) response.headers.set('cache-control', privateRoute
			? 'private, no-store'
			: 'public, max-age=0, s-maxage=300, stale-while-revalidate=86400');
		return response;
	}
	const upstream = env.API_INTERNAL_URL ?? 'http://localhost:8080';
	const target = new URL(event.url.pathname + event.url.search, upstream);
	const headers = new Headers(event.request.headers);
	headers.delete('host');
	headers.delete('connection');
	// Discard browser-supplied forwarding claims before signing the adapter's address.
	for (const spoofable of ['x-forwarded-for', 'x-real-ip', 'cf-connecting-ip', 'true-client-ip', 'forwarded', 'x-kredit-client-ip', 'x-kredit-client-timestamp', 'x-kredit-client-signature']) {
		headers.delete(spoofable);
	}
	try {
		const clientAddress = event.getClientAddress();
		if (clientAddress && env.FRONTEND_PROXY_SIGNING_KEY) {
			const timestamp = Math.floor(Date.now() / 1000).toString();
			const payload = [timestamp, event.request.method, target.pathname + target.search, clientAddress].join('\n');
			headers.set('x-kredit-client-ip', clientAddress);
			headers.set('x-kredit-client-timestamp', timestamp);
			headers.set('x-kredit-client-signature', createHmac('sha256', env.FRONTEND_PROXY_SIGNING_KEY).update(payload).digest('hex'));
		}
	} catch {
		// Without an observed address, the API uses its trusted ingress address.
	}
	const method = event.request.method;
	try {
		let body: Uint8Array<ArrayBuffer> | undefined;
		if (method !== 'GET' && method !== 'HEAD' && event.request.body) {
			const reader = event.request.body.getReader();
			const chunks: Uint8Array[] = [];
			let size = 0;
			while (true) {
				const { value, done } = await reader.read();
				if (done) break;
				size += value.byteLength;
				if (size > (event.url.pathname.endsWith('/documents') ? 3 : 2) * 1024 * 1024) {
					await reader.cancel();
					return new Response(JSON.stringify({ title: 'Request too large', status: 413 }), {
						status: 413, headers: { 'content-type': 'application/problem+json', 'cache-control': 'no-store' }
					});
				}
				chunks.push(value);
			}
			body = new Uint8Array(size);
			let offset = 0;
			for (const chunk of chunks) { body.set(chunk, offset); offset += chunk.byteLength; }
		}
		const timeout = AbortSignal.timeout(30_000);
		const signal = AbortSignal.any([event.request.signal, timeout]);
		return await fetch(target, { method, headers, body, redirect: 'manual', signal });
	} catch {
		return new Response(JSON.stringify({ type: 'about:blank', title: 'Service unavailable', status: 503, detail: 'The API is temporarily unavailable.' }), {
			status: 503,
			headers: { 'content-type': 'application/problem+json', 'cache-control': 'no-store' }
		});
	}
};
