import { createHmac } from 'node:crypto';
import { env } from '$env/dynamic/private';
import { env as publicEnv } from '$env/dynamic/public';
import type { Handle } from '@sveltejs/kit';
import { assertLaunchWebConfig } from '$lib/server/legal-config';
import { parkedDestination } from '$lib/features';
import { applyPageCachePolicy, isAccountPage } from '$lib/server/page-cache';
import { ProxyBodyError, proxyHeaders, readProxyBody } from '$lib/server/proxy-body';

assertLaunchWebConfig();

// Keep browser cookies first-party while the API remains an internal service.
// The same-origin proxy is used by the production Node adapter; Vite's proxy
// serves the equivalent role during local development.

// Applied to every HTML response the Node adapter serves; the Go API sets the
// equivalent headers for /api traffic. Content-Security-Policy is generated by
// SvelteKit from kit.csp so framework inline scripts receive hashes/nonces.
const SECURITY_HEADERS: Record<string, string> = {
	'x-content-type-options': 'nosniff',
	'x-frame-options': 'DENY',
	'referrer-policy': 'no-referrer',
	'permissions-policy': 'camera=(), microphone=(), geolocation=()',
	'cross-origin-opener-policy': 'same-origin',
	'cross-origin-resource-policy': 'same-origin',
	// Browsers ignore HSTS over plain HTTP, so it is safe to always send.
	'strict-transport-security': 'max-age=31536000; includeSubDomains'
};

export const handle: Handle = async ({ event, resolve }) => {
	if (!event.url.pathname.startsWith('/api/')) {
		if (isAccountPage(event.url.pathname) && !event.cookies.get('kredit_session')) {
			const next = `${event.url.pathname}${event.url.search}`;
			const response = new Response(null, {
				status: 303,
				headers: {
					...SECURITY_HEADERS,
					location: `/signin?next=${encodeURIComponent(next)}`
				}
			});
			applyPageCachePolicy(event.url.pathname, response, event.request.method);
			return response;
		}
		const parked =
			event.request.method === 'GET' || event.request.method === 'HEAD'
				? parkedDestination(event.url.pathname, publicEnv.PUBLIC_KREDIT_FULL_WORKSPACE === '1')
				: null;
		if (parked) {
			// Keep the business choice (?organization=) and any prefilled sale details.
			const response = new Response(null, {
				status: 307,
				headers: { ...SECURITY_HEADERS, location: `${parked}${event.url.search}` }
			});
			applyPageCachePolicy(event.url.pathname, response, event.request.method);
			return response;
		}
		const response = await resolve(event);
		for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
			response.headers.set(name, value);
		}
		applyPageCachePolicy(
			event.url.pathname,
			response,
			event.request.method,
			Boolean(event.cookies.get('kredit_session'))
		);
		return response;
	}
	const upstream = env.API_INTERNAL_URL ?? 'http://localhost:8080';
	const target = new URL(event.url.pathname + event.url.search, upstream);
	const headers = proxyHeaders(event.request.headers);
	headers.delete('host');
	headers.delete('accept-encoding');
	// fetch computes the length of the actual buffered bytes, not the client's claim.
	headers.delete('content-length');
	// Discard browser-supplied forwarding claims before signing the adapter's address.
	for (const spoofable of [
		'x-forwarded-for',
		'x-real-ip',
		'cf-connecting-ip',
		'true-client-ip',
		'forwarded',
		'x-kredit-client-ip',
		'x-kredit-client-timestamp',
		'x-kredit-client-signature'
	]) {
		headers.delete(spoofable);
	}
	const method = event.request.method;
	try {
		let body: Uint8Array<ArrayBuffer> | undefined;
		if (method !== 'GET' && method !== 'HEAD' && event.request.body) {
			// A separate input deadline covers time spent receiving the body. The
			// upstream deadline cannot protect a request that has not been sent yet.
			// Base64 document bodies need the existing 4 MiB allowance on both
			// singular identity-document and plural document upload routes.
			const maxBytes = (/\/documents?$/.test(event.url.pathname) ? 4 : 2) * 1024 * 1024;
			body = await readProxyBody(event.request.body, maxBytes, event.request.signal);
		}
		try {
			const clientAddress = event.getClientAddress();
			if (clientAddress && env.FRONTEND_PROXY_SIGNING_KEY) {
				// Sign immediately before sending so a valid slow upload does not
				// consume the API's timestamp acceptance window before dispatch.
				const timestamp = Math.floor(Date.now() / 1000).toString();
				const payload = [timestamp, method, target.pathname + target.search, clientAddress].join('\n');
				headers.set('x-kredit-client-ip', clientAddress);
				headers.set('x-kredit-client-timestamp', timestamp);
				headers.set(
					'x-kredit-client-signature',
					createHmac('sha256', env.FRONTEND_PROXY_SIGNING_KEY).update(payload).digest('hex')
				);
			}
		} catch {
			// Without an observed address, the API uses its trusted ingress address.
		}
		const timeout = AbortSignal.timeout(30_000);
		const signal = AbortSignal.any([event.request.signal, timeout]);
		const upstreamResponse = await fetch(target, { method, headers, body, redirect: 'manual', signal });
		const responseHeaders = proxyHeaders(upstreamResponse.headers);
		// Node.js fetch() automatically decompresses the body stream. Forwarding upstream
		// content-encoding or content-length will cause net::ERR_CONTENT_DECODING_FAILED in the browser.
		responseHeaders.delete('content-encoding');
		responseHeaders.delete('content-length');

		return new Response(upstreamResponse.body, {
			status: upstreamResponse.status,
			statusText: upstreamResponse.statusText,
			headers: responseHeaders
		});
	} catch (error) {
		if (error instanceof ProxyBodyError) {
			const title =
				error.status === 413 ? 'Request too large' : error.status === 408 ? 'Request timeout' : 'Invalid request body';
			return new Response(JSON.stringify({ type: 'about:blank', title, status: error.status, detail: error.message }), {
				status: error.status,
				headers: { ...SECURITY_HEADERS, 'content-type': 'application/problem+json', 'cache-control': 'no-store' }
			});
		}
		return new Response(
			JSON.stringify({
				type: 'about:blank',
				title: 'Service unavailable',
				status: 503,
				detail: 'The API is temporarily unavailable.'
			}),
			{
				status: 503,
				headers: { ...SECURITY_HEADERS, 'content-type': 'application/problem+json', 'cache-control': 'no-store' }
			}
		);
	}
};
