<script lang="ts">
	import { onMount } from 'svelte';
	import { csrfHeaders,idempotencyKey } from '$lib/api/client';
	import { productLabel } from '$lib/product-language';
	let orgID=$state(''),members:any[]=$state([]),target=$state(''),channel=$state('email'),role=$state('sales'),message=$state(''),error=$state(''),busy=$state(''),loading=$state(true);
	let roleDraft:Record<string,string>=$state({});
	async function load(){loading=true;error='';try{const r=await fetch('/api/v1/organizations',{credentials:'include'});if(!r.ok)throw new Error('We could not open your business.');const d=await r.json();orgID=d.organizations?.[0]?.id??'';if(!orgID){members=[];return}const q=await fetch(`/api/v1/organizations/${orgID}/members`,{credentials:'include'});const data=await q.json().catch(()=>({}));if(!q.ok)throw new Error(data.detail??'We could not open your staff list.');members=data.members??[];roleDraft=Object.fromEntries(members.map((m)=>[m.user_id,m.role]))}catch(cause){error=cause instanceof Error?cause.message:'We could not open your staff list.'}finally{loading=false}}
	async function invite(event:SubmitEvent){event.preventDefault();busy='invite';error='';message='';const r=await fetch(`/api/v1/organizations/${orgID}/members`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({target,channel,role})});const d=await r.json().catch(()=>({}));busy='';if(!r.ok){error=d.detail??'We could not send this invite.';return}target='';message='Invite sent.';await load()}
	async function change(member:any,body:{role?:string;status?:string},label:string){busy=member.user_id;error='';message='';const r=await fetch(`/api/v1/organizations/${orgID}/members/${member.user_id}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));busy='';if(!r.ok){error=d.detail??'Access could not be changed. Refresh and try again.';return}message=label;await load()}
	onMount(load);
</script>
<svelte:head><title>Team — Kredit</title></svelte:head>
<main class="shell workspace team"><p class="eyebrow">Your staff</p><h1>Choose what each person can do.</h1><p class="lede">Invite a staff member, change their job or stop their access. The business owner's access cannot be removed.</p>
	{#if message}<p class="notice" role="status">{message}</p>{/if}{#if error}<p class="error" role="alert">{error} <button onclick={load}>Refresh team</button></p>{/if}
	<section class="card"><h2>Invite a staff member</h2><form onsubmit={invite}><label>Email or phone<input bind:value={target} type={channel==='email'?'email':'tel'} required /></label><label>Send invite by<select bind:value={channel}><option value="email">Email</option><option value="phone">Phone</option></select></label><label>What will they do?<select bind:value={role}><option value="sales">Add sales</option><option value="finance">Handle money</option><option value="collections">Follow late payments</option><option value="administrator">Manage the account</option><option value="viewer">Look only</option></select></label><button class="primary" disabled={busy==='invite'||!target}>{busy==='invite'?'Sending…':'Send invite'}</button></form></section>
	<section class="card"><h2>People with access</h2>{#if loading}<p role="status">Opening your staff list…</p>{:else if members.length}<div class="member-list">{#each members as member}<article><div><strong>{productLabel(member.role)}</strong><span class="status">{productLabel(member.status)}</span><small>Account {member.user_id}</small>{#if member.role==='finance'&&member.status==='active'}<em>This person needs extra sign-in safety.</em>{/if}</div>{#if member.role!=='owner'&&member.status!=='removed'}<div class="controls"><label>What can they do?<span class="sr-only"> for {member.user_id}</span><select bind:value={roleDraft[member.user_id]} disabled={member.status!=='active'||busy===member.user_id}><option value="sales">Add sales</option><option value="finance">Handle money</option><option value="collections">Follow late payments</option><option value="administrator">Manage the account</option><option value="viewer">Look only</option></select></label><button disabled={member.status!=='active'||roleDraft[member.user_id]===member.role||busy===member.user_id} onclick={()=>change(member,{role:roleDraft[member.user_id]},'What this person can do was changed.')}>Save change</button>{#if member.status==='active'}<button class="danger" disabled={busy===member.user_id} onclick={()=>change(member,{status:'suspended'},'This person can no longer enter the account.')}>Stop access</button>{:else if member.status==='suspended'}<button disabled={busy===member.user_id} onclick={()=>change(member,{status:'active'},'This person can enter the account again.')}>Allow access again</button>{/if}<button class="danger" disabled={busy===member.user_id} onclick={()=>change(member,{status:'removed'},'This person was removed from the business account.')}>Remove</button></div>{/if}</article>{/each}</div>{:else}<p>No staff member has been added yet.</p>{/if}</section>
</main>
<style>.team h1{font-size:clamp(2.4rem,6vw,4.5rem);line-height:1}.card{margin:1.5rem 0;padding:1.3rem}.card form{display:grid;grid-template-columns:2fr 1fr 1fr auto;align-items:end;gap:.7rem}label{display:grid;gap:.3rem;font-weight:700}input,select,button{box-sizing:border-box;padding:.7rem;border:1px solid var(--color-border);border-radius:.65rem;background:var(--color-surface);color:inherit;font:inherit}.member-list{display:grid;gap:.75rem}.member-list article{display:grid;grid-template-columns:minmax(16rem,1fr) 2fr;gap:1rem;padding:1rem;border-top:1px solid var(--color-border)}.member-list article>div:first-child{display:grid;grid-template-columns:auto auto 1fr;align-items:center;gap:.55rem}.member-list strong{text-transform:capitalize}.member-list small,.member-list em{grid-column:1/-1;overflow-wrap:anywhere}.member-list em{color:var(--color-warning)}.controls{display:flex;flex-wrap:wrap;align-items:end;gap:.5rem}.controls select{min-width:10rem}.danger{color:var(--color-destructive);border-color:var(--color-destructive)}.notice{padding:1rem;border-left:4px solid var(--color-positive);background:var(--color-surface-muted)}@media(max-width:820px){.card form,.member-list article{grid-template-columns:1fr}.controls{align-items:stretch;flex-direction:column}.controls button,.controls label{width:100%}}</style>
