<script lang="ts">
	import{onMount}from'svelte';import Money from'$lib/components/Money.svelte';
	let summary=$state<any>(null),activity=$state<any[]>([]),loading=$state(true),error=$state('');
	async function load(){loading=true;const r=await fetch('/api/v1/ops/money?limit=100',{credentials:'include'});const d=await r.json().catch(()=>({}));loading=false;if(!r.ok){error=d.detail??'Money activity could not be loaded.';return}summary=d.summary;activity=d.activity??[]}
	onMount(load);
</script>
<svelte:head><title>Money — Kredit admin</title></svelte:head>
<main class="shell workspace money"><header><p class="eyebrow">Admin / Money</p><h1>The platform money position.</h1><p>Confirmed payments, bank-debit attempts and customer balances. No estimated bank alerts are included.</p></header>{#if error}<p class="error">{error}</p>{:else if loading}<p>Checking the latest money records…</p>{:else}<section class="totals"><article><span>Money received</span><strong><Money amountKobo={summary.received_kobo}/></strong><small>{summary.payment_count} payment records</small></article><article><span>Money still owed</span><strong><Money amountKobo={summary.outstanding_kobo}/></strong><small>Across active sales</small></article><article><span>Debit requested</span><strong><Money amountKobo={summary.collection_requested_kobo}/></strong><small>All bank-debit attempts</small></article><article><span>Debit successful</span><strong><Money amountKobo={summary.collection_succeeded_kobo}/></strong><small>Confirmed by providers</small></article></section><section class="activity"><div><p class="eyebrow">Latest activity</p><h2>Payments and bank debits.</h2></div><div class="table-wrap"><table><thead><tr><th>Type</th><th>Amount</th><th>Status</th><th>Reference</th><th>Time</th></tr></thead><tbody>{#each activity as item}<tr><td>{item.kind==='payment'?'Payment':'Bank debit'}</td><td><strong><Money amountKobo={item.amount_kobo}/></strong></td><td>{item.state.replaceAll('_',' ')}</td><td><code>{item.reference}</code></td><td>{new Date(item.occurred_at).toLocaleString('en-NG')}</td></tr>{/each}</tbody></table></div></section>{/if}</main>
<style>.money>header{padding:2rem 0;border-bottom:3px solid #17181b}.money h1{max-width:15ch;margin:.4rem 0;font-family:Georgia,serif;font-size:clamp(2.5rem,6vw,4.5rem);font-weight:500;line-height:.95}.money header p{max-width:42rem}.totals{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin:2rem 0 4rem;border-top:1px solid #bbb6ac;border-left:1px solid #bbb6ac}.totals article{display:grid;gap:.6rem;min-height:9rem;padding:1rem;border-right:1px solid #bbb6ac;border-bottom:1px solid #bbb6ac;background:#faf8f2}.totals article>strong{font-family:Georgia,serif;font-size:1.65rem}.totals small{align-self:end;color:#66635e}.activity>div:first-child{border-bottom:3px solid #17181b}.activity h2{font-family:Georgia,serif;font-size:2.3rem;font-weight:500}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;background:#faf8f2}th,td{padding:1rem;text-align:left;border-bottom:1px solid #d0cbc1}code{font-size:.72rem}@media(max-width:850px){.totals{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:440px){.totals{grid-template-columns:1fr}}</style>
