<script lang="ts">
 import {onMount} from 'svelte';
 import {read,purchase,Mutation,money,kobo,label,type Purchase} from '$lib/consumer';
 import {record,normalizeNigerianPhone} from '$lib/api/reliable';
 import {organization,type Organization} from '$lib/records';
 let {mode='buyer'}:{mode?:'buyer'|'seller'|'admin'}=$props();
 let items=$state<Purchase[]>([]),businesses=$state<Organization[]>([]),org=$state(''),error=$state(''),message=$state(''),busy=$state(false),loaded=$state(false),search=$state('');
 let channel=$state('email'),target=$state(''),item=$state(''),quantity=$state(1),total=$state(''),deposit=$state('0'),depositDate=$state(''),firstDate=$state(''),count=$state(4),cadence=$state('weekly'),fulfillment=$state('on_full_payment'),threshold=$state(50),days=$state(7),stock=$state(''),reserved=$state(false),returns=$state('Before release, cancellation receives a full refund. Contact us to arrange return of incorrect, defective or undelivered goods. We review other returns individually. Your statutory rights are unaffected.');
 let enabled=$state(true),number=$state(''),evidence=$state('');
 let cursor=$state('');
 const mutation=new Mutation(),settingsMutation=new Mutation();
 const matching=$derived(items.filter(i=>`${i.terms.item} ${i.customer_name} ${i.target} ${i.id}`.toLowerCase().includes(search.toLowerCase())));
 const endpoint=$derived(mode==='buyer'?'/api/v1/buyer/purchases':mode==='admin'?'/api/v1/ops/consumer-sales':`/api/v1/organizations/${org}/consumer-sales`);
 function href(s:Purchase){return mode==='buyer'?`/buyer/purchases/${s.id}`:mode==='admin'?`/admin/consumer-sales/${s.id}`:`/app/consumer-sales/${s.id}?organization=${s.organization_id}`}
 async function load(){busy=true;error='';loaded=false;items=[];try{if(mode==='seller'&&!org)return;const data=record(await read(endpoint));if(!Array.isArray(data.items))throw new Error('The purchase list could not be verified.');items=data.items.map(purchase);cursor=typeof data.next_cursor==='string'?data.next_cursor:'';loaded=true;}catch(e){error=e instanceof Error?e.message:'Could not load purchases.'}finally{busy=false}}
 async function more(){busy=true;error='';try{const data=record(await read(endpoint+'?before='+encodeURIComponent(cursor)));if(!Array.isArray(data.items))throw new Error('Could not verify the next page.');items=[...items,...data.items.map(purchase)];cursor=typeof data.next_cursor==='string'?data.next_cursor:'';}catch(e){error=e instanceof Error?e.message:'Could not load more purchases.'}finally{busy=false}}
 async function retry(){busy=true;error='';try{if(mutation.pending){const data=purchase(await mutation.retry());message=`Offer confirmed: ${location.origin}/buyer/purchases/${data.id}`;}else{await settingsMutation.retry();message='Settings confirmed.'}await load();}catch(e){error=e instanceof Error?e.message:'Could not confirm previous action.'}finally{busy=false}}
 async function init(){try{if(mode==='seller'){const data=record(await read('/api/v1/organizations'));if(!Array.isArray(data.organizations))throw new Error('Could not load businesses.');businesses=data.organizations.map(organization);const requested=new URLSearchParams(location.search).get('organization');org=businesses.find(b=>b.id===requested)?.id??businesses[0]?.id??'';}await load();}catch(e){error=e instanceof Error?e.message:'Could not load businesses.'}}
 async function create(){busy=true;error='';try{const data=purchase(await mutation.send(endpoint,{target_type:channel,target:channel==='phone'?normalizeNigerianPhone(target):target.trim(),terms:{item,quantity,total_kobo:kobo(total),deposit_kobo:kobo(deposit),deposit_date:depositDate,first_date:firstDate,count,cadence,fulfillment,threshold_percent:threshold,delivery_days:days,stock_reference:stock,stock_reserved:reserved,returns_policy:returns}}));message=`Offer saved. Share this private sign-in link with ${data.target}: ${location.origin}/buyer/purchases/${data.id}`;items=[data,...items];}catch(e){error=e instanceof Error?e.message:'The offer was not confirmed.'}finally{busy=false}}
 async function connectBank(){busy=true;error='';try{await settingsMutation.send(`/api/v1/organizations/${encodeURIComponent(org)}/consumer-bank`,{account_number:number});message='Receiving account matched. Consumer sales are available when your business checks are complete.';number='';}catch(e){error=e instanceof Error?e.message:'Could not confirm the receiving account.'}finally{busy=false}}
 async function saveSettings(){busy=true;error='';try{await settingsMutation.send(`/api/v1/ops/organizations/${encodeURIComponent(org)}/consumer-settings`,{enabled,review_evidence:evidence});message='Restriction updated. Eligible retailers can use consumer sales automatically.';}catch(e){error=e instanceof Error?e.message:'Settings were not saved.'}finally{busy=false}}
 async function loadSettings(){busy=true;error='';try{const s=record(await read(`/api/v1/ops/organizations/${encodeURIComponent(org)}/consumer-settings`));enabled=s.enabled===true;evidence=String(s.review_evidence??'');}catch(e){error=e instanceof Error?e.message:'Settings unavailable.'}finally{busy=false}}
 onMount(init);
</script>
<main class="shell workspace feature-page consumer-sales"><header class="feature-heading"><div><p class="eyebrow">{mode==='seller'?'Retailer → Consumer':mode==='admin'?'Super admin · Retailer → Consumer':'Retailer → You · Personal use'}</p><h1>{mode==='seller'?'Consumer sales':mode==='admin'?'Consumer purchases':'Your purchases'}</h1><p class="lede">{mode==='seller'?'Sell goods to individuals for personal use, on installments or layaway. Customer payments go to your receiving account.':mode==='admin'?'Review purchases, resolve exceptions and support your retailers.':'See what you have paid, what is due and when your goods will arrive.'}</p></div><a class="secondary" href={mode==='seller'?'#new-consumer-offer':'#purchase-list'}>{mode==='seller'?'Create an offer →':'View purchases →'}</a></header>
 {#if error}<p class="error" role="alert">{error}</p>{#if mutation.pending||settingsMutation.pending}<button onclick={retry} disabled={busy}>Retry the same unconfirmed action</button>{/if}{/if}{#if message}<p role="status" class="message">{message}</p>{/if}
 {#if mode==='seller'}<label>Retailer business<select bind:value={org} onchange={load} disabled={busy}>{#each businesses as b}<option value={b.id}>{b.trading_name||b.legal_name}</option>{/each}</select></label>
 <details><summary>Connect your receiving account<span>One setup step for direct customer payments</span></summary><p>Enter the receiving account already connected in your <a href="/app/settings/settlement">settlement settings</a>. Kredit matches it automatically. You do not need a separate consumer-sale approval.</p><form onsubmit={e=>{e.preventDefault();void connectBank()}}><label>Receiving account number<input bind:value={number} pattern="[0-9]{10}" maxlength="10" required disabled={busy}/></label><button disabled={busy||!org}>Use this account</button></form></details>
 <details id="new-consumer-offer" class="offer-form"><summary>Create a consumer offer<span>Set the item, payment dates and delivery terms</span></summary><form onsubmit={e=>{e.preventDefault();void create()}}><fieldset disabled={busy||!org}><div class="grid">
 <label>Send the sign-in code by<select bind:value={channel}><option value="email">Email</option><option value="phone">WhatsApp</option></select></label><label>Customer {channel==='email'?'email':'WhatsApp number'}<input bind:value={target} type={channel==='email'?'email':'tel'} required/></label>
 <label>Item or product description<input bind:value={item} required minlength="3" maxlength="500"/></label><label>Quantity<input type="number" bind:value={quantity} min="1" max="10000" required/></label><label>Total price for all items (₦)<input bind:value={total} inputmode="decimal" required/></label><label>Deposit (₦; use 0 for none)<input bind:value={deposit} inputmode="decimal" required/></label><label>Deposit due date (if any)<input type="date" bind:value={depositDate}/></label><label>First installment date<input type="date" bind:value={firstDate} required/></label><label>Number of installments after deposit<input type="number" bind:value={count} min="1" max="60" required/></label><label>Payment frequency<select bind:value={cadence}><option value="weekly">Weekly</option><option value="fortnightly">Every two weeks</option><option value="monthly">Monthly</option></select></label>
 <label>Deliver goods<select bind:value={fulfillment}><option value="on_full_payment">After full payment (layaway)</option><option value="on_percentage">After a percentage is paid</option><option value="immediate">After the customer accepts</option></select></label>{#if fulfillment==='on_percentage'}<label>Percentage needed<input type="number" bind:value={threshold} min="1" max="99" required/></label>{/if}
 <label>Deliver within this many days of eligibility<input type="number" bind:value={days} min="1" max="90" required/></label><label>Stock reservation reference<input bind:value={stock} required minlength="3" maxlength="200"/></label></div>
 <label><input type="checkbox" bind:checked={reserved} required/>I have reserved these goods and can meet the delivery terms.</label><label>Return and refund arrangements<textarea bind:value={returns} required minlength="20" maxlength="2000" rows="4"></textarea></label><p>Use one installment for a single due-date payment. Monthly dates are capped at month-end. There are no added interest or late fees. Payment instructions come from the registered receiving account matched by Kredit. Confirm the offer before sharing; accepted terms cannot be edited.</p><button class="primary">Create offer</button></fieldset></form></details>{/if}
 {#if mode==='admin'}<details><summary>Restrict or restore a retailer when needed</summary><p>Eligible retailers activate automatically. Use this control only for an exception, such as suspected fraud or an unresolved operating issue. Removing a restriction does not bypass business or bank checks.</p><a href="/admin/organizations">Browse businesses and their IDs</a><label>Retailer business ID<input bind:value={org} disabled={busy}/></label><button onclick={loadSettings} disabled={busy||!org}>Load restriction</button><form onsubmit={e=>{e.preventDefault();void saveSettings()}}><fieldset disabled={busy||!org}><label>Reason<textarea bind:value={evidence} minlength="20" maxlength="2000" required></textarea></label><label><input type="checkbox" bind:checked={enabled}/>No consumer-sale restriction</label><button>Save exception decision</button></fieldset></form></details>{/if}
 <section id="purchase-list"><p class="eyebrow">Payment & delivery progress</p><h2>Purchases</h2><label>Find a purchase<input bind:value={search} type="search"/></label><button onclick={load} disabled={busy}>Refresh list</button>{#if busy}<p>Loading…</p>{:else if !loaded}<p>Choose a business or retry loading the list.</p>{:else}{#each matching as sale}<a class="sale record-row" href={href(sale)}><strong>{sale.terms.item}</strong><span>{sale.customer_name||sale.target} · {label(sale.state)}{sale.case_state?` · Return ${label(sale.case_state)}`:''}</span><span>{money(sale.outstanding_kobo)} left to pay · {money(sale.refund_due_kobo)} refund due</span></a>{:else}<div class="empty-state"><h3>No matching purchases yet.</h3><p>{mode==='seller'?'Create an offer to start tracking a customer’s payments and delivery.':'Your purchases will appear here. If you searched, try another name or item.'}</p></div>{/each}{#if cursor}<button onclick={more} disabled={busy}>Load older purchases</button>{/if}{/if}</section></main>
