<script lang="ts">
 import { parseNaira } from '$lib/money';
	import { onMount } from 'svelte';
	import { csrfHeaders, idempotencyKey } from '$lib/api/client';
	import { productLabel } from '$lib/product-language';
	let { endpoint, backHref, canDecide = false }:{ endpoint:string; backHref:string; canDecide?:boolean } = $props();
	let dispute:any=$state(null), evidence:any[]=$state([]), decisions:any[]=$state([]), loading=$state(true), busy=$state(false), error=$state(''), notice=$state('');
	let statement=$state(''), documentID=$state(''), outcome=$state('UPHELD'), valid=$state('0'), adjustment=$state('0'), remaining=$state('0'), reason=$state('');
	const money=(value:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format((value??0)/100);
	async function load(){loading=true;error='';try{const response=await fetch(endpoint,{credentials:'include'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail??'We could not open this problem.');dispute=data.dispute;evidence=data.evidence??[];decisions=data.decisions??[];remaining=String((dispute.remaining_disputed_kobo??0)/100)}catch(cause){error=cause instanceof Error?cause.message:'We could not open this problem.'}finally{loading=false}}
	async function submitEvidence(event:SubmitEvent){event.preventDefault();busy=true;error='';notice='';const response=await fetch(`${endpoint}/evidence`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify({document_id:documentID,statement})});const data=await response.json().catch(()=>({}));busy=false;if(!response.ok){error=data.detail??'We could not add this information.';return}statement='';documentID='';notice='Information added.';await load()}
	async function decide(event:SubmitEvent){event.preventDefault();busy=true;error='';notice='';const body={outcome,valid_principal_kobo:parseNaira(valid),adjustment_kobo:parseNaira(adjustment),remaining_disputed_kobo:parseNaira(remaining),reason};const response=await fetch(`${endpoint}/decide`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey(),...csrfHeaders()},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));busy=false;if(!response.ok){error=data.detail??'This problem changed before the decision was saved. Check it and try again.';return}notice='Decision saved. The amount owed has been updated.';await load()}
	onMount(load);
</script>
<a href={backHref}>← All reported problems</a>
{#if loading}<p role="status">Opening the problem…</p>{:else if error && !dispute}<p class="error" role="alert">{error} <button onclick={load}>Try again</button></p>{:else if dispute}
	{#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
	<section class="summary" aria-label="Problem summary"><article><span>Now</span><strong>{productLabel(dispute.state)}</strong></article><article><span>Money reported</span><strong>{money(dispute.total_disputed_kobo)}</strong></article><article><span>Money still affected</span><strong>{money(dispute.remaining_disputed_kobo)}</strong></article><article><span>What happens to bank debit</span><strong>{productLabel(dispute.collection_effect)}</strong></article></section>
	<article class="card"><h2>{dispute.reason}</h2><p>{dispute.explanation||'No other details were added.'}</p><small>Reported {new Date(dispute.opened_at).toLocaleString('en-NG')}</small></article>
	<div class="columns"><section class="card"><h2>What people have added</h2>{#if evidence.length}<ol>{#each evidence as item}<li><p>{item.statement||'A document was added.'}</p>{#if item.document_id}<details><summary>Document number</summary><code>{item.document_id}</code></details>{/if}<small>{new Date(item.submitted_at).toLocaleString('en-NG')}</small></li>{/each}</ol>{:else}<p>Nothing has been added yet.</p>{/if}<form onsubmit={submitEvidence}><h3>Add more information</h3><label>What should we know?<textarea bind:value={statement} required rows="4"></textarea></label><label>Document number <small>optional</small><input bind:value={documentID}/></label><button class="primary" disabled={busy||!statement.trim()}>{busy?'Adding…':'Add this information'}</button></form></section>
	<section class="card"><h2>Past decisions</h2>{#if decisions.length}<ol>{#each decisions as item}<li><strong>{productLabel(item.outcome)}</strong><p>{item.reason}</p><small>{new Date(item.decided_at).toLocaleString('en-NG')}</small></li>{/each}</ol>{:else}<p>No decision has been made yet.</p>{/if}
	{#if canDecide && !['RESOLVED','WITHDRAWN'].includes(dispute.state)}<form onsubmit={decide}><h3>Make a decision</h3><label>Decision<select bind:value={outcome}><option value="UPHELD">Accept the problem</option><option value="REJECTED">Do not accept it</option><option value="PARTIALLY_UPHELD">Accept part of it</option></select></label><label>Correct sale amount (₦)<input bind:value={valid} inputmode="decimal"/></label><label>Money to add or remove (₦)<input bind:value={adjustment} inputmode="decimal"/></label><label>Money still being checked (₦)<input bind:value={remaining} inputmode="decimal"/></label><label>Why did you decide this?<textarea bind:value={reason} required rows="3"></textarea></label><button class="primary" disabled={busy||!reason.trim()}>{busy?'Saving…':'Save this decision'}</button></form>{/if}</section></div>
{/if}
<style>.summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;margin:1.5rem 0}.summary article{padding:1rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--color-surface)}.summary span,.summary strong{display:block}.columns{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{padding:1.25rem}ol{display:grid;gap:.75rem;padding:0;list-style:none}li{padding:.8rem;border-left:3px solid var(--color-primary);background:var(--color-surface-muted)}li p{margin:.25rem 0}form,label{display:grid;gap:.45rem}form{gap:.75rem;margin-top:1rem;padding-top:1rem;border-top:1px solid var(--color-border)}input,select,textarea{box-sizing:border-box;width:100%;padding:.7rem;border:1px solid var(--color-border);border-radius:.55rem;background:var(--color-surface);color:inherit}.notice{padding:.8rem;border-left:4px solid var(--color-positive);background:var(--color-surface-muted)}@media(max-width:760px){.summary,.columns{grid-template-columns:1fr}}</style>
