<script lang="ts">
 import {checkedJSON,record,rows,text,publicError} from '$lib/api/reliable';
 import {MutationIntent} from '$lib/api/mutation';
 import {formatKobo} from '$lib/money';
 let {org,admin=false,onselect}:{org:string;admin?:boolean;onselect?:(id:string)=>void}=$props();
 type Authorization={id:string;provider:string;state:string;authorization_url:string;ceiling_kobo:number;ends_at:string;approved:boolean;mandate_reference:string};
 let items=$state<Authorization[]>([]),error=$state(''),message=$state(''),busy=$state(false),available=$state(false),email=$state(''),phone=$state(''),address=$state(''),bvn=$state(''),ceiling=$state(''),consent=$state(false),evidence=$state(''),reference=$state(''),reviewed=$state(false),selected=$state<Authorization|null>(null),action=$state('');
 const endpoint=$derived(admin?`/api/v1/ops/fee-authorizations/${encodeURIComponent(org)}`:`/api/v1/organizations/${encodeURIComponent(org)}/fee-authorizations`);
 let mutation:MutationIntent|null=null;
 async function load(){error='';try{const data=await checkedJSON(endpoint,record);available=data.available===true;items=rows('authorizations',value=>{const r=record(value);if(!Number.isSafeInteger(r.ceiling_kobo)||Number(r.ceiling_kobo)<=0)throw new Error('Invalid ceiling');return{id:text(r.id),provider:text(r.provider),state:text(r.state),authorization_url:typeof r.authorization_url==='string'?r.authorization_url:'',ceiling_kobo:Number(r.ceiling_kobo),ends_at:text(r.ends_at),approved:r.approved===true,mandate_reference:typeof r.mandate_reference==='string'?r.mandate_reference:''}})(data)}catch(cause){error=publicError(cause,'Fee permissions could not be loaded.')}}
 $effect(()=>{if(org){mutation=null;selected=null;void load()}});
 function choose(item:Authorization,kind:string){selected=item;action=kind;reference='';evidence='';reviewed=false;mutation=new MutationIntent('fee-authorization',endpoint)}
 async function send(payload:Record<string,unknown>){if(busy)return;busy=true;error='';try{mutation??=new MutationIntent('fee-authorization',endpoint);await mutation.run(payload,value=>{if(record(value).saved!==true)throw new Error('Setup not confirmed');return true});mutation=null;selected=null;message='Saved. Refresh the page after completing the bank permission.';await load()}catch(cause){error=publicError(cause,'This request is unconfirmed. Refresh and review the saved setup before retrying.')}finally{bvn='';busy=false}}
 function start(){if(!/^\d+(\.\d{1,2})?$/.test(ceiling)){error='Enter a valid naira ceiling.';return}const [whole,fraction='']=ceiling.split('.');const amount=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(amount)||amount<20000||amount>2500000000){error='The ceiling must be between ₦200 and ₦25 million.';return}void send({action:'start',email,phone,address,bvn,ceiling_kobo:amount,consent_version:consent?'seller-fees-v1':''})}
 function safeURL(value:string){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
</script>
<section><h2>Separate bank permission for Kredit fees</h2><p>This permission pays the seller’s platform fees. Its ceiling is the total that may be debited over one year. Bills are issued before collection and are due seven days later.</p>{#if error}<p role="alert">{error}</p>{/if}{#if message}<p role="status">{message}</p>{/if}<button disabled={busy} onclick={load}>Refresh permissions</button>
{#each items as item(item.id)}<article><strong>{item.state.replaceAll('_',' ')}</strong><p>{formatKobo(item.ceiling_kobo)} lifetime ceiling · ends {new Date(item.ends_at).toLocaleDateString('en-NG')}</p><p>Setup reference: {item.id}</p>{#if admin}<button disabled={busy||!['customer_pending','mandate_pending','ready'].includes(item.state)} onclick={()=>choose(item,item.state==='customer_pending'?'customer':'approve')}>Review saved setup</button>{:else}{#if item.state==='customer_ready'}<button disabled={busy} onclick={()=>{mutation=null;void send({action:'authorize',id:item.id})}}>Open bank permission setup</button>{/if}{#if item.authorization_url&&safeURL(item.authorization_url)}<a href={safeURL(item.authorization_url)} target="_blank" rel="noopener noreferrer">Give permission with the bank</a>{/if}{#if ['mandate_pending','ready'].includes(item.state)&&onselect}<button disabled={busy} onclick={()=>onselect?.(item.id)}>Use this permission for billing</button>{/if}{#if item.state==='paused'&&item.mandate_reference}<button disabled={busy} onclick={()=>choose(item,'resume')}>Request resumption</button>{/if}{#if ['ready','customer_ready'].includes(item.state)}<button disabled={busy} onclick={()=>choose(item,'pause')}>Pause future fee debits</button>{/if}{/if}</article>{/each}
{#if !admin&&available&&!items.some(i=>i.state!=='paused')}<form onsubmit={e=>{e.preventDefault();start()}}><fieldset disabled={busy}><legend>Create a fee bank permission</legend><label>Business email<input type="email" bind:value={email} required /></label><label>Contact phone<input type="tel" bind:value={phone} required /></label><label>Business address<input bind:value={address} required maxlength="100" /></label><label>Shareholder BVN<input type="password" inputmode="numeric" bind:value={bvn} pattern="[0-9]{11}" required autocomplete="off" /></label><label>Lifetime debit ceiling (₦)<input bind:value={ceiling} inputmode="decimal" required /></label><label><input type="checkbox" bind:checked={consent} required />I have the shareholder’s consent for identity verification. I authorize collection of my business’s billed Kredit fees after their due dates, within this ceiling. I will confirm the separate permission with my bank.</label><button disabled={!consent}>Start fee bank setup</button></fieldset></form>{/if}
{#if selected}<form onsubmit={e=>{e.preventDefault();void send({action,id:selected?.id,reference,evidence})}}><fieldset disabled={busy}><legend>Review before saving</legend>{#if admin}<p>{action==='customer'?'Link the provider customer that matches the saved shareholder identity.':'Confirm the separate bank fee mandate. The server checks its customer, reference, ceiling, dates and readiness.'}</p><label>Provider customer or mandate reference<input bind:value={reference} oninput={()=>reviewed=false} /></label><label>Evidence and verified receiving-bank instructions<textarea bind:value={evidence} oninput={()=>reviewed=false} minlength="20" maxlength="2000" required></textarea></label>{:else}<p>{#if action==='resume'}Request renewed fee debit approval using the original bank permission. Select it for billing and wait for super-admin review.{:else}Pause future fee debits. A request already sent will still be reconciled. Existing fees remain payable; this does not cancel the permission held by your bank.{/if}</p>{/if}<label><input type="checkbox" bind:checked={reviewed} required />I reviewed this change.</label><button disabled={!reviewed}>Save</button><button type="button" onclick={()=>selected=null}>Cancel</button></fieldset></form>{/if}</section>
<style>section,article{border:1px solid var(--color-border);padding:1rem;border-radius:.8rem;margin-block:1rem}fieldset{display:grid;gap:.8rem;border:0}label{display:grid;gap:.4rem}input,button,textarea{padding:.7rem;font:inherit}a,button{margin:.4rem}</style>
