<script lang="ts">
 import {checkedJSON,record,text,publicError} from '$lib/api/reliable';
 type Line={fee_id:string;obligation_id:string;type:string;amount_kobo:number;credit_kobo:number};
 type FeeInvoice={id:string;organization_id:string;business_name:string;business_address:string;payment_instructions:string;issued_at:string;due_at:string;period_end:string;total_kobo:number;credit_kobo:number;deducted_kobo:number;received_kobo:number;provider_received_kobo:number;refunded_kobo:number;outstanding_kobo:number;credit_balance_kobo:number;lines:Line[]};
 let {url,revision=0,onselect}:{url:string;revision?:number;onselect?:(invoice:FeeInvoice,direction:'received'|'refunded')=>void}=$props();
 let invoices=$state<FeeInvoice[]>([]),loading=$state(true),error=$state('');
 function money(value:unknown){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<0)throw new Error('Invalid invoice amount');return value}
 function date(value:unknown){const result=text(value);if(!Number.isFinite(Date.parse(result)))throw new Error('Invalid invoice date');return result}
 const amount=(value:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(value/100);
 let generation=0;
 async function load(source:string){const request=++generation;loading=true;error='';try{const data=await checkedJSON(source,record);if(!Array.isArray(data.invoices))throw new Error('Invalid invoices');const loaded=data.invoices.map(value=>{const r=record(value);if(r.currency!=='NGN'||!Array.isArray(r.lines))throw new Error('Invalid invoice');return{id:text(r.id),organization_id:text(r.organization_id),business_name:text(r.business_name),business_address:text(r.business_address),payment_instructions:text(r.payment_instructions),issued_at:date(r.issued_at),due_at:date(r.due_at),period_end:date(r.period_end),total_kobo:money(r.total_kobo),credit_kobo:money(r.credit_kobo),deducted_kobo:money(r.deducted_kobo),received_kobo:money(r.received_kobo),provider_received_kobo:money(r.provider_received_kobo),refunded_kobo:money(r.refunded_kobo),outstanding_kobo:money(r.outstanding_kobo),credit_balance_kobo:money(r.credit_balance_kobo),lines:r.lines.map(value=>{const l=record(value);return{fee_id:text(l.fee_id),obligation_id:text(l.obligation_id),type:text(l.type),amount_kobo:money(l.amount_kobo),credit_kobo:money(l.credit_kobo),deducted_kobo:money(l.deducted_kobo)}})}});if(request===generation)invoices=loaded}catch(cause){if(request===generation)error=publicError(cause,'Your fee bills could not be loaded.')}finally{if(request===generation)loading=false}}
 $effect(()=>{void revision;if(url)void load(url)});
</script>
<section aria-label="Kredit fee bills"><h2>Fee bills</h2><button class="no-print" disabled={loading} onclick={()=>load(url)}>Refresh bills</button>
{#if loading}<p role="status">Loading bills…</p>{:else if error}<p role="alert">{error}</p>{:else if !invoices.length}<p>No bills have been issued yet. Weekly bills close on Monday; monthly bills close on the first day of the month.</p>{:else}
{#each invoices as invoice(invoice.id)}<article><h3>Kredit fee bill</h3><p>Reference: {invoice.id}</p><p>{invoice.business_name}<br />{invoice.business_address}</p><p>Issued: {new Date(invoice.issued_at).toLocaleDateString('en-NG',{timeZone:'Africa/Lagos'})} · Due: {new Date(invoice.due_at).toLocaleDateString('en-NG',{timeZone:'Africa/Lagos'})}</p><div class="table-wrap"><table><thead><tr><th>Sale</th><th>Fee</th><th>Charged</th><th>Credited</th></tr></thead><tbody>{#each invoice.lines as line(line.fee_id)}<tr><td>{line.obligation_id}</td><td>{line.type==='base_service'?'Base fee':'Collection fee'}</td><td>{amount(line.amount_kobo)}</td><td>{amount(line.credit_kobo)}</td></tr>{/each}</tbody></table></div><p>Total: {amount(invoice.total_kobo)} · Credits: {amount(invoice.credit_kobo)} · Deducted from collections: {amount(invoice.deducted_kobo)} · Payments received: {amount(invoice.received_kobo)} · Confirmed bank debits: {amount(invoice.provider_received_kobo)} · Refunds recorded: {amount(invoice.refunded_kobo)}</p><p><strong>Left to pay: {amount(invoice.outstanding_kobo)}</strong></p>{#if invoice.credit_balance_kobo>0}<p>Credit balance: {amount(invoice.credit_balance_kobo)}. Contact support to arrange its return. This is not confirmation of a refund.</p>{/if}<h4>How to pay</h4><p class="instructions">{invoice.payment_instructions}</p><p>Use this bill reference when paying. A transfer counts only after Kredit confirms receipt.</p>{#if onselect&&invoice.outstanding_kobo>0}<button class="no-print" onclick={()=>onselect?.(invoice,'received')}>Record a received payment</button>{/if}{#if onselect&&invoice.credit_balance_kobo>0}<button class="no-print" onclick={()=>onselect?.(invoice,'refunded')}>Record a completed refund</button>{/if}</article>{/each}<button class="no-print" onclick={()=>window.print()}>Print or save bills</button>{/if}</section>
<style>article{border:1px solid var(--color-border);border-radius:1rem;padding:1.2rem;margin-block:1rem}p,td{overflow-wrap:anywhere}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:.6rem;text-align:left;border-bottom:1px solid var(--color-border)}.instructions{white-space:pre-wrap}button{font:inherit;padding:.65rem}@media print{.no-print{display:none}article{break-inside:avoid}}</style>
