<script lang="ts">
 import {checkedJSON,record,rows,text,publicError} from '$lib/api/reliable';
 import {MutationIntent} from '$lib/api/mutation';
 import {formatKobo} from '$lib/money';
 let {org,admin=false}:{org:string;admin?:boolean}=$props();
 type Bank={provider:string;allocated_kobo:number;received_kobo:number;returned_kobo:number;outstanding_kobo:number};type Debit={id:string;invoice_id:string;provider:string;amount_kobo:number;state:string;review_required:boolean};
 let banks=$state<Bank[]>([]),debits=$state<Debit[]>([]),busy=$state(false),error=$state(''),action=$state(''),id=$state(''),provider=$state(''),direction=$state('received'),amount=$state(''),reference=$state(''),date=$state(''),evidence=$state(''),reviewed=$state(false);
 const endpoint=$derived(admin?`/api/v1/ops/fee-operations/${encodeURIComponent(org)}`:`/api/v1/organizations/${encodeURIComponent(org)}/fee-operations`);let mutation:MutationIntent|null=null;let generation=0;
 function money(value:unknown){if(typeof value!=='number'||!Number.isSafeInteger(value))throw new Error('Invalid amount');return value}
 async function load(){const request=++generation;try{const data=await checkedJSON(endpoint,record);const b=rows('banks',v=>{const r=record(v);return{provider:text(r.provider),allocated_kobo:money(r.allocated_kobo),received_kobo:money(r.received_kobo),returned_kobo:money(r.returned_kobo),outstanding_kobo:money(r.outstanding_kobo)}})(data);const d=rows('debits',v=>{const r=record(v);return{id:text(r.id),invoice_id:text(r.invoice_id),provider:text(r.provider),amount_kobo:money(r.amount_kobo),state:text(r.state),review_required:r.review_required===true}})(data);if(request===generation){banks=b;debits=d}}catch(cause){if(request===generation)error=publicError(cause,'Fee movements could not be loaded.')}}
 $effect(()=>{if(org){action='';error='';void load()}});
 function choose(kind:string,ref:string,account=''){action=kind;id=ref;provider=account;amount='';reference='';date='';evidence='';reviewed=false;mutation=new MutationIntent('fee-operation',endpoint)}
 async function save(){if(!reviewed||busy||!mutation)return;busy=true;error='';try{let extra:Record<string,unknown>={};if(action==='bank'){if(!/^\d+(\.\d{1,2})?$/.test(amount))throw new Error('Enter a valid naira amount.');const [whole,fraction='']=amount.split('.');const kobo=Number(whole)*100+Number(fraction.padEnd(2,'0'));const when=new Date(date+'+01:00');if(!Number.isSafeInteger(kobo)||kobo<=0||!Number.isFinite(when.getTime()))throw new Error('Check the amount and bank date.');extra={provider,direction,bank_reference:reference,amount_kobo:kobo,received_at:when.toISOString()}}await mutation.run({action,id,evidence,...extra},value=>{if(record(value).saved!==true)throw new Error('Change not confirmed');return true});action='';await load()}catch(cause){error=publicError(cause,'The change is unconfirmed. Refresh before retrying.')}finally{busy=false}}
</script>
<section><h2>Fee collections and bank receipts</h2>{#if error}<p role="alert">{error}</p>{/if}<button disabled={busy} onclick={load}>Refresh fee movements</button>{#if !banks.length&&!debits.length}<p>No fee collections have been recorded.</p>{/if}{#each banks as bank(bank.provider)}<article><h3>{bank.provider}</h3><p>Fees collected: {formatKobo(bank.allocated_kobo)} · Bank receipts: {formatKobo(bank.received_kobo)} · Bank returns: {formatKobo(bank.returned_kobo)}</p><p>Awaiting bank reconciliation: {formatKobo(bank.outstanding_kobo)}</p>{#if admin}<button disabled={busy} onclick={()=>choose('bank','',bank.provider)}>Record completed bank movement</button>{/if}</article>{/each}{#each debits as debit(debit.id)}<article><p>Fee debit: {debit.id} · {debit.state} · {formatKobo(debit.amount_kobo)}</p>{#if debit.review_required}<p role="alert">The provider reported a dispute or reversal. Review the original bank evidence before making another payment.</p>{/if}<p>Bill: {debit.invoice_id} · {debit.provider}</p>{#if debit.state==='failed'}<p>The debit failed. Pay the bill using its bank instructions; it will not be automatically sent again.</p>{/if}{#if admin&&debit.review_required}<button disabled={busy} onclick={()=>choose('clear_review',debit.id)}>Review provider evidence</button>{/if}{#if admin&&debit.state==='pending'}<button disabled={busy} onclick={()=>choose('reconcile',debit.id)}>Check original provider reference</button>{/if}{#if admin&&debit.state==='succeeded'}<button disabled={busy} onclick={()=>choose('reversed',debit.id)}>Record a completed bank reversal</button>{/if}</article>{/each}
{#if action}<form onsubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy}><legend>Review before saving</legend>{#if action==='bank'}<p>Confirm an actual bank movement for fees from {provider}. This does not change the seller’s fee bill or buyer debt.</p><label>Direction<select bind:value={direction} onchange={()=>reviewed=false}><option value="received">Received by Kredit</option><option value="returned">Returned from Kredit</option></select></label><label>Amount (₦)<input bind:value={amount} oninput={()=>reviewed=false} required inputmode="decimal" /></label><label>Bank reference<input bind:value={reference} oninput={()=>reviewed=false} required maxlength="200" /></label><label>Completed at (Lagos time)<input type="datetime-local" bind:value={date} oninput={()=>reviewed=false} required /></label>{:else if action==='clear_review'}<p>Clear the review only after checking the bank evidence. The original provider must still confirm the recorded debit status and amount. This does not move money.</p>{:else if action==='reversed'}<p>Confirm that the bank reversed this completed fee debit. The seller’s bill becomes payable again. This records an existing reversal; it does not move money.</p>{:else}<p>Check the original provider account and saved debit reference. This does not send another debit.</p>{/if}{#if action!=='reconcile'}<label>Bank evidence reviewed<textarea bind:value={evidence} oninput={()=>reviewed=false} minlength="20" maxlength="2000" required></textarea></label>{/if}<label><input type="checkbox" bind:checked={reviewed} required />I reviewed the evidence and effect.</label><button disabled={!reviewed}>Save</button><button type="button" onclick={()=>action=''}>Cancel</button></fieldset></form>{/if}</section>
<style>section,article{padding:1rem;margin-block:1rem;border:1px solid var(--color-border);border-radius:.8rem}fieldset{display:grid;gap:1rem;border:0}label{display:grid;gap:.4rem}input,select,textarea,button{padding:.7rem;font:inherit}</style>
