<script lang="ts">
 import {onMount} from 'svelte';
 import {checkedJSON,record,text,publicError} from '$lib/api/reliable';
 import {adminPost} from '$lib/admin-client';
 import VerifyIdentity from './VerifyIdentity.svelte';
 let {review=false}:{review?:boolean}=$props();
 type Check={id:string;provider:string;kind:string;state:string;name:string;operation:string;version:number;document_id:string;verified_name:string;nin_status:string;cac_status:string};
 let items=$state<Check[]>([]),loading=$state(true),busy=$state(false),error=$state(''),message=$state(''),consentVersion=$state('');
 let values=$state<Record<string,string>>({}),consents=$state<Record<string,boolean>>({}),decisions=$state<Record<string,string>>({});
 async function load(){loading=true;error='';try{const result=await checkedJSON(`/api/v1/identity/checks${review?'?review=true':''}`,value=>{const body=record(value);if(!Array.isArray(body.cases))throw new Error('Invalid verification checks');return{consent:text(body.consent_version),items:body.cases.map(value=>{const c=record(value);if(!Number.isSafeInteger(c.version))throw new Error('Invalid verification version');return{id:text(c.id),provider:text(c.provider),kind:text(c.kind),state:text(c.state),name:text(c.name),operation:text(c.operation),version:c.version as number,document_id:text(c.document_id),verified_name:typeof record(c.safe_result).verified_name==='string'?text(record(c.safe_result).verified_name):'',nin_status:typeof record(c.safe_result).nin_status==='string'?text(record(c.safe_result).nin_status):'',cac_status:typeof record(c.safe_result).cac_status==='string'?text(record(c.safe_result).cac_status):''}})}});items=result.items;consentVersion=result.consent}catch(cause){error=publicError(cause,'Verification checks could not be loaded.')}finally{loading=false}}
 async function act(item:Check,action:string){if(busy)return;busy=true;error='';message='';try{await adminPost(`/api/v1/identity/checks/${encodeURIComponent(item.provider)}/${encodeURIComponent(item.id)}`,{action,expected_version:item.version,value:review?'':values[action==='phone_verify'?item.id+':otp':item.id]??'',evidence:review?values[item.id]??'':'',consent_version:consents[item.id]?consentVersion:''});values[item.id]='';values[item.id+':otp']='';message='Check saved. Refresh your business verification status to apply the result.';await load()}catch(cause){error=publicError(cause,'Verification was not confirmed. Refresh before trying again.')}finally{busy=false}}

 function documentPath(item:Check){return `/api/v1/identity/checks/${encodeURIComponent(item.provider)}/${encodeURIComponent(item.id)}/document`}
 async function upload(item:Check,file:File|undefined){if(!file||busy)return;if(file.size>2*1024*1024){error='Choose a PDF or image up to 2 MB.';return}busy=true;error='';try{const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('The file could not be read.'));reader.readAsDataURL(file)});await adminPost(documentPath(item),{file_name:file.name,content_type:file.type,content_base64:content});message='Document saved. It must pass its safety check before review.';await load()}catch(cause){error=publicError(cause,'Document upload was not confirmed.')}finally{busy=false}}
 async function openDocument(item:Check){try{const link=await checkedJSON(documentPath(item)+'?download=true',value=>{const url=new URL(text(record(value).url),location.origin);if(url.protocol!=='https:'||url.username||url.password)throw new Error('Invalid document address');return url.href});location.assign(link)}catch(cause){error=publicError(cause,'The document cannot be opened yet.')}}
 onMount(load);
</script>
<section><h2>{review?'Review identity and business authority':'Complete your verification'}</h2>
<p>{review?'Check the identity evidence and the document authorising this person to act for the business. Approval is recorded with your account and evidence reference.':'Use your NIN-linked phone and your business CAC registration number. Never send your NIN or verification code to support.'}</p>
{#if review}<VerifyIdentity/>{/if}
{#if message}<p role="status">{message}</p>{/if}{#if error}<p role="alert">{error}</p>{/if}
<button disabled={busy||loading} onclick={load}>Refresh saved checks</button>
{#if loading}<p>Loading checks…</p>{:else if items.length===0&&!error}<p>No saved interactive checks. Start or refresh your business verification first.</p>{/if}
{#each items as item(item.id)}<article><h3>{item.kind==='authority'?'Authority to act for the business':item.kind==='person'?'Personal identity':'Business registration'}</h3><p>{item.name} · {item.state} · {item.provider}</p>{#if item.verified_name}<p>Provider-confirmed name: {item.verified_name}</p>{/if}{#if item.nin_status}<p>Identity evidence: {item.nin_status}</p>{/if}{#if item.cac_status}<p>Registration evidence: {item.cac_status}</p>{/if}{#if item.document_id}<button disabled={busy} onclick={()=>openDocument(item)}>Open saved evidence document</button>{/if}{#if !review&&!['verified','failed'].includes(item.state)}<label>Supporting authority or identity document (PDF or image, up to 2 MB)<input type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy} onchange={(event)=>void upload(item,event.currentTarget.files?.[0])}/></label>{/if}
{#if item.operation}<p>The last request is awaiting confirmation. Phone codes expire after five minutes; you can then request a new code. For a business lookup, support must review the saved request.</p>{/if}
{#if !['verified','failed'].includes(item.state)||(review&&item.state==='failed')}
{#if review}<form onsubmit={(event)=>{event.preventDefault();void act(item,item.state==='failed'?'retry':decisions[item.id]??'approve')}}>{#if item.state==='failed'}<p>Reopen this rejected check after reviewing the appeal. The previous decision remains in the audit history; fresh evidence is required.</p>{:else}<label>Decision<select bind:value={decisions[item.id]}><option value="approve">Approve with supporting evidence</option><option value="reject">Reject</option><option value="retry">Release an interrupted lookup after evidence review</option></select></label>{/if}<label>Evidence reviewed<textarea bind:value={values[item.id]} required minlength="20" maxlength="2000" placeholder="Document reference, authority checked and reason. No identity numbers or secrets."></textarea></label><p>Approval permits this check to satisfy account verification. The other required checks must also be current.</p><button disabled={busy||(Boolean(item.operation)&&decisions[item.id]!=='retry')}>Record decision</button></form>
{:else if item.state==='expired'}<button disabled={busy} onclick={()=>act(item,'renew')}>Renew this check</button>{:else if item.kind==='person'}<form onsubmit={(event)=>{event.preventDefault();void act(item,'phone_start')}}><label>NIN-linked phone<input bind:value={values[item.id]} type="tel" autocomplete="tel" required maxlength="14"/></label><label><input type="checkbox" bind:checked={consents[item.id]} required/>I authorise Mono to retrieve my NIN-linked identity for Kredit’s account checks.</label><button disabled={busy}>Send verification code</button></form><form onsubmit={(event)=>{event.preventDefault();void act(item,'phone_verify')}}><label>Code received<input bind:value={values[item.id+':otp']} inputmode="numeric" autocomplete="one-time-code" required pattern={'[0-9]{4,8}'}/></label><button disabled={busy}>Verify code</button></form>
{:else if item.kind==='business'}<form onsubmit={(event)=>{event.preventDefault();void act(item,'business_lookup')}}><label>CAC registration number<input bind:value={values[item.id]} required maxlength="40"/></label><label><input type="checkbox" bind:checked={consents[item.id]} required/>I authorise Kredit to check this business’s registration through Mono.</label><button disabled={busy||Boolean(item.operation)}>Check registration</button></form>
{:else}<p>Support will review your authority to act for this business. Upload the signed authority document above.</p><a href="/app/help">Contact support</a>{/if}
{/if}</article>{/each}</section>
<style>section{margin-block:1.5rem}article{border:1px solid var(--border,#ddd);padding:1rem;margin-top:1rem;border-radius:.6rem}form,label{display:grid;gap:.5rem}form{margin-block:1rem}input,select,textarea,button{font:inherit;padding:.65rem}input[type=checkbox]{width:auto;justify-self:start}textarea{min-height:6rem}p{line-height:1.5}</style>
