<script lang="ts">
	import { onMount } from 'svelte';
	import { productLabel } from '$lib/product-language';
	let { preferencesHref = '/app/settings/notifications' } = $props<{ preferencesHref?: string }>();
	let items: any[] = $state([]), loading = $state(true), error = $state(''), filter = $state('all');
	const channel = (value: string) => ({ whatsapp: 'WhatsApp', email: 'Email', sms: 'SMS' } as Record<string,string>)[String(value).toLowerCase()] ?? productLabel(value);
	const messageName = (value: string) => ({
		PaymentDueSoon: 'Payment due soon', PaymentOverdue: 'Payment overdue', PaymentRecorded: 'Payment recorded', PaymentReceipt: 'Payment receipt',
		CreditRequestSent: 'Credit sale sent', CreditRequestAccepted: 'Credit sale accepted', GoodsReleased: 'Goods released', GoodsReceived: 'Goods received',
		CollectionSubmitted: 'Bank debit requested', CollectionSucceeded: 'Bank debit completed', CollectionFailed: 'Bank debit did not complete',
		DisputeOpened: 'Dispute opened', DisputeUpdated: 'Dispute updated',
		AccountRecoveryRequested: 'Account recovery started', AccountRecoveryCompleted: 'Account recovery completed',
		PrivacyRequestReceived: 'Information request received', PrivacyExportReady: 'Information copy ready', NotificationPreferencesChanged: 'Notification settings changed'
	} as Record<string,string>)[value] ?? productLabel(value);
	const visible = $derived(filter === 'all' ? items : filter === 'failed' ? items.filter((item)=>String(item.state).toLowerCase()==='failed'||item.failure_reason) : items.filter((item)=>String(item.channel).toLowerCase()===filter));
	const failures = $derived(items.filter((item)=>String(item.state).toLowerCase()==='failed'||item.failure_reason).length);
	const sentCount = $derived(items.filter((item)=>['sent','delivered','recognized','completed'].includes(String(item.state).toLowerCase())).length);
	onMount(async () => {
		const response = await fetch('/api/v1/me/notifications', { credentials: 'include' });
		const data = await response.json().catch(() => ({})); loading = false;
		if (!response.ok) { error = data.detail ?? 'We could not open your message history.'; return; }
		items = (data.notifications ?? []).sort((a: any, b: any) => new Date(b.sent_at || b.scheduled_at || 0).getTime() - new Date(a.sent_at || a.scheduled_at || 0).getTime());
	});
</script>

<main class="shell workspace messages"><header><p class="eyebrow">Message history</p><h1>Know what Kredit sent.<br />Know whether it arrived.</h1><p class="lede">Review reminders, payment messages and account notices by channel. Private codes are never shown here.</p></header>
{#if loading}<p role="status">Opening your messages…</p>{:else if error}<p class="error" role="alert">{error}</p>{:else}
<section class="summary"><article><span>Total messages</span><strong>{items.length}</strong></article><article><span>Sent or delivered</span><strong>{sentCount}</strong></article><article class:danger={failures>0}><span>Needs attention</span><strong>{failures}</strong></article></section>
<div class="toolbar" role="group" aria-label="Filter message history"><button class:active={filter==='all'} onclick={()=>filter='all'}>All</button><button class:active={filter==='whatsapp'} onclick={()=>filter='whatsapp'}>WhatsApp</button><button class:active={filter==='email'} onclick={()=>filter='email'}>Email</button><button class:active={filter==='sms'} onclick={()=>filter='sms'}>SMS</button><button class:active={filter==='failed'} onclick={()=>filter='failed'}>Failed</button><a href={preferencesHref}>Notification settings →</a></div>
{#if visible.length}<section class="list">{#each visible as item}<article class:failed-card={item.failure_reason}><div class="message-head"><div><span class="channel">{channel(item.channel)}</span><strong>{messageName(item.template)}</strong></div><span class="state">{productLabel(item.state)}</span></div><p class="body">{item.body || 'Kredit sent an account message.'}</p><div class="meta"><time>{new Date(item.sent_at || item.scheduled_at || item.failed_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</time>{#if item.recipient_hint}<span>{item.recipient_hint}</span>{/if}</div>{#if item.failure_reason}<p class="failed"><strong>Delivery problem:</strong> {item.failure_reason}</p>{/if}</article>{/each}</section>{:else}<section class="empty-state"><h2>{items.length?'No messages match this filter':'No messages yet'}</h2><p>{items.length?'Choose another channel to see more messages.':'Account, payment and reminder messages will appear here after Kredit sends them.'}</p></section>{/if}
<section class="explain"><strong>Why this history matters</strong><p>You can check whether a reminder was actually sent before following up with a customer. If a delivery failed, use another approved contact route rather than assuming the customer received it.</p></section>
{/if}</main>
<style>.messages{max-width:64rem}.messages header{max-width:52rem}.messages h1{max-width:15ch;font-family:Georgia,'Times New Roman',serif;font-size:clamp(3rem,6vw,5.2rem);font-weight:500;line-height:.94;letter-spacing:-.055em}.summary{display:grid;grid-template-columns:repeat(3,1fr);margin:2rem 0;border-top:1px solid var(--color-border);border-left:1px solid var(--color-border)}.summary article{display:grid;gap:.4rem;padding:1rem;border-right:1px solid var(--color-border);border-bottom:1px solid var(--color-border);background:#fffdf8}.summary span{color:var(--color-muted);font-size:.75rem}.summary strong{font-family:Georgia,'Times New Roman',serif;font-size:2rem;font-weight:500}.summary article.danger{border-top:4px solid #b42318}.toolbar{display:flex;align-items:center;gap:.4rem;flex-wrap:wrap;margin:1.5rem 0;padding:.6rem;background:#17181b}.toolbar button{min-height:2.6rem;padding:.55rem .8rem;border:1px solid #4b4c51;background:transparent;color:#d5d5d1;font:inherit;font-size:.75rem;font-weight:750}.toolbar button.active{border-color:#e85f3d;background:#e85f3d;color:#17181b}.toolbar a{margin-left:auto;color:#fff;font-size:.76rem;font-weight:750}.list{display:grid;gap:.75rem;margin-top:2rem}.list article{padding:1rem 1.1rem;border:1px solid var(--color-border);border-left:4px solid #2738d6;background:var(--color-surface)}.list article.failed-card{border-left-color:#b42318}.message-head{display:flex;justify-content:space-between;gap:1rem}.message-head>div{display:grid;gap:.25rem}.channel{color:#2738d6;font-size:.65rem;font-weight:850;letter-spacing:.08em;text-transform:uppercase}.state{font-size:.75rem;font-weight:750}.body{margin:.75rem 0;color:#343733;line-height:1.6}.meta{display:flex;justify-content:space-between;gap:1rem;color:var(--color-muted);font-size:.72rem}.failed,.error{color:var(--color-destructive)}.failed{margin:.75rem 0 0;padding:.7rem;background:#fff0ed}.empty-state{padding:3rem;background:#2738d6;color:#fff}.empty-state p{color:#d8dbff}.explain{margin-top:2rem;padding:1rem;border-left:4px solid #16794e;background:#edf8f2}.explain p{margin:.4rem 0;color:#59615c;line-height:1.6}@media(max-width:650px){.summary{grid-template-columns:1fr}.toolbar{align-items:stretch}.toolbar button{flex:1}.toolbar a{width:100%;margin:0;padding:.6rem}.message-head,.meta{align-items:flex-start;flex-direction:column;gap:.45rem}}</style>
