<script lang="ts">
 import VerifyIdentity from './VerifyIdentity.svelte';
 import {adminPost} from '$lib/admin-client';
 let {businessID,businessName}:{businessID:string;businessName:string}=$props();
 let email=$state(''),phone=$state(''),address=$state(''),bvn=$state(''),consent=$state(false),busy=$state(false),message=$state('');
 async function save(){if(busy||!consent)return;busy=true;message='';try{const result=await adminPost(`/api/v1/buyer/businesses/${encodeURIComponent(businessID)}/repayment-customer`,{email,phone,address,bvn,consent_version:'business-bank-v1'});if(result.registered!==true)throw new Error('Registration needs review.');message='Business bank details registered. Open your sale to give bank debit permission.'}catch(cause){message=cause instanceof Error?cause.message:'The bank setup is unconfirmed. Contact support before trying again.'}finally{bvn='';busy=false}}
</script>
<details><summary>Set up business bank repayment</summary><p>Register {businessName} before giving bank debit permission. Use the business name held by your bank. Mono requires the BVN of a company shareholder.</p><VerifyIdentity /><form onsubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy}><label>Business email<input type="email" bind:value={email} required autocomplete="email" /></label><label>Contact phone<input type="tel" bind:value={phone} required autocomplete="tel" /></label><label>Business address<input bind:value={address} required maxlength="100" autocomplete="street-address" /></label><label>Shareholder BVN<input type="password" inputmode="numeric" bind:value={bvn} pattern="[0-9]{11}" minlength="11" maxlength="11" autocomplete="off" required /></label><label><input type="checkbox" bind:checked={consent} required />I have the shareholder’s permission to send these details to Mono to verify and register this business for bank repayment. This step does not authorize a debit.</label><button disabled={!consent}>{busy?'Saving…':'Register bank details'}</button></fieldset></form>{#if message}<p role="status">{message}</p>{/if}</details>
<style>details{margin-block:1rem;padding:1rem;border:1px solid var(--color-border);border-radius:.8rem}fieldset{border:0;display:grid;gap:1rem}label{display:grid;gap:.4rem}input,button{padding:.7rem;font:inherit}</style>
