<script lang="ts">
	import { onMount } from 'svelte'; import { page } from '$app/state';
	import Skeleton from '$lib/components/Skeleton.svelte';
	import { productLabel } from '$lib/product-language';
	let { eyebrow,title,description,primaryLabel='',primaryHref='',endpoint='',organizationPath='',collectionKey='',detailBase='',showDetails=true,detailQueryOrganization=false,emptyTitle='Nothing here yet',emptyCopy='New items will show here.',tips=[] }:{eyebrow:string;title:string;description:string;primaryLabel?:string;primaryHref?:string;endpoint?:string;organizationPath?:string;collectionKey?:string;detailBase?:string;showDetails?:boolean;detailQueryOrganization?:boolean;emptyTitle?:string;emptyCopy?:string;tips?:string[]}=$props();
	let loading=$state(Boolean(endpoint||organizationPath)),error=$state(''),records:any[]=$state([]),organizations:any[]=$state([]),organizationID=$state(''),query=$state(''),pageNumber=$state(1);const pageSize=9;
	let filtered=$derived(records.filter((record)=>JSON.stringify(record).toLowerCase().includes(query.toLowerCase())));let visible=$derived(filtered.slice((pageNumber-1)*pageSize,pageNumber*pageSize));
	async function load(url:string){loading=true;error='';try{const r=await fetch(url,{credentials:'include'});if(r.status===401){location.assign('/app');return}if(!r.ok)throw new Error('We could not open this page.');const data=await r.json();const value=collectionKey?data[collectionKey]:data;records=Array.isArray(value)?value:[]}catch(e){error=e instanceof Error?e.message:'We could not open this page.'}finally{loading=false}}
	async function changeOrganization(){if(organizationID&&organizationPath)await load(`/api/v1/organizations/${organizationID}${organizationPath}`)}
	onMount(async()=>{if(organizationPath){const r=await fetch('/api/v1/organizations',{credentials:'include'});if(r.status===401){location.assign('/app');return}if(r.ok){const d=await r.json();organizations=d.organizations??[];organizationID=organizations[0]?.id??'';if(organizationID)await changeOrganization();else loading=false}else loading=false}else if(endpoint)await load(endpoint)});
</script>
<svelte:head><title>{title} — Kredit</title></svelte:head>
<main class="shell workspace"><header class="heading"><div><p class="eyebrow">{eyebrow}</p><h1>{title}</h1><p class="lede">{description}</p></div>{#if primaryHref}<a class="primary" href={primaryHref}>{primaryLabel}</a>{/if}</header>
{#if tips.length}<section class="tips" aria-label="Highlights">{#each tips as tip}<article><b>✓</b><p>{tip}</p></article>{/each}</section>{/if}
{#if endpoint||organizationPath}<div class="toolbar">{#if organizations.length>1}<label>Business<select bind:value={organizationID} onchange={changeOrganization}>{#each organizations as org}<option value={org.id}>{org.trading_name||org.legal_name}</option>{/each}</select></label>{/if}<label class="search"><span class="sr-only">Search</span><input bind:value={query} oninput={()=>pageNumber=1} type="search" placeholder="Search here…" /></label><button onclick={()=>organizationPath?changeOrganization():load(endpoint)}>Check again</button></div>{/if}
	{#if loading}<div class="loading" role="status"><span class="sr-only">Opening {title}</span><Skeleton rows={6} tall /></div>{:else if error}<div class="error" role="alert">{error} <button onclick={()=>organizationPath?changeOrganization():load(endpoint)}>Try again</button></div>{:else if filtered.length}<section class="records" aria-label={title}>{#each visible as item}{@const record=item.request??item}{@const detailID=detailBase.includes('/obligations')?(item.obligation?.id??''):record.id}<article><div><strong>{record.buyer_legal_name??record.legal_name??record.reason??record.reference??record.provider??record.id??'Item'}</strong><span class="status">{productLabel(record.state??record.status??'OPEN')}</span></div><p>{record.goods_description??record.explanation??record.subject_type??record.description??'Open this item to see more.'}</p>{#if showDetails && detailID}<a href={`${detailBase||page.url.pathname}/${detailID}${detailQueryOrganization?`?organization=${organizationID}`:''}`}>Open →</a>{/if}</article>{/each}</section>{#if filtered.length>pageSize}<nav class="pagination" aria-label="Pages"><button disabled={pageNumber===1} onclick={()=>pageNumber--}>Back</button><span>Page {pageNumber} of {Math.ceil(filtered.length/pageSize)}</span><button disabled={pageNumber>=Math.ceil(filtered.length/pageSize)} onclick={()=>pageNumber++}>Next</button></nav>{/if}{:else}<section class="empty-state"><div class="empty-icon" aria-hidden="true">◎</div><h2>{query?'Nothing found':emptyTitle}</h2><p>{query?'Try another word.':emptyCopy}</p>{#if primaryHref}<a class="primary-button" href={primaryHref}>{primaryLabel}</a>{/if}</section>{/if}</main>
<style>.heading{display:flex;align-items:end;justify-content:space-between;gap:3rem;margin-bottom:2.5rem;padding-bottom:2rem;border-bottom:3px solid #17181b}.heading h1{max-width:15ch;margin:.55rem 0;font-family:Georgia,'Times New Roman',serif;font-size:clamp(3rem,6vw,5.4rem);font-weight:500;line-height:.92;letter-spacing:-.055em}.tips{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:0;margin:1.5rem 0;border-top:1px solid var(--color-border);border-left:1px solid var(--color-border)}.tips article{display:flex;gap:.8rem;padding:1.15rem;border-right:1px solid var(--color-border);border-bottom:1px solid var(--color-border)}.tips b{color:#e85f3d}.tips p,.records p{margin:.1rem 0;color:var(--color-muted);line-height:1.5}.toolbar{display:flex;align-items:end;gap:.75rem;margin:2rem 0;padding:1rem;color:#fff;background:#17181b}.toolbar label{display:grid;gap:.35rem;font-weight:700}.search{flex:1}.toolbar input,.toolbar select,.toolbar button,.pagination button{box-sizing:border-box;width:100%;min-height:3rem;padding:.65rem .75rem;border:1px solid #4b4c51;border-radius:0;background:#fff;color:#17181b;font:inherit}.toolbar button{width:auto;color:#fff;background:#2738d6;border-color:#2738d6;font-weight:750}.records{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin:1.5rem 0}.records article{min-height:11rem;padding:1.35rem;border:1px solid var(--color-border);background:#fffdf8;box-shadow:6px 6px 0 #ded8cc}.records article>div{display:flex;justify-content:space-between;gap:1rem}.records a{margin-top:auto;color:var(--color-primary);font-weight:750}.pagination{display:flex;justify-content:center;align-items:center;gap:1rem;margin:1.5rem}.pagination button{width:auto}.loading{padding:3rem;text-align:center;color:var(--color-muted)}.empty-state{padding:clamp(2rem,6vw,5rem);color:#fff;background:#2738d6}.empty-state h2{max-width:14ch;font-family:Georgia,'Times New Roman',serif;font-size:clamp(2rem,4vw,3.5rem);font-weight:500}.empty-state p{color:#d6d9ff}.empty-icon{font-size:3rem;color:#ff8b70}.empty-state :global(.primary-button){color:#17181b;background:#fff}.error{padding:1rem;color:#fff;background:#b42318}@media(max-width:720px){.heading{display:block}.heading .primary{margin-top:1rem}.tips,.records{grid-template-columns:1fr}.toolbar{align-items:stretch;flex-direction:column}.toolbar button{width:100%}.records article{min-height:auto}}</style>
